// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: edc40268cce7

package platform

import "context"

// ClientAuthTokens: tokens returned by authentication operations.
type ClientAuthTokens struct {
	TokenExpiry  int    `json:"token_expiry,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	AccessToken  string `json:"access_token,omitempty"`
}

// AuthClient: authentication and token-flow operations.
type AuthClient struct {
	http *HTTPClient
}

func newAuthClient(h *HTTPClient) *AuthClient {
	return &AuthClient{http: h}
}

// AllowedAuthMethods: List supported auth methods
// Returns the complete catalogue of authentication methods the platform supports,
// including each method's stable slug, user-facing name, and description.
// Use this endpoint to render method labels in sign-in UIs or org settings screens
// without hardcoding copy or maintaining your own enum list. Results reflect the
// platform's source-of-truth catalogue and are consistent across all orgs.
// This endpoint requires only a publishable key and is accessible without an active
// user session, making it suitable for pre-authentication flows such as login page
// rendering or onboarding configuration.
func (a *AuthClient) AllowedAuthMethods(ctx context.Context) (JSONValue, error) {
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/auth/allowed_auth_methods"})
	if err != nil {
		return JSONValue{}, err
	}
	return data, nil
}

// Login: Authenticate with email and password
// Authenticates a user with an email address and password and returns a short-lived
// access token, a refresh token, and the authenticated user object. Use the refresh
// token with the `/auth/refresh` endpoint to obtain new access tokens without
// re-authenticating.
// Password login must be enabled for the app; apps that have disabled password
// authentication return HTTP 403. Requests are rate-limited per IP (10 per minute)
// and per email-IP pair (5 per minute) exceeding either limit returns HTTP 429.
func (a *AuthClient) Login(ctx context.Context, email string, password string) (*ClientAuthTokens, error) {
	body := map[string]JSONValue{}
	body["email"] = JSONOf(email)
	body["password"] = JSONOf(password)
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/login", Body: body})
	if err != nil {
		return nil, err
	}
	return &ClientAuthTokens{
		TokenExpiry:  data.Get("expires_in").IntValue(),
		RefreshToken: data.Get("refresh_token").StringValue(),
		AccessToken:  data.Get("token").StringValue(),
	}, nil
}

// RequestLoginMagicLink: Request a magic link for login
// Sends a magic link to the given email address so an existing user can sign in
// without a password. The user clicks the link in their email and is redirected to
// `redirect_uri` with a token; pass that token to `/auth/verify_link` to obtain
// session tokens.
// If no account exists for the email, the endpoint still returns success to prevent
// email enumeration no link is sent in that case. Both `email` and `redirect_uri`
// are required. Requests are rate-limited per IP (10 per minute) and per email-IP pair
// (3 per minute) exceeding either limit returns HTTP 429. Returns HTTP 204 on success.
func (a *AuthClient) RequestLoginMagicLink(ctx context.Context, email *string, redirectURI *string) (JSONValue, error) {
	body := map[string]JSONValue{}
	if email != nil {
		body["email"] = JSONOf(*email)
	}
	if redirectURI != nil {
		body["redirect_uri"] = JSONOf(*redirectURI)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/login/link", Body: body})
	if err != nil {
		return JSONValue{}, err
	}
	return data, nil
}

// Refresh: Refresh an access token
// Exchanges a valid refresh token for a new access token and a new refresh token,
// rotating the refresh token on every call. The response also includes the updated
// user object. Store the new refresh token and discard the old one.
// Refresh tokens are single-use submitting an already-consumed token returns HTTP 401.
// Rate limiting is applied per (user, IP) pair when the token can be verified, and
// falls back to IP-only when it cannot. The limit is 30 exchanges per minute per
// bucket; exceeding it returns HTTP 429.
func (a *AuthClient) Refresh(ctx context.Context, refreshToken string) (*ClientAuthTokens, error) {
	body := map[string]JSONValue{}
	body["refresh_token"] = JSONOf(refreshToken)
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/refresh", Body: body})
	if err != nil {
		return nil, err
	}
	return &ClientAuthTokens{
		TokenExpiry:  data.Get("expires_in").IntValue(),
		RefreshToken: data.Get("refresh_token").StringValue(),
		AccessToken:  data.Get("token").StringValue(),
	}, nil
}

// Register: Register a new user with email and password
// Creates a new user account and returns an access token, refresh token, and the new
// user object. Two registration paths are supported:
// - **Team registration**: supply `team_invite` with a valid team invite ID. The new
// user is added to that team immediately upon registration. Returns HTTP 404 if the
// invite is not found.
// - **Standard registration**: supply `password`. An `invite_code` may optionally be
// included for invite-gated apps; an invalid code returns HTTP 404.
// Exactly one of `team_invite` or `password` must be provided; omitting both returns
// HTTP 400. Password registration must be enabled for the app; disabled apps return
// HTTP 403. The response status is HTTP 201 on success.
func (a *AuthClient) Register(ctx context.Context, email string, alias *string, fullName *string, inviteCode *string, password *string, setOrg *string, teamInvite *string, timezone *string) (*ClientAuthTokens, error) {
	body := map[string]JSONValue{}
	body["email"] = JSONOf(email)
	if alias != nil {
		body["alias"] = JSONOf(*alias)
	}
	if fullName != nil {
		body["full_name"] = JSONOf(*fullName)
	}
	if inviteCode != nil {
		body["invite_code"] = JSONOf(*inviteCode)
	}
	if password != nil {
		body["password"] = JSONOf(*password)
	}
	if setOrg != nil {
		body["set_org"] = JSONOf(*setOrg)
	}
	if teamInvite != nil {
		body["team_invite"] = JSONOf(*teamInvite)
	}
	if timezone != nil {
		body["timezone"] = JSONOf(*timezone)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/register", Body: body})
	if err != nil {
		return nil, err
	}
	return &ClientAuthTokens{
		TokenExpiry:  data.Get("expires_in").IntValue(),
		RefreshToken: data.Get("refresh_token").StringValue(),
		AccessToken:  data.Get("token").StringValue(),
	}, nil
}

// RequestRegisterMagicLink: Request a magic link for registration
// Starts a passwordless registration flow by sending a verification link to the given
// email address. The recipient clicks the link and is redirected to `redirect_uri` with
// a token; pass that token to `/auth/verify_link` to complete registration and obtain
// session tokens.
// Profile fields (`full_name`, `alias`, `timezone`) are captured now and applied when
// the link is verified. Requests are rate-limited per IP (10 per minute) and per
// email-IP pair (3 per minute) exceeding either limit returns HTTP 429. Returns
// HTTP 204 on success.
func (a *AuthClient) RequestRegisterMagicLink(ctx context.Context, alias *string, email *string, fullName *string, redirectURI *string, setOrg *string, timezone *string) (JSONValue, error) {
	body := map[string]JSONValue{}
	if alias != nil {
		body["alias"] = JSONOf(*alias)
	}
	if email != nil {
		body["email"] = JSONOf(*email)
	}
	if fullName != nil {
		body["full_name"] = JSONOf(*fullName)
	}
	if redirectURI != nil {
		body["redirect_uri"] = JSONOf(*redirectURI)
	}
	if setOrg != nil {
		body["set_org"] = JSONOf(*setOrg)
	}
	if timezone != nil {
		body["timezone"] = JSONOf(*timezone)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/register/link", Body: body})
	if err != nil {
		return JSONValue{}, err
	}
	return data, nil
}

// RequestMagicLink: Request a magic link for login or registration
// Sends a passwordless magic link to the given email address. If an account with that
// email already exists, a login link is sent. If no account exists, a registration link
// is sent and the recipient completes sign-up by clicking through. This unified endpoint
// lets you implement a single email-entry UI that handles both cases transparently.
// The `redirect_uri` is validated against the app's registered hosts; an unregistered
// URI returns HTTP 400. Both `email` and `redirect_uri` are required. Requests are
// rate-limited per IP (10 per minute) and per email-IP pair (3 per minute). Returns
// HTTP 204 on success no body.
func (a *AuthClient) RequestMagicLink(ctx context.Context, email *string, redirectURI *string, setOrg *string) (JSONValue, error) {
	body := map[string]JSONValue{}
	if email != nil {
		body["email"] = JSONOf(*email)
	}
	if redirectURI != nil {
		body["redirect_uri"] = JSONOf(*redirectURI)
	}
	if setOrg != nil {
		body["set_org"] = JSONOf(*setOrg)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/request/link", Body: body})
	if err != nil {
		return JSONValue{}, err
	}
	return data, nil
}

// ExchangeLoginToken: Exchange a one-time login token for session tokens
// Consumes a single-use login token delivered via email and returns an access token,
// refresh token, and the authenticated user object. One-time tokens are issued by the
// passwordless login flow and expire after a short window; submitting an expired or
// already-used token returns HTTP 401.
// If `timezone` is provided and the user's current timezone is still the default
// (`"America/Los_Angeles"`), the account timezone is updated in the same request.
// Requests are rate-limited to 10 per IP per minute; exceeding this returns HTTP 429.
func (a *AuthClient) ExchangeLoginToken(ctx context.Context, token string, timezone *string) (*ClientAuthTokens, error) {
	body := map[string]JSONValue{}
	body["token"] = JSONOf(token)
	if timezone != nil {
		body["timezone"] = JSONOf(*timezone)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/token", Body: body})
	if err != nil {
		return nil, err
	}
	return &ClientAuthTokens{
		TokenExpiry:  data.Get("expires_in").IntValue(),
		RefreshToken: data.Get("refresh_token").StringValue(),
		AccessToken:  data.Get("token").StringValue(),
	}, nil
}

// VerifyMagicLink: Verify a magic link token
// Consumes a single-use token from a magic link URL and returns an access token,
// refresh token, and the authenticated user object. This endpoint completes both the
// login flow (initiated by `/auth/request_login_link`) and the registration flow
// (initiated by `/auth/request_register_link` or `/auth/request_link`).
// Extract the token from the `token` query parameter of the magic link redirect URI
// and POST it here. Expired or already-used tokens return HTTP 401 expired links
// carry the error code `expired_token`, unknown or already-used tokens carry
// `invalid_or_expired_token`. If the app has disabled passwordless authentication
// the request returns HTTP 403. Rate-limited to 10 requests per IP per minute
// exceeding this returns HTTP 429.
func (a *AuthClient) VerifyMagicLink(ctx context.Context, token *string) (*ClientAuthTokens, error) {
	body := map[string]JSONValue{}
	if token != nil {
		body["token"] = JSONOf(*token)
	}
	data, err := fetch[JSONValue](a.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/auth/verify/link", Body: body})
	if err != nil {
		return nil, err
	}
	return &ClientAuthTokens{
		TokenExpiry:  data.Get("expires_in").IntValue(),
		RefreshToken: data.Get("refresh_token").StringValue(),
		AccessToken:  data.Get("token").StringValue(),
	}, nil
}
