// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 09afe900cc1e

package platform

import (
	"context"
	"strings"
	"sync"
)

// Client: entry point for the platform API. Configure it with an API key
// and/or an access token, then reach resources through the version
// namespaces (client.V1.Agents) or the default-version accessors
// (client.Agents()).
type Client struct {
	// HTTP is the shared transport every resource issues requests through.
	HTTP *HTTPClient
	Auth *AuthClient
	V1   *V1

	baseURL        string
	defaultHeaders map[string]string

	mu           sync.Mutex
	refreshToken string
	sockets      []*Socket
}

// NewClient: build a client. Without options it targets https://platform.archastro.ai.
func NewClient(opts ...ClientOption) *Client {
	cfg := newClientConfig("https://platform.archastro.ai")
	for _, opt := range opts {
		opt(cfg)
	}
	c := &Client{
		HTTP:           newHTTPClient(cfg),
		baseURL:        cfg.BaseURL,
		defaultHeaders: cfg.DefaultHeaders,
	}
	c.Auth = newAuthClient(c.HTTP)
	c.V1 = newV1(c.HTTP)
	return c
}

// ActivityFeed: default-version alias for Client.V1.ActivityFeed.
func (c *Client) ActivityFeed() *ActivityFeedResource {
	return c.V1.ActivityFeed
}

// AgentComputers: default-version alias for Client.V1.AgentComputers.
func (c *Client) AgentComputers() *AgentComputerResource {
	return c.V1.AgentComputers
}

// AgentEnvVars: default-version alias for Client.V1.AgentEnvVars.
func (c *Client) AgentEnvVars() *AgentEnvVarResource {
	return c.V1.AgentEnvVars
}

// AgentHealthActions: default-version alias for Client.V1.AgentHealthActions.
func (c *Client) AgentHealthActions() *AgentHealthActionResource {
	return c.V1.AgentHealthActions
}

// AgentInstallations: default-version alias for Client.V1.AgentInstallations.
func (c *Client) AgentInstallations() *AgentInstallationResource {
	return c.V1.AgentInstallations
}

// AgentRoutineRuns: default-version alias for Client.V1.AgentRoutineRuns.
func (c *Client) AgentRoutineRuns() *AgentRoutineRunResource {
	return c.V1.AgentRoutineRuns
}

// AgentRoutines: default-version alias for Client.V1.AgentRoutines.
func (c *Client) AgentRoutines() *AgentRoutineResource {
	return c.V1.AgentRoutines
}

// AgentSessions: default-version alias for Client.V1.AgentSessions.
func (c *Client) AgentSessions() *AgentSessionResource {
	return c.V1.AgentSessions
}

// AgentSkills: default-version alias for Client.V1.AgentSkills.
func (c *Client) AgentSkills() *AgentSkillResource {
	return c.V1.AgentSkills
}

// AgentTools: default-version alias for Client.V1.AgentTools.
func (c *Client) AgentTools() *AgentToolResource {
	return c.V1.AgentTools
}

// Agents: default-version alias for Client.V1.Agents.
func (c *Client) Agents() *AgentResource {
	return c.V1.Agents
}

// Artifacts: default-version alias for Client.V1.Artifacts.
func (c *Client) Artifacts() *ArtifactResource {
	return c.V1.Artifacts
}

// AutomationRuns: default-version alias for Client.V1.AutomationRuns.
func (c *Client) AutomationRuns() *AutomationRunResource {
	return c.V1.AutomationRuns
}

// Automations: default-version alias for Client.V1.Automations.
func (c *Client) Automations() *AutomationResource {
	return c.V1.Automations
}

// BugReports: default-version alias for Client.V1.BugReports.
func (c *Client) BugReports() *BugReportResource {
	return c.V1.BugReports
}

// Config: default-version alias for Client.V1.Config.
func (c *Client) Config() *ConfigResource {
	return c.V1.Config
}

// CustomObjects: default-version alias for Client.V1.CustomObjects.
func (c *Client) CustomObjects() *CustomObjectResource {
	return c.V1.CustomObjects
}

// EventSubscriptionDeliveries: default-version alias for Client.V1.EventSubscriptionDeliveries.
func (c *Client) EventSubscriptionDeliveries() *EventSubscriptionDeliveryResource {
	return c.V1.EventSubscriptionDeliveries
}

// EventSubscriptions: default-version alias for Client.V1.EventSubscriptions.
func (c *Client) EventSubscriptions() *EventSubscriptionResource {
	return c.V1.EventSubscriptions
}

// Extractions: default-version alias for Client.V1.Extractions.
func (c *Client) Extractions() *ExtractionResource {
	return c.V1.Extractions
}

// Files: default-version alias for Client.V1.Files.
func (c *Client) Files() *FileResource {
	return c.V1.Files
}

// InstallationSources: default-version alias for Client.V1.InstallationSources.
func (c *Client) InstallationSources() *InstallationSourceResource {
	return c.V1.InstallationSources
}

// Invites: default-version alias for Client.V1.Invites.
func (c *Client) Invites() *InviteResource {
	return c.V1.Invites
}

// KnowledgeDocuments: default-version alias for Client.V1.KnowledgeDocuments.
func (c *Client) KnowledgeDocuments() *KnowledgeDocumentResource {
	return c.V1.KnowledgeDocuments
}

// KnowledgeIngestions: default-version alias for Client.V1.KnowledgeIngestions.
func (c *Client) KnowledgeIngestions() *KnowledgeIngestionResource {
	return c.V1.KnowledgeIngestions
}

// KnowledgeSources: default-version alias for Client.V1.KnowledgeSources.
func (c *Client) KnowledgeSources() *KnowledgeSourceResource {
	return c.V1.KnowledgeSources
}

// Kv: default-version alias for Client.V1.Kv.
func (c *Client) Kv() *KvResource {
	return c.V1.Kv
}

// NotificationPreferences: default-version alias for Client.V1.NotificationPreferences.
func (c *Client) NotificationPreferences() *NotificationPreferenceResource {
	return c.V1.NotificationPreferences
}

// Notifications: default-version alias for Client.V1.Notifications.
func (c *Client) Notifications() *NotificationResource {
	return c.V1.Notifications
}

// Orgs: default-version alias for Client.V1.Orgs.
func (c *Client) Orgs() *OrgResource {
	return c.V1.Orgs
}

// PrivateServiceDefinitions: default-version alias for Client.V1.PrivateServiceDefinitions.
func (c *Client) PrivateServiceDefinitions() *PrivateServiceDefinitionResource {
	return c.V1.PrivateServiceDefinitions
}

// PrivateServiceEnrollments: default-version alias for Client.V1.PrivateServiceEnrollments.
func (c *Client) PrivateServiceEnrollments() *PrivateServiceEnrollmentResource {
	return c.V1.PrivateServiceEnrollments
}

// PrivateServices: default-version alias for Client.V1.PrivateServices.
func (c *Client) PrivateServices() *PrivateServiceResource {
	return c.V1.PrivateServices
}

// Sandboxes: default-version alias for Client.V1.Sandboxes.
func (c *Client) Sandboxes() *SandboxResource {
	return c.V1.Sandboxes
}

// SlackChannelBindings: default-version alias for Client.V1.SlackChannelBindings.
func (c *Client) SlackChannelBindings() *SlackChannelBindingResource {
	return c.V1.SlackChannelBindings
}

// SolutionCategories: default-version alias for Client.V1.SolutionCategories.
func (c *Client) SolutionCategories() *SolutionCategoryResource {
	return c.V1.SolutionCategories
}

// SolutionInstances: default-version alias for Client.V1.SolutionInstances.
func (c *Client) SolutionInstances() *SolutionInstanceResource {
	return c.V1.SolutionInstances
}

// SolutionTags: default-version alias for Client.V1.SolutionTags.
func (c *Client) SolutionTags() *SolutionTagResource {
	return c.V1.SolutionTags
}

// Solutions: default-version alias for Client.V1.Solutions.
func (c *Client) Solutions() *SolutionResource {
	return c.V1.Solutions
}

// Status: default-version alias for Client.V1.Status.
func (c *Client) Status() *StatuResource {
	return c.V1.Status
}

// Tasks: default-version alias for Client.V1.Tasks.
func (c *Client) Tasks() *TaskResource {
	return c.V1.Tasks
}

// TeamMemberships: default-version alias for Client.V1.TeamMemberships.
func (c *Client) TeamMemberships() *TeamMembershipResource {
	return c.V1.TeamMemberships
}

// Teams: default-version alias for Client.V1.Teams.
func (c *Client) Teams() *TeamResource {
	return c.V1.Teams
}

// ThreadMessages: default-version alias for Client.V1.ThreadMessages.
func (c *Client) ThreadMessages() *ThreadMessageResource {
	return c.V1.ThreadMessages
}

// Threads: default-version alias for Client.V1.Threads.
func (c *Client) Threads() *ThreadResource {
	return c.V1.Threads
}

// Trajectories: default-version alias for Client.V1.Trajectories.
func (c *Client) Trajectories() *TrajectoryResource {
	return c.V1.Trajectories
}

// Users: default-version alias for Client.V1.Users.
func (c *Client) Users() *UserResource {
	return c.V1.Users
}

// WorkItems: default-version alias for Client.V1.WorkItems.
func (c *Client) WorkItems() *WorkItemResource {
	return c.V1.WorkItems
}

// Ai: default-version alias for Client.V1.Ai.
func (c *Client) Ai() *AiResource {
	return c.V1.Ai
}

// Oauth: default-version alias for Client.V1.Oauth.
func (c *Client) Oauth() *OauthResource {
	return c.V1.Oauth
}

// SetAccessToken: replace the bearer token sent on every request.
func (c *Client) SetAccessToken(token string) {
	c.HTTP.SetAccessToken(token)
}

// SetRefreshToken: store the refresh token used by automatic 401 retry.
func (c *Client) SetRefreshToken(token string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.refreshToken = token
}

// RefreshToken: the refresh token captured at login, if any.
func (c *Client) RefreshToken() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.refreshToken
}

// Close: disconnect every socket this client opened.
func (c *Client) Close() error {
	c.mu.Lock()
	sockets := c.sockets
	c.sockets = nil
	c.mu.Unlock()
	var firstErr error
	for _, socket := range sockets {
		if err := socket.Close(); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

func (c *Client) apiKey() string {
	for key, value := range c.defaultHeaders {
		if strings.EqualFold(key, "x-archastro-api-key") {
			return value
		}
	}
	return ""
}

// OpenSocket: open a Phoenix socket to the platform, injecting the
// client's API key and current access token as connect params. The
// returned socket is closed by Client.Close.
func (c *Client) OpenSocket(ctx context.Context, opts ...SocketOption) (*Socket, error) {
	params := map[string]string{}
	if key := c.apiKey(); key != "" {
		params["api_key"] = key
	}
	if token := c.HTTP.AccessToken(); token != "" {
		params["token"] = token
	}
	if params["token"] == "" {
		return nil, ErrMissingAccessToken
	}
	base := []SocketOption{WithSocketParams(params)}
	socket := NewSocket(websocketURL(c.baseURL, "/socket/api/websocket"), append(base, opts...)...)
	if err := socket.Connect(ctx); err != nil {
		return nil, err
	}
	c.mu.Lock()
	c.sockets = append(c.sockets, socket)
	c.mu.Unlock()
	return socket, nil
}

// NewClientWithSecretKey: Secret API key full admin access, no user JWT required
func NewClientWithSecretKey(key string, opts ...ClientOption) *Client {
	base := []ClientOption{
		WithDefaultHeaders(map[string]string{"x-archastro-api-key": key}),
	}
	return NewClient(append(base, opts...)...)
}

// NewClientWithToken: build a client from a publishable key plus an existing access token.
func NewClientWithToken(apiKey string, accessToken string, opts ...ClientOption) *Client {
	base := []ClientOption{
		WithDefaultHeaders(map[string]string{"x-archastro-api-key": apiKey}),
		WithAccessToken(accessToken),
	}
	return NewClient(append(base, opts...)...)
}

// NewClientWithCredentials: log in with credentials and return a ready
// client. When the login flow yields a refresh token, automatic 401
// token refresh is wired up.
func NewClientWithCredentials(ctx context.Context, apiKey string, email string, password string, opts ...ClientOption) (*Client, error) {
	base := []ClientOption{
		WithDefaultHeaders(map[string]string{"x-archastro-api-key": apiKey}),
	}
	client := NewClient(append(base, opts...)...)
	tokens, err := client.Auth.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}
	if tokens.AccessToken == "" {
		return nil, ErrLoginFailed
	}
	client.SetAccessToken(tokens.AccessToken)
	if tokens.RefreshToken != "" {
		client.SetRefreshToken(tokens.RefreshToken)
	}
	// Refresh runs on a separate refresh-only client so it can
	// never re-enter the main client's 401 retry.
	refreshBase := []ClientOption{
		WithBaseURL(client.baseURL),
		WithDefaultHeaders(map[string]string{"x-archastro-api-key": apiKey}),
		withRefreshOnly(),
	}
	refreshClient := NewClient(append(refreshBase, opts...)...)
	client.HTTP.SetRefreshHandler(func(ctx context.Context) (string, error) {
		current := client.RefreshToken()
		if current == "" {
			return "", ErrRefreshFailed
		}
		refreshed, err := refreshClient.Auth.Refresh(ctx, current)
		if err != nil {
			return "", err
		}
		if refreshed.AccessToken == "" {
			return "", ErrRefreshFailed
		}
		client.SetAccessToken(refreshed.AccessToken)
		if refreshed.RefreshToken != "" {
			client.SetRefreshToken(refreshed.RefreshToken)
		}
		return refreshed.AccessToken, nil
	})
	return client, nil
}
