// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d36448de938e

package platform

// ThreadSettings: Configuration settings for a thread that control AI agent behavior and other thread-level preferences.
type ThreadSettings struct {
	// AgentEnabled: Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured. `null` when a client explicitly cleared the setting.
	AgentEnabled *bool `json:"agent_enabled,omitempty"`
}

// Thread: A chat thread, representing a conversation channel that can be owned by a user, team, or agent and may contain messages, participants, and AI agent activity.
type Thread struct {
	// AgentUser: ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads.
	AgentUser *string `json:"agent_user,omitempty"`
	// CreatedAt: When the thread was created (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// Creator: User who created this thread. Returns a user ID (`usr_...`) by default, or an expanded user object when the association is loaded. `null` if the creator is unknown.
	Creator *JSONValue `json:"creator,omitempty"`
	// Description: Optional description or purpose statement for the thread. `null` if not set.
	Description *string `json:"description,omitempty"`
	// ID: Thread ID (`thr_...`).
	ID string `json:"id"`
	// IsChannel: Whether this thread operates as a channel a multi-member broadcast-style conversation.
	IsChannel *bool `json:"is_channel,omitempty"`
	// IsDefault: Whether this is the default thread for its owner. Each user or team has at most one default thread.
	IsDefault *bool `json:"is_default,omitempty"`
	// IsTransient: Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires.
	IsTransient *bool `json:"is_transient,omitempty"`
	// IsUnlisted: Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants.
	IsUnlisted *bool `json:"is_unlisted,omitempty"`
	// Key: Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set.
	Key *string `json:"key,omitempty"`
	// Kind: Thread subtype: `"standard"` for ordinary threads, `"personal"` for a user-and-owned-agents roster, `"feed"` for a post feed with inline replies, `"slack_mirror"` for the membership-strict mirror of a Slack channel, or `"slashwork_mirror"` for the membership-strict mirror of a Slashwork group. `personal` and `feed` are explicit creation options; mirror kinds are server-derived.
	Kind *string `json:"kind,omitempty"`
	// LastActivity: When the most recent message was posted in this thread, falling back to the thread's creation time if it has no messages. Always populated on thread list endpoints (which order by it, after default threads); `null` on endpoints that don't compute activity enrichment.
	LastActivity *string `json:"last_activity,omitempty"`
	// LastMessagePreview: Single-line snippet of the most recent message's text content (first non-empty line, truncated to 140 characters). Populated on thread list endpoints alongside `last_activity`; `null` when the thread has no messages, the latest message has no text content (e.g. attachment-only), or the endpoint doesn't compute activity enrichment.
	LastMessagePreview *string `json:"last_message_preview,omitempty"`
	// LastMessageSender: Display name of the sender of the most recent message the same message `last_message_preview` snippets. Populated on thread list endpoints; `null` when the thread has no messages or the endpoint doesn't compute activity enrichment.
	LastMessageSender *string `json:"last_message_sender,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Muted: Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery.
	Muted *bool `json:"muted,omitempty"`
	// Org: ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context.
	Org *string `json:"org,omitempty"`
	// ParentMessage: The message that spawned this thread as a sub-thread. `null` for top-level threads.
	ParentMessage *Message `json:"parent_message,omitempty"`
	// Participant: Array of participant user IDs (`usr_...`) who are members of this thread.
	Participant []string `json:"participant,omitempty"`
	// Participants: Expanded participant user objects for each member of this thread. Populated only when the association is loaded.
	Participants []User `json:"participants,omitempty"`
	// ParticipatingActor: Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested.
	ParticipatingActor []string `json:"participating_actor,omitempty"`
	// ParticipatingAgents: Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested.
	ParticipatingAgents []Agent `json:"participating_agents,omitempty"`
	// Role: The authenticated user's membership role in this thread, e.g. `"owner"`, `"member"`, or `"viewer"`. `null` if the user is not a member.
	Role *string `json:"role,omitempty"`
	// Sandbox: ID of the developer sandbox this thread is scoped to (`dsb_...`). `null` for production threads.
	Sandbox *string `json:"sandbox,omitempty"`
	// Settings: Per-thread configuration settings controlling AI agent behavior for this thread.
	Settings *ThreadSettings `json:"settings,omitempty"`
	// Slug: URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned.
	Slug *string `json:"slug,omitempty"`
	// SubThreads: Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested.
	SubThreads []map[string]JSONValue `json:"sub_threads,omitempty"`
	// Tags: Status tags on the thread (e.g. `"blocked"`, `"needs-review"`). Edited by any thread participant via the `/threads/:thread/tags` endpoints and filterable on the thread list endpoints. Empty array if none set.
	Tags []string `json:"tags,omitempty"`
	// Team: ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads.
	Team *string `json:"team,omitempty"`
	// Title: Human-readable name of the thread. `null` if no title has been set.
	Title *string `json:"title,omitempty"`
	// TTL: Offset-free expiry timestamp after which the thread may be automatically cleaned up. `null` if the thread does not expire.
	TTL *string `json:"ttl,omitempty"`
	// UnreadCount: Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested.
	UnreadCount *int `json:"unread_count,omitempty"`
	// UpdatedAt: When the thread was last modified (ISO 8601).
	UpdatedAt *string `json:"updated_at,omitempty"`
	// User: ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads.
	User *string `json:"user,omitempty"`
	// Visibility: Who can read the thread: `team` for every owning-team member, `restricted` for team-readable threads with an explicit roster, `private` for roster-only access, or `org` for every member of the owning organization.
	Visibility string `json:"visibility"`
}

// ThreadMessage: A single message posted to a thread, as seen from the developer portal. Includes sender information, optional attachments, and scoping identifiers.
type ThreadMessage struct {
	// ACL: Access control list for private messages. Only returned to resource owners (and privileged/org-admin viewers); `null` otherwise.
	ACL *ACL `json:"acl,omitempty"`
	// Admin: Admin-only diagnostic metadata for the message, including execution trajectory details. Only present in developer portal responses.
	Admin map[string]JSONValue `json:"admin,omitempty"`
	// Agent: Agent ID (`agt_...`) associated with the message. `null` if not agent-scoped.
	Agent *string `json:"agent,omitempty"`
	// AgentMode: Local agent execution mode for this message. One of `cli`, `embedded`, or `null` when the message was not created by a local agent execution path.
	AgentMode *string `json:"agent_mode,omitempty"`
	// App: App ID (`app_...`) that the message belongs to.
	App *string `json:"app,omitempty"`
	// Attachments: Files or media attached to the message. Empty array if no attachments are present.
	Attachments []Attachment `json:"attachments,omitempty"`
	// Content: Text content of the message. `null` if the message contains only attachments.
	Content *string `json:"content,omitempty"`
	// CreatedAt: When the message was posted to the thread (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// ID: Message ID (`msg_...`).
	ID string `json:"id"`
	// Metadata: Key-value metadata attached to the message. Always present; defaults to an empty object. The `metadata` query parameter filters on this same object, so a caller can read back the field it selects on.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: Organization ID (`org_...`) this message is scoped to. `null` if not org-scoped.
	Org *string `json:"org,omitempty"`
	// RootMessageID: ID of the root message in this reply chain (`msg_...`). `null` for a top-level message. The value is persisted when the reply is created, so callers can correlate a multi-turn session without walking parent messages.
	RootMessageID *string `json:"root_message_id,omitempty"`
	// Sandbox: Sandbox ID (`dsb_...`) this message is scoped to. `null` if not sandbox-scoped.
	Sandbox *string `json:"sandbox,omitempty"`
	// Sender: Public ID of the sender (e.g. `usr_...` or `agt_...`). `null` for system-generated messages.
	Sender *string `json:"sender,omitempty"`
	// SenderName: Display name of the message sender. `null` if unavailable.
	SenderName *string `json:"sender_name,omitempty"`
	// SenderType: Category of entity that sent the message. One of `"user"`, `"agent"`, or `"system"`.
	SenderType *string `json:"sender_type,omitempty"`
	// Team: Team ID (`tea_...`) associated with the message. `null` if not team-scoped.
	Team *string `json:"team,omitempty"`
	// Type: Optional client-defined classification for the message (for example `note` or `status`). Free-form string up to 64 characters. The value `system` is reserved for platform-authored messages and cannot be set by clients. `null` when unset.
	Type *string `json:"type,omitempty"`
	// User: User ID (`usr_...`) associated with the message. `null` if not user-scoped.
	User *string `json:"user,omitempty"`
	// Visibility: Message-level visibility. `default` follows thread membership; `private` is limited to the sender and ACL `read` grantees.
	Visibility *string `json:"visibility,omitempty"`
}

// ThreadReadStatus: The read status of a thread for a specific user, indicating how far they have read and how many messages remain unread.
type ThreadReadStatus struct {
	// LastReadMessage: Message ID (`msg_...`) of the last message the user has read in this thread. `null` if the user has never read any message in the thread.
	LastReadMessage *string `json:"last_read_message,omitempty"`
	// Thread: Thread ID (`thr_...`) that this read status belongs to.
	Thread string `json:"thread"`
	// UnreadCount: Number of messages in the thread that the user has not yet read.
	UnreadCount int `json:"unread_count"`
}
