// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: c776b9ebfa35

package platform

import (
	"encoding/json"
	"fmt"
)

// ChatMember: A participant in a chat thread, which may be either a human user or an AI agent. Exactly one of `user` or `agent` is populated depending on `type`.
type ChatMember struct {
	// Agent: Full agent object for this member. Populated when `type` is `"agent"`; `null` for user members.
	Agent *Agent `json:"agent,omitempty"`
	// MembershipType: Role of this member within the thread. Common values are `"owner"` and `"member"`. `null` when the membership type is not applicable.
	MembershipType *string `json:"membership_type,omitempty"`
	// Type: Kind of participant. One of `"user"` (a human user) or `"agent"` (an AI agent).
	Type string `json:"type"`
	// User: Full user object for this member. Populated when `type` is `"user"`; `null` for agent members.
	User *User `json:"user,omitempty"`
}

// ChatRoomModel: A point-in-time snapshot of a chat room's state, including its loaded messages, member roster, and pagination cursors. Returned when loading or refreshing a thread's message list.
type ChatRoomModel struct {
	// AfterCursor: Opaque cursor to pass when fetching messages newer than those in this snapshot. `null` when this snapshot already reflects the latest messages.
	AfterCursor *string `json:"after_cursor,omitempty"`
	// Agent: The agent associated with this chat room. `null` when no agent is attached.
	Agent *Agent `json:"agent,omitempty"`
	// BeforeCursor: Opaque cursor to pass when fetching messages older than those in this snapshot. `null` when the beginning of the thread history has been reached.
	BeforeCursor *string `json:"before_cursor,omitempty"`
	// IsTransient: Whether this thread is ephemeral. Transient threads are not retained in long-term storage and may be deleted when the session ends.
	IsTransient bool `json:"is_transient"`
	// Members: All active members of the chat room, including both human users and agents.
	Members []ChatMember `json:"members"`
	// Messages: The page of messages currently loaded for the thread, ordered chronologically. Use `before_cursor` or `after_cursor` to page through additional history.
	Messages []Message `json:"messages"`
	// MessagesLoadedOnLastUpdate: Number of messages that were added to the snapshot in the most recent incremental update. `null` on the initial load.
	MessagesLoadedOnLastUpdate *int `json:"messages_loaded_on_last_update,omitempty"`
	// Team: The team that owns this thread. `null` for threads scoped to an individual user rather than a team.
	Team *Team `json:"team,omitempty"`
	// Thread: The parent thread whose message history and membership this snapshot represents.
	Thread *Thread `json:"thread"`
}

// ChatForkThreadResponse: Response returned after forking a chat thread. Contains the new thread, its initial chat-room snapshot, and the owning team when applicable.
type ChatForkThreadResponse struct {
	// ChatModel: Initial chat-room render snapshot for the forked thread, including members and loaded messages. `null` for transient threads whose room model is suppressed.
	ChatModel *ChatRoomModel `json:"chat_model,omitempty"`
	// Team: Team that owns the forked thread. Present only when the original thread was team-scoped; `null` for personal threads.
	Team *Team `json:"team,omitempty"`
	// Thread: The newly-created thread produced by the fork operation.
	Thread *Thread `json:"thread"`
}

// ChatLoadMoreMessagesResponse: Response returned after loading an additional page of chat messages. Contains a refreshed chat-room snapshot with the newly-fetched messages merged in.
type ChatLoadMoreMessagesResponse struct {
	// Data: Updated chat-room snapshot for the thread, incorporating the newly-loaded page of messages alongside any previously loaded messages.
	Data *ChatRoomModel `json:"data"`
}

// ChatLocalToolCall: One local function invocation requested by the model.
type ChatLocalToolCall struct {
	Arguments map[string]JSONValue `json:"arguments"`
	ID        string               `json:"id"`
	Name      string               `json:"name"`
}

// ChatLocalToolFunction: A function implemented by the client connected to a personal thread.
type ChatLocalToolFunction struct {
	Description string               `json:"description"`
	Name        string               `json:"name"`
	Parameters  map[string]JSONValue `json:"parameters"`
}

// ChatLocalToolDefinition: An OpenAI-compatible local function definition advertised by a personal-thread connection.
type ChatLocalToolDefinition struct {
	Function *ChatLocalToolFunction `json:"function"`
	Type     string                 `json:"type"`
}

// ChatLocalToolProvider: Server-issued identity for the local-tool set currently advertised by this connection.
type ChatLocalToolProvider struct {
	Generation int    `json:"generation"`
	ProviderID string `json:"provider_id"`
}

// ChatLocalToolRequest: A correlated batch of local function calls targeted to one connection.
type ChatLocalToolRequest struct {
	Calls []ChatLocalToolCall `json:"calls"`
	ID    string              `json:"id"`
}

// ChatLocalToolResultError: A failed local-tool outcome.
type ChatLocalToolResultError struct {
	CallID  string `json:"call_id"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Status  string `json:"status"`
}

// ChatLocalToolResult: One terminal local-tool outcome returned by the owning client connection.
//
// Exactly one variant pointer is set when the payload matched a known
// variant. Raw always carries the undecoded payload.
type ChatLocalToolResult struct {
	Ok                       *Ok
	ChatLocalToolResultError *ChatLocalToolResultError
	Cancelled                *Cancelled
	Raw                      JSONValue
}

// UnmarshalJSON decodes the union payload.
func (u *ChatLocalToolResult) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &u.Raw); err != nil {
		return err
	}
	tag := u.Raw.Get("status").StringValue()
	switch tag {
	case "cancelled":
		var v Cancelled
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Cancelled = &v
		return nil
	case "error":
		var v ChatLocalToolResultError
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.ChatLocalToolResultError = &v
		return nil
	case "ok":
		var v Ok
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Ok = &v
		return nil
	default:
		return fmt.Errorf("ChatLocalToolResult: unknown status tag %q", tag)
	}
}

// MarshalJSON re-encodes whichever variant is set.
func (u ChatLocalToolResult) MarshalJSON() ([]byte, error) {
	if u.Ok != nil {
		return json.Marshal(u.Ok)
	}
	if u.ChatLocalToolResultError != nil {
		return json.Marshal(u.ChatLocalToolResultError)
	}
	if u.Cancelled != nil {
		return json.Marshal(u.Cancelled)
	}
	return json.Marshal(u.Raw)
}

// ChatMarkThreadReadResponse: Response returned after marking a chat thread as read. Confirms that the read marker was successfully recorded for the authenticated user.
type ChatMarkThreadReadResponse struct {
	// Success: Indicates whether the read marker was successfully applied. Always `true` on success; errors are returned as channel error replies rather than a `false` value here.
	Success bool `json:"success"`
}

// ChatMessageListResponse: Response returned when listing the messages of a joined chat thread. Contains the set of messages currently loaded for the thread.
type ChatMessageListResponse struct {
	// Messages: Ordered array of message objects currently loaded for the thread, from oldest to newest. Use the `load_more_messages` channel message to fetch earlier pages.
	Messages []Message `json:"messages"`
}

// ChatPostMessageResponse: Response returned after successfully posting a message to a chat thread. Contains the persisted message object echoed back to the sender.
type ChatPostMessageResponse struct {
	// Message: The message that was created and stored. Contains the full message object including its assigned ID, author, content, and timestamps.
	Message *Message `json:"message"`
}
