// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6377be2fbe52

package platform

// AIChatStreamDone: Terminal event marking the end of a streaming chat completion (SSE `done` event).
type AIChatStreamDone struct {
	// FinishReason: The overall finish reason for the completion.
	FinishReason *string `json:"finish_reason,omitempty"`
	// RunCount: Number of model runs executed, including continuations triggered by tool calls.
	RunCount *int `json:"run_count,omitempty"`
	// TotalUsage: Aggregate token usage across every run in the completion (including tool-call continuations), keyed by model ID.
	TotalUsage map[string]JSONValue `json:"total_usage,omitempty"`
	// Usage: Token usage for the final run, keyed by model ID.
	Usage map[string]JSONValue `json:"usage,omitempty"`
}

// AIChatStreamError: Terminal error event for a streaming chat completion (SSE `error` event).
type AIChatStreamError struct {
	// Message: Human-readable description of the error that terminated the stream.
	Message string `json:"message"`
}

// AIToolCall: A tool (function) call emitted by the assistant within an AI message. Mirrors the OpenAI tool-call object format.
type AIToolCall struct {
	// Arguments: Arguments the model wants to pass to the tool, as a key-value map. Deserialize and validate these against the tool's input schema before executing.
	Arguments map[string]JSONValue `json:"arguments"`
	// ID: Unique identifier for this tool call, assigned by the model. Use this value as `id` when submitting the corresponding tool result.
	ID string `json:"id"`
	// Name: Name of the tool or function the model wants to invoke, e.g. `"web_search"` or `"run_code"`.
	Name string `json:"name"`
	// ThoughtSignature: Opaque signature representing the model's internal reasoning that led to this tool call. `null` when the provider does not expose chain-of-thought data.
	ThoughtSignature *string `json:"thought_signature,omitempty"`
}

// AIToolResult: The result of executing a tool call, submitted back to the model as a tool-role message. Mirrors the OpenAI tool-result object format.
type AIToolResult struct {
	// Content: Plain-text output produced by the tool execution. `null` when the result is expressed entirely through `resolution`.
	Content *string `json:"content,omitempty"`
	// ID: ID of the tool call this result satisfies. Must match the `id` from the corresponding `AIToolCall`.
	ID string `json:"id"`
	// Name: Name of the tool or function that was executed, e.g. `"web_search"`. Must match the `name` from the corresponding `AIToolCall`.
	Name string `json:"name"`
	// Resolution: Structured result data from the tool execution. Shape varies by tool. `null` when the result is expressed as plain text in `content`.
	Resolution *JSONValue `json:"resolution,omitempty"`
}

// AIMessage: A single message in an AI conversation, following the OpenAI-compatible chat format. Used in both request inputs and completion responses.
type AIMessage struct {
	// Content: Plain-text content of the message. Present for `system`, `user`, and `assistant` messages. `null` when the message body is expressed through `content_parts` or `tool_calls`.
	Content *string `json:"content,omitempty"`
	// ContentParts: Multimodal content parts for the message, used when the body includes images or mixed media. Each part is a map with a `type` key (`"text"`, `"image_url"`, or `"image_data"`). `null` when `content` is set.
	ContentParts []map[string]JSONValue `json:"content_parts,omitempty"`
	// ResumeToken: Opaque token that can be passed on a subsequent request to resume this conversation from the current state. `null` when the provider does not support conversation resumption.
	ResumeToken *string `json:"resume_token,omitempty"`
	// Role: The speaker role for this message. One of `"system"`, `"user"`, `"assistant"`, or `"tool"`.
	Role string `json:"role"`
	// StructuredOutput: Parsed structured data returned by the model when a JSON schema or structured-output mode was requested. Shape varies by the schema supplied at call time. `null` when structured output was not requested.
	StructuredOutput *JSONValue `json:"structured_output,omitempty"`
	// ToolCalls: Tool calls requested by the model in an `assistant` message. Present only on assistant messages that invoke one or more tools. `null` on all other message roles.
	ToolCalls []AIToolCall `json:"tool_calls,omitempty"`
	// ToolResults: Tool execution results provided in a `tool` message. Each entry corresponds to a prior tool call by its `id`. `null` on all other message roles.
	ToolResults []AIToolResult `json:"tool_results,omitempty"`
}

// AIChatStreamMessageComplete: The fully assembled assistant message for one run of a streaming chat completion (SSE `message_complete` event).
type AIChatStreamMessageComplete struct {
	// FinishReason: Why the model stopped generating this message, e.g. `"stop"`, `"length"`, or `"tool_calls"`.
	FinishReason *string `json:"finish_reason,omitempty"`
	// Message: The complete assistant message for this run, assembled from the preceding deltas.
	Message *AIMessage `json:"message"`
	// Usage: Token consumption for this run, keyed by model ID. `null` when usage data is unavailable.
	Usage map[string]JSONValue `json:"usage,omitempty"`
}

// AIChatStreamMessageDelta: Incremental assistant text emitted during a streaming chat completion (SSE `message_delta` event).
type AIChatStreamMessageDelta struct {
	// Delta: The chunk of assistant text produced since the previous `message_delta` event. Concatenate deltas in order to reconstruct the message.
	Delta string `json:"delta"`
}

// AIChatStreamThinkingDelta: Incremental model reasoning emitted during a streaming chat completion (SSE `thinking_delta` event).
type AIChatStreamThinkingDelta struct {
	// Delta: The chunk of model reasoning produced since the previous `thinking_delta` event.
	Delta string `json:"delta"`
}

// AIChatStreamToolCallDelta: Incremental tool-call data emitted as the model assembles a tool invocation (SSE `tool_call_delta` event).
type AIChatStreamToolCallDelta struct {
	// Delta: A chunk of the tool call's serialized arguments. Concatenate deltas to reconstruct the arguments JSON.
	Delta *string `json:"delta,omitempty"`
	// ID: Identifier of the tool call this delta belongs to, once the model has assigned one.
	ID *string `json:"id,omitempty"`
	// Name: Name of the tool being called, once known.
	Name *string `json:"name,omitempty"`
}

// AIChatStreamToolResult: The result of a server-executed tool, streamed back into the run (SSE `tool_result` event).
type AIChatStreamToolResult struct {
	// Content: The tool's output, serialized as a string.
	Content *string `json:"content,omitempty"`
	// ID: ID of the tool call this result satisfies.
	ID *string `json:"id,omitempty"`
	// Name: Name of the tool that produced this result.
	Name *string `json:"name,omitempty"`
	// Resolution: How the tool call resolved, e.g. `"ok"` or `"error"`.
	Resolution *string `json:"resolution,omitempty"`
}

// AICompletionResult: The result of an AI chat completion request. Returned by chat completion endpoints after the model finishes generating.
type AICompletionResult struct {
	// FinishReason: The reason the model stopped generating. Common values include `"stop"` (natural end), `"length"` (token limit reached), and `"tool_calls"` (the model invoked a tool).
	FinishReason string `json:"finish_reason"`
	// Message: The final assistant message produced by the completion.
	Message *AIMessage `json:"message"`
	// Messages: The complete message history for the conversation, including all user, assistant, and tool messages in order.
	Messages []AIMessage `json:"messages"`
	// TokenUsage: Token consumption breakdown keyed by model ID. Each value is a map with `"input_tokens"` and `"output_tokens"` counts. `null` when usage data is unavailable.
	TokenUsage map[string]JSONValue `json:"token_usage,omitempty"`
}

// AIImageResult: The result returned by an AI image generation or editing operation. Contains the generated image (as inline data or a URL) along with dimension, size, and usage metadata.
type AIImageResult struct {
	// AspectRatio: Aspect ratio of the generated image, e.g. `"16:9"` or `"1:1"`. `null` when not reported by the provider.
	AspectRatio *string `json:"aspect_ratio,omitempty"`
	// Height: Height of the generated image in pixels. `null` when the provider does not report dimensions.
	Height *int `json:"height,omitempty"`
	// ImageData: The generated image encoded as a base64 string. Present when the provider returns inline image data. `null` when `image_url` is set instead.
	ImageData *string `json:"image_data,omitempty"`
	// ImageSize: Resolution tier label for the image, e.g. `"1K"` or `"2K"`. `null` when the provider does not include a tier label.
	ImageSize *string `json:"image_size,omitempty"`
	// ImageType: MIME type of the generated image, e.g. `"image/png"` or `"image/jpeg"`. `null` when the provider does not report a content type.
	ImageType *string `json:"image_type,omitempty"`
	// ImageURL: Temporary URL pointing to the generated image hosted by the provider. Present when the provider returns a URL rather than inline data. `null` when `image_data` is set instead.
	ImageURL *string `json:"image_url,omitempty"`
	// Model: Identifier of the model that produced the image, e.g. `"dall-e-3"` or `"imagen-3"`.
	Model string `json:"model"`
	// RevisedPrompt: The prompt as rewritten by the provider before generation. Some providers (e.g. DALL-E 3) automatically expand or safety-check the original prompt. `null` when the provider does not revise prompts.
	RevisedPrompt *string `json:"revised_prompt,omitempty"`
	// Size: Canonical size string as returned by the provider, e.g. `"1024x1024"`. `null` when not reported.
	Size *string `json:"size,omitempty"`
	// Usage: Provider-reported token and compute usage for the request. Structure varies by provider. `null` when usage data is unavailable.
	Usage map[string]JSONValue `json:"usage,omitempty"`
	// Width: Width of the generated image in pixels. `null` when the provider does not report dimensions.
	Width *int `json:"width,omitempty"`
}
