// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: b5a136ed76ab

package platform

// OAuthTokenResponse: A successful OAuth 2.0 token response. Issued by the token endpoint after a completed authorization or device-flow grant.
type OAuthTokenResponse struct {
	// AccessToken: Bearer token used to authenticate API requests. Include this value in the `Authorization: Bearer <token>` header.
	AccessToken string `json:"access_token"`
	// ExpiresIn: Number of seconds until the access token expires.
	ExpiresIn int `json:"expires_in"`
	// RefreshToken: Token that can be exchanged for a new access token once the current one expires. `null` if the grant type does not issue refresh tokens.
	RefreshToken *string `json:"refresh_token,omitempty"`
	// Scope: Space-separated list of scopes granted to the access token. `null` if scope was not included in the grant request.
	Scope *string `json:"scope,omitempty"`
	// TokenType: Token type. Always `"Bearer"`.
	TokenType string `json:"token_type"`
	// User: The authenticated user associated with this token. `null` when the token is not tied to a specific user (e.g. client-credentials grants).
	User *User `json:"user,omitempty"`
}
