// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 76881bd6eaf1

package platform

import (
	"context"
	"net/url"
)

type ArtifactCreateInputFile struct {
	// Data: File content encoded according to file.encoding (base64 by default).
	Data string `json:"data"`
	// Encoding: Data encoding; defaults to base64. Use utf8 for script-generated text.
	Encoding *string `json:"encoding,omitempty"`
	// Filename: Original filename.
	Filename *string `json:"filename,omitempty"`
	// MimeType: MIME type for the file.
	MimeType *string `json:"mime_type,omitempty"`
}

// ArtifactCreateInput: Create an artifact
type ArtifactCreateInput struct {
	// Agent: Agent ID (`agt_...`) to associate with the artifact.
	Agent *string `json:"agent,omitempty"`
	// Artifact: Legacy wrapper object containing artifact attributes. Prefer top-level fields.
	Artifact map[string]JSONValue `json:"artifact,omitempty"`
	// Description: Optional longer artifact description.
	Description *string `json:"description,omitempty"`
	// File: File payload for the initial artifact version.
	File *ArtifactCreateInputFile `json:"file,omitempty"`
	// GroupKey: Optional nonunique, case-sensitive grouping key, limited to 1024 UTF-8 bytes. Artifact ID remains identity.
	GroupKey *string `json:"group_key,omitempty"`
	// IdempotencyKey: Optional PR-evidence retry key, limited to 255 characters. Requires both team and thread. Matching app, team, thread, name, and key values return the original artifact.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Name: Human-readable artifact name.
	Name *string `json:"name,omitempty"`
	// Org: Organization owning a system artifact. Requires an organization admin or system viewer.
	Org *string `json:"org,omitempty"`
	// Permissions: Optional artifact permissions map.
	Permissions map[string]JSONValue `json:"permissions,omitempty"`
	// System: When true, create a system-owned artifact. Mutually exclusive with `team` and `user`.
	System *bool `json:"system,omitempty"`
	// Team: Team ID (`tem_...`) that should own the artifact. Mutually exclusive with `user`.
	Team *string `json:"team,omitempty"`
	// Thread: Thread ID (`thr_...`) to associate with the artifact.
	Thread *string `json:"thread,omitempty"`
	// User: User ID (`usr_...`) that should own the artifact. Defaults to the authenticated user when omitted and no team is supplied.
	User *string `json:"user,omitempty"`
}

type ArtifactReplaceInputFile struct {
	// Data: File content encoded according to file.encoding.
	Data string `json:"data"`
	// Encoding: Data encoding; defaults to base64. Use utf8 for script-generated text.
	Encoding *string `json:"encoding,omitempty"`
	// Filename: Original filename for the uploaded file.
	Filename *string `json:"filename,omitempty"`
	// MimeType: MIME type of the uploaded file.
	MimeType *string `json:"mime_type,omitempty"`
}

// ArtifactReplaceInput: Update an artifact
type ArtifactReplaceInput struct {
	// Description: New description for the artifact. Omit to leave the existing description unchanged.
	Description *string `json:"description,omitempty"`
	// File: Replacement file payload. Omit to leave the current file unchanged.
	File *ArtifactReplaceInputFile `json:"file,omitempty"`
	// FileContent: Legacy flat Base64 file content. Prefer `file.data`.
	FileContent *string `json:"file_content,omitempty"`
	// FileContentType: Legacy flat MIME type. Prefer `file.mime_type`.
	FileContentType *string `json:"file_content_type,omitempty"`
	// FileName: Legacy flat filename. Prefer `file.filename`.
	FileName *string `json:"file_name,omitempty"`
	// FromVersion: The artifact's current version number, used for optimistic concurrency control. Returns 409 if this value does not match the server's current version.
	FromVersion int `json:"from_version"`
	// GroupKey: Nonunique grouping key, limited to 1024 UTF-8 bytes. Omit to preserve; null clears. Grouping-only updates do not increment the content version and from_version does not protect against concurrent metadata updates.
	GroupKey *string `json:"group_key,omitempty"`
	// Name: New display name for the artifact. Omit to leave the existing name unchanged.
	Name *string `json:"name,omitempty"`
}

// ArtifactContentParams: query parameters for ArtifactResource.Content.
type ArtifactContentParams struct {
	// Version: Version number to retrieve. Omit to return the artifact's current version.
	Version *int
}

type ArtifactResource struct {
	http *HTTPClient
}

func newArtifactResource(h *HTTPClient) *ArtifactResource {
	return &ArtifactResource{
		http: h,
	}
}

// Create: Create an artifact
//
// Creates a new artifact and stores its file content. A file payload is required;
// supply it via the `file.data` (Base64-encoded by default), `file.filename`, and
// `file.mime_type` fields. The artifact is scoped to the owner resolved from the
// request body either a team, a user, or an explicit system owner. When no
// owner is supplied and the viewer is an authenticated user, the artifact
// defaults to that user.
// For company-readable snapshots, pass `system: true` and `org`. Organization
// members can read these artifacts; organization admins and system viewers can
// create them. Scripts may supply text directly using `file.encoding: "utf8"`.
// Optionally associate the artifact with an existing thread or agent by passing
// `thread` or `agent`. Legacy requests that wrap fields in an `artifact` object
// are still accepted.
//
// Returns: The newly created artifact.
func (r *ArtifactResource) Create(ctx context.Context, input ArtifactCreateInput) (*Artifact, error) {
	return fetch[*Artifact](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/artifacts", Body: input})
}

// Delete: Delete an artifact
//
// Permanently deletes the artifact and all associated file versions. This
// operation is irreversible deleted artifacts and their file content cannot
// be recovered.
// The authenticated user must have write access to the artifact's owning team
// or organization. Returns 404 if the artifact does not exist or is not
// accessible to the caller.
//
// artifact: Artifact ID (`art_...`) of the artifact to delete.
//
// Returns: Empty body. HTTP 204 indicates the artifact and all associated file versions were permanently deleted.
func (r *ArtifactResource) Delete(ctx context.Context, artifact string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/artifacts/" + url.PathEscape(artifact)})
}

// Get: Retrieve an artifact
//
// Returns the artifact identified by `artifact`. The response includes metadata
// such as name, description, version, and a signed `file_url` for downloading
// the current file version. Image artifacts also include an `image_source` object
// with display-ready metadata.
// The authenticated user must have read access to the artifact's owning team or
// organization. Returns 404 if the artifact does not exist or is not accessible
// to the caller.
//
// artifact: Artifact ID (`art_...`) of the artifact to retrieve.
//
// Returns: The requested artifact, including its current version's file metadata and signed download URL.
func (r *ArtifactResource) Get(ctx context.Context, artifact string) (*Artifact, error) {
	return fetch[*Artifact](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/artifacts/" + url.PathEscape(artifact)})
}

// Replace: Update an artifact
//
// Updates the metadata and, optionally, the file content of an existing artifact.
// This endpoint uses optimistic concurrency control: you must supply the artifact's
// current `version` number as `from_version`. If another update has incremented the
// version since you last fetched the artifact, the request returns 409.
// To replace the artifact's file, include a nested `file` object with Base64
// `data`, `filename`, and `mime_type`. Omitting `file` leaves the existing file
// unchanged. The authenticated user or developer must have write access to the
// artifact's owner.
//
// artifact: Artifact ID (`art_...`) of the artifact to update.
//
// Returns: The artifact after applying the update, reflecting the new version number and any changed metadata or file.
func (r *ArtifactResource) Replace(ctx context.Context, artifact string, input ArtifactReplaceInput) (*Artifact, error) {
	return fetch[*Artifact](r.http, ctx, requestSpec{Method: "PUT", Path: "/api/v1/artifacts/" + url.PathEscape(artifact), Body: input})
}

// Archive: Archive an artifact
//
// Soft-deletes the artifact identified by `artifact`. The artifact record is
// retained in storage but is no longer returned by the list or show endpoints.
// The authenticated user must have write access to the artifact's owning team or
// organization. Attempting to archive an artifact you do not own returns 403.
// Attempting to archive an artifact that does not exist or is already archived
// returns 404.
//
// artifact: Artifact ID (`art_...`) of the artifact to archive.
//
// Returns: Returns 204 No Content on success. The artifact is soft-deleted and no longer accessible through the API.
func (r *ArtifactResource) Archive(ctx context.Context, artifact string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/artifacts/" + url.PathEscape(artifact) + "/archive"})
}

// Content: Retrieve raw artifact file content
//
// Returns the raw binary content of the file stored for the specified artifact.
// The response `Content-Type` header reflects the artifact file's MIME type, so
// you can pipe the response body directly to disk or display it in a browser.
// By default the endpoint serves the artifact's current version. Pass the
// `version` parameter to retrieve a specific historical version. The authenticated
// user must have read access to the artifact's owning team or organization.
//
// artifact: Artifact ID (`art_...`) of the artifact whose content to retrieve.
//
// Returns: Raw binary content of the artifact file. The `Content-Type` header is set to the artifact's stored MIME type.
func (r *ArtifactResource) Content(ctx context.Context, artifact string, params ArtifactContentParams) (*RawResponse, error) {
	q := url.Values{}
	if params.Version != nil {
		q.Add("version", queryParam(*params.Version))
	}
	return r.http.requestRaw(ctx, requestSpec{Method: "GET", Path: "/api/v1/artifacts/" + url.PathEscape(artifact) + "/content", Query: q})
}
