// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d03dba72ee46

package platform

import (
	"context"
	"net/url"
)

type ActivityFeedListResponseDataItem struct {
	// Agent: The agent that produced this event. Returns an agent ID (`agi_...`) by default, or an expanded agent object when the association is loaded. `null` if no agent is associated.
	Agent *JSONValue `json:"agent,omitempty"`
	// App: ID of the application that produced this entry (`dap_...`). `null` if not scoped to an app.
	App *string `json:"app,omitempty"`
	// Attachments: Array of attachment objects associated with this entry. Each attachment has a `type` field (e.g. `"file"`, `"task"`, `"artifact"`) and type-specific additional fields. Empty array when there are no attachments.
	Attachments []map[string]JSONValue `json:"attachments,omitempty"`
	// AutomationRun: ID of the automation run that produced this entry (`atr_...`). `null` if not produced by an automation run.
	AutomationRun *string `json:"automation_run,omitempty"`
	// Content: A longer explanation of the event rendered as Markdown. `null` if no additional content is available.
	Content *string `json:"content,omitempty"`
	// CorrelationID: An opaque string used to group related entries together. Entries sharing the same `correlation_id` belong to a single logical operation. `null` if not correlated.
	CorrelationID *string `json:"correlation_id,omitempty"`
	// CreatedAt: When this activity feed entry was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// ID: Activity feed entry ID (`afe_...`).
	ID string `json:"id"`
	// Kind: The type of event this entry represents, e.g. `"agent_step"` or `"tool_call"`. Determines how `title`, `content`, and `attachments` should be interpreted.
	Kind *string `json:"kind,omitempty"`
	// Level: Severity level of the event. One of `"info"`, `"warning"`, or `"error"`. `null` if no severity is set.
	Level *string `json:"level,omitempty"`
	// Metadata: Arbitrary key-value metadata stored on this entry. Returns an empty object when no metadata is set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: ID of the organization this entry belongs to (`org_...`). `null` if not org-scoped.
	Org *string `json:"org,omitempty"`
	// RoutineRun: ID of the agent routine run that produced this entry (`arr_...`). `null` if not produced by a routine run.
	RoutineRun *string `json:"routine_run,omitempty"`
	// Sandbox: Identifier of the sandbox environment this entry was generated in. `null` in production contexts.
	Sandbox *string `json:"sandbox,omitempty"`
	// SessionRecord: ID of the agent session record this entry belongs to (`ase_...`). `null` if not part of an agent session.
	SessionRecord *string `json:"session_record,omitempty"`
	// Team: ID of the team this entry is associated with (`tem_...`). `null` if not team-scoped.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the thread this entry is associated with (`thr_...`). `null` if not linked to a thread.
	Thread *string `json:"thread,omitempty"`
	// Title: A one-line human-readable summary of the event. `null` if the entry has no title.
	Title *string `json:"title,omitempty"`
	// UpdatedAt: When this activity feed entry was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: The user who triggered this event. Returns a user ID (`usr_...`) by default, or an expanded user object when the association is loaded. `null` if no user is associated.
	User *JSONValue `json:"user,omitempty"`
}

// ActivityFeedListResponse: Successful response
type ActivityFeedListResponse struct {
	// AfterCursor: Opaque cursor to pass as `after_cursor` to retrieve the next newer page. Absent when no newer entries exist.
	AfterCursor *string `json:"after_cursor,omitempty"`
	// BeforeCursor: Opaque cursor to pass as `before_cursor` to retrieve the next older page. Absent when no older entries exist.
	BeforeCursor *string `json:"before_cursor,omitempty"`
	// Data: Array of activity feed entry objects for the current page, ordered newest first.
	Data []ActivityFeedListResponseDataItem `json:"data"`
	// HasMore: `true` when additional entries exist beyond this page in the requested direction.
	HasMore bool `json:"has_more"`
}

// ActivityFeedListParams: query parameters for ActivityFeedResource.List.
type ActivityFeedListParams struct {
	// Kind: One or more entry kinds to include. Accepted values: routine_run, automation_run, thread_story, agent_quality_verdict, generic. Omit to return all kinds.
	Kind []string
	// Level: One or more severity levels to include. Accepted values: debug, info, warn, error, audit. Omit to return all levels.
	Level []string
	// Agent: Restrict results to entries associated with these agent IDs (`agt_...`). Accepts multiple values.
	Agent []string
	// Thread: Restrict results to entries associated with these thread IDs (`thr_...`). Accepts multiple values.
	Thread []string
	// Team: Restrict results to entries associated with these team IDs (`tem_...`). Accepts multiple values.
	Team []string
	// Org: Restrict results to entries associated with these organization IDs (`org_...`). Accepts multiple values.
	Org []string
	// CorrelationID: Restrict results to entries that share this correlation group identifier. Useful for tracing a chain of related events.
	CorrelationID *string
	// Limit: Maximum number of entries to return per page. Defaults to 50; maximum is 100.
	Limit *int
	// BeforeCursor: Opaque cursor from a previous response's `before_cursor` field. Returns entries older than the cursor's position.
	BeforeCursor *string
	// AfterCursor: Opaque cursor from a previous response's `after_cursor` field. Returns entries newer than the cursor's position.
	AfterCursor *string
}

type ActivityFeedResource struct {
	http *HTTPClient
}

func newActivityFeedResource(h *HTTPClient) *ActivityFeedResource {
	return &ActivityFeedResource{
		http: h,
	}
}

// List: List activity feed entries
//
// Returns a cursor-paginated list of activity feed entries visible to the
// authenticated user. Entries are ordered from newest to oldest by default.
// Use `before_cursor` to page backward and `after_cursor` to page forward.
// Results are scoped to the caller's app. All filter params are optional and
// can be combined. Passing multiple values in an array filter returns entries
// matching any of the supplied values (OR semantics).
// Invalid `kind` or `level` values return a 400 error listing the accepted
// values rather than being silently ignored.
//
// Returns: Successful response
func (r *ActivityFeedResource) List(ctx context.Context, params ActivityFeedListParams) (*ActivityFeedListResponse, error) {
	q := url.Values{}
	for _, item := range params.Kind {
		q.Add("kind", item)
	}
	for _, item := range params.Level {
		q.Add("level", item)
	}
	for _, item := range params.Agent {
		q.Add("agent", item)
	}
	for _, item := range params.Thread {
		q.Add("thread", item)
	}
	for _, item := range params.Team {
		q.Add("team", item)
	}
	for _, item := range params.Org {
		q.Add("org", item)
	}
	if params.CorrelationID != nil {
		q.Add("correlation_id", *params.CorrelationID)
	}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.BeforeCursor != nil {
		q.Add("before_cursor", *params.BeforeCursor)
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	return fetch[*ActivityFeedListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/activity_feed", Query: q})
}
