// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 0a63d91ced1d

package platform

import (
	"context"
	"net/url"
)

type AgentHealthActionResource struct {
	http *HTTPClient
}

func newAgentHealthActionResource(h *HTTPClient) *AgentHealthActionResource {
	return &AgentHealthActionResource{
		http: h,
	}
}

// Get: Retrieve a health action
//
// Returns a single agent health action by its ID. Use this endpoint to
// fetch the current state of a specific health action for example, to
// refresh a checklist item after the user completes a setup step or after
// polling for status changes.
// The caller must be authenticated and scoped to the app that owns the
// health action. Returns 404 if the health action does not exist or is not
// accessible within the current app scope.
//
// healthAction: Health action ID (`aha_...`) to retrieve.
//
// Returns: The requested health action object.
func (r *AgentHealthActionResource) Get(ctx context.Context, healthAction string) (*AgentHealthAction, error) {
	return fetch[*AgentHealthAction](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/agent_health_actions/" + url.PathEscape(healthAction)})
}

// Verify: Verify a health action
//
// Synchronously re-runs the verifier for the specified health action and
// returns the updated health action object. Use this endpoint to power
// operator-facing "Verify" buttons that let users confirm a setup step is
// complete (for example, after setting an environment variable or
// completing an OAuth install).
// The verifier transitions the action's `status` field according to the
// following rules: a `pending` action that passes becomes `completed`; one
// that fails stays `pending`. A `completed` action that passes stays
// `completed`; one that fails becomes `degraded`. A `degraded` action that
// passes returns to `completed`; one that fails stays `degraded`. Actions
// in `skipped` status are never transitioned the call returns the
// unchanged record.
// This endpoint runs the verifier synchronously and blocks until the check
// finishes. For background or probe-driven verification sweeps, use the
// platform's internal debounced trigger instead of calling this endpoint
// in a tight loop. Returns 422 if the verifier itself encounters an
// unrecoverable error.
//
// healthAction: Health action ID (`aha_...`) to verify.
//
// Returns: The health action object with its `status` and `last_verified_at` updated to reflect the result of the verification run.
func (r *AgentHealthActionResource) Verify(ctx context.Context, healthAction string) (*AgentHealthAction, error) {
	return fetch[*AgentHealthAction](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/agent_health_actions/" + url.PathEscape(healthAction) + "/verify"})
}
