// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 1ff987a7cbdb

package platform

import (
	"context"
	"net/url"
)

// AutomationRunJournalParams: query parameters for AutomationRunResource.Journal.
type AutomationRunJournalParams struct {
	// Limit: Maximum number of entries to return. Defaults to 50; maximum is 100.
	Limit *int
	// AfterCursor: Opaque cursor from the previous response's `after_cursor` field.
	AfterCursor *string
}

type AutomationRunResource struct {
	http *HTTPClient
}

func newAutomationRunResource(h *HTTPClient) *AutomationRunResource {
	return &AutomationRunResource{
		http: h,
	}
}

// Get: Retrieve an automation run
//
// Returns a single automation run by ID.
// Public v1 path: `GET /api/v1/automation_runs/:automation_run`.
// Developer app-scoped path (legacy shape, same module):
// `GET /protected/api/v1/developer/apps/:app/automations/runs/:automation_run`.
// Any automation type is accepted (`trigger`, `scheduled`, or `invoked`).
// Resolution is viewer-scoped (AppScope + OrgScope): a run the caller cannot
// see returns 404.
//
// automationRun: Automation run ID (`arun_...`).
//
// Returns: The requested automation run.
func (r *AutomationRunResource) Get(ctx context.Context, automationRun string) (*AutomationRun, error) {
	return fetch[*AutomationRun](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/automation_runs/" + url.PathEscape(automationRun)})
}

// Journal: List an automation run journal
//
// Returns durable workflow journal entries for an automation run.
// Public v1 path: `GET /api/v1/automation_runs/:automation_run/journal`.
// Developer app-scoped path (legacy shape, same module):
// `GET /protected/api/v1/developer/apps/:app/automations/runs/:automation_run/journal`.
// Any automation type is accepted. Resolution is viewer-scoped
// (AppScope + OrgScope). An authorized run without a journal returns
// `journal: null` and an empty `data` array with HTTP 200.
//
// automationRun: Automation run ID (`atr_...`) whose journal to retrieve.
//
// Returns: Forward-paginated automation run journal entries.
func (r *AutomationRunResource) Journal(ctx context.Context, automationRun string, params AutomationRunJournalParams) (*RunJournalPage, error) {
	q := url.Values{}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	return fetch[*RunJournalPage](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/automation_runs/" + url.PathEscape(automationRun) + "/journal", Query: q})
}

// Stream: Stream automation run status
//
// Opens a Server-Sent Events connection that emits a `run_update` event whenever
// the invoked automation run's status changes, replaying the current status on
// connect and closing on a terminal status (`completed`, `failed`, `cancelled`)
// or after the max stream duration.
//
// automationRun: ID of the invoked automation run.
//
// Returns: Server-Sent Events stream
func (r *AutomationRunResource) Stream(ctx context.Context, automationRun string) (*SSEStream, error) {
	return r.http.streamSSE(ctx, requestSpec{Method: "GET", Path: "/api/v1/automation_runs/" + url.PathEscape(automationRun) + "/stream"})
}
