// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 5ce157d4fb4c

package platform

import (
	"context"
	"net/url"
)

// AutomationInvokeInput: Invoke an automation
type AutomationInvokeInput struct {
	// IdempotencyKey: Unique key to deduplicate concurrent or retried invocations. A second request with the same key returns the existing run instead of creating a new one.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Payload: Arbitrary input data passed to the automation. Validated against the automation's `input_schema` when one is configured; the request is rejected with 422 if validation fails.
	Payload map[string]JSONValue `json:"payload,omitempty"`
}

type AutomationResource struct {
	http *HTTPClient
}

func newAutomationResource(h *HTTPClient) *AutomationResource {
	return &AutomationResource{
		http: h,
	}
}

// Invoke: Invoke an automation
//
// Triggers a single run of an automation that has `type: "invoked"`. Returns
// the resulting automation run object, which you can use to poll or display
// run status.
// Both server-to-server (secret key) and user (publishable key + JWT) auth
// are supported. The automation's `invoke_auth` setting controls which auth
// modes are accepted; requests using an unsupported mode are rejected with
// 403. For server-to-server callers the run executes under the identity
// configured in the automation's `run_as_user` or `run_as_agent` fields. For
// authenticated user callers the invoking user's identity is used
// automatically.
// If you supply an `idempotency_key`, a second request with the same key
// returns the existing run rather than creating a new one.
//
// automation: Automation ID (`auto_...`) or `lookup_key` of the automation to invoke.
//
// Returns: The automation run created by this invocation.
func (r *AutomationResource) Invoke(ctx context.Context, automation string, input AutomationInvokeInput) (*AutomationRun, error) {
	return fetch[*AutomationRun](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/automations/" + url.PathEscape(automation) + "/invoke", Body: input})
}
