// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 7f5f49e20788

package platform

import "context"

// BugReportCreateInput: Submit a bug report
type BugReportCreateInput struct {
	// Client: Identifier of the submitting client. One of `"agent_network_web"`, `"cli"`, or `"developer_portal"`.
	Client string `json:"client"`
	// ClientVersion: Build SHA or package version of the client.
	ClientVersion string `json:"client_version"`
	// Context: Optional client-shaped context blob; 5 KB serialized. Stored verbatim and surfaced for triage clients commonly include url, user_agent, thread_id, message_id, etc.
	Context map[string]JSONValue `json:"context,omitempty"`
	// Description: Freeform report text. 1 10,000 chars after trim.
	Description string `json:"description"`
}

type BugReportResource struct {
	http *HTTPClient
}

func newBugReportResource(h *HTTPClient) *BugReportResource {
	return &BugReportResource{
		http: h,
	}
}

// Create: Submit a bug report
//
// Creates a bug report or freeform feedback entry on behalf of the authenticated user.
// The `description` is stored in full; the `context` blob is stored verbatim and surfaced
// during triage. Callers should include relevant session identifiers (URL, thread ID, etc.)
// in `context` to speed up reproduction.
// This endpoint requires authentication. Submissions are rate-limited to 10 reports per
// user per hour; exceeding that limit returns 429. The `client` value must be one of the
// recognised string identifiers listed below an unrecognised value returns 400.
//
// Returns: The created bug report record.
func (r *BugReportResource) Create(ctx context.Context, input BugReportCreateInput) (*BugReport, error) {
	return fetch[*BugReport](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/bug_reports", Body: input})
}
