// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: b880a3c31147

package platform

import (
	"context"
	"net/url"
)

// SystemCloneInput: Clone a system config
type SystemCloneInput struct {
	// LookupKey: Override the `lookup_key` on the cloned config. When omitted, the source value is used.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Org: Organization ID (`org_...`) to scope the clone to. When set, must match the authenticated viewer's org.
	Org *string `json:"org,omitempty"`
	// Team: Team ID (`tea_...`) that will own the cloned config. Required unless `user` is provided or the caller is app-scoped.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) that will own the cloned config. Required unless `team` is provided or the caller is app-scoped.
	User *string `json:"user,omitempty"`
	// VirtualPath: Override the `virtual_path` on the cloned config. When omitted, the source value is used.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

// ConfigCreateInput: Create a config
type ConfigCreateInput struct {
	// Agent: Agent ID (`agt_...`) to assign as the config owner. Mutually exclusive with `team`, `user`, and `system`.
	Agent *string `json:"agent,omitempty"`
	// ChangeDescription: Human-readable description of this initial version, stored on the version record.
	ChangeDescription *string `json:"change_description,omitempty"`
	// Data: Arbitrary key-value metadata stored on the version alongside the content.
	Data map[string]JSONValue `json:"data,omitempty"`
	// DataEncoding: Encoding of `raw_content`. Omit or set `"raw"` for literal content; set `"base64"` when sending binary content such as images or PDFs in JSON.
	DataEncoding *string `json:"data_encoding,omitempty"`
	// Kind: Config kind that determines the schema and behavior of the config, e.g. `"Agent"` or `"APITool"`.
	Kind string `json:"kind"`
	// LookupKey: Optional stable key for looking up this config independent of its `virtual_path`. Must be unique within the app + org scope across all owners.
	LookupKey *string `json:"lookup_key,omitempty"`
	// MimeType: MIME type of `raw_content`, e.g. `"application/x-yaml"` or `"application/json"`.
	MimeType string `json:"mime_type"`
	// Org: Organization ID (`org_...`) to scope the config to a specific org.
	Org *string `json:"org,omitempty"`
	// Parent: Parent config ID (`cfg_...`) for bundle children, e.g. files belonging to a Skill. Required together with `relative_path` when creating a child config.
	Parent *string `json:"parent,omitempty"`
	// ParentSolution: Solution config ID (`cfg_...`) that this config was imported with. Records provenance for configs that arrive as part of a solution bundle.
	ParentSolution *string `json:"parent_solution,omitempty"`
	// RawContent: Raw content bytes for the first version. Accepted formats depend on `mime_type`; typical values are YAML or JSON text.
	RawContent string `json:"raw_content"`
	// RelativePath: Path of this config within its parent bundle, e.g. `"prompts/system.md"`. Required when `parent` is set.
	RelativePath *string `json:"relative_path,omitempty"`
	// System: Set `true` to create a system-owned config (no team, user, or agent owner). Requires a developer, all-powerful, or app system-user viewer, or an org admin creating an org-scoped system config. Mutually exclusive with `team`, `user`, and `agent`.
	System *bool `json:"system,omitempty"`
	// TakeOwnership: When `true` and a config already exists at the specified `virtual_path` or `lookup_key` under a different owner, adopt that config rather than returning 409: the existing row is re-owned to the requested owner, unarchived if necessary, and this content is saved as its next version. Requires modify rights on the existing row (developer or all-powerful viewer).
	TakeOwnership *bool `json:"take_ownership,omitempty"`
	// Team: Team ID (`team_...`) to assign as the config owner. Mutually exclusive with `user`, `agent`, and `system`.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) to assign as the config owner. Mutually exclusive with `team`, `agent`, and `system`.
	User *string `json:"user,omitempty"`
	// VirtualPath: Human-readable path that uniquely identifies the config within its owner scope, e.g. `"my-agent/v1"`. Must be unique within the app + org + owner combination.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

// ConfigEncryptSecretInput: Encrypt a secret for use in a config
type ConfigEncryptSecretInput struct {
	// Org: Organization ID (`org_...`) whose KEK to use for encryption. Overrides the viewer's own org. Omit to use the viewer's org KEK, or the app-level KEK when the viewer has no org context.
	Org *string `json:"org,omitempty"`
	// Plaintext: The secret value to encrypt. Never stored; only the resulting ciphertext is returned.
	Plaintext string `json:"plaintext"`
}

// ConfigValidateInput: Validate config content
type ConfigValidateInput struct {
	// Agent: Agent ID (`agt_...`) that would own the config. Used for owner-aware validation rules. Mutually exclusive with `team` and `user`.
	Agent *string `json:"agent,omitempty"`
	// Data: Optional metadata used by kind-specific validation. File and Image configs require `data.name` when validating direct binary content.
	Data map[string]JSONValue `json:"data,omitempty"`
	// DataEncoding: Encoding of `raw_content`. Omit or set `"raw"` for literal content; set `"base64"` when sending binary content such as images or PDFs in JSON.
	DataEncoding *string `json:"data_encoding,omitempty"`
	// Kind: Config kind whose schema the content is validated against, e.g. `"Agent"` or `"APITool"`.
	Kind string `json:"kind"`
	// MimeType: MIME type of `raw_content`, e.g. `"application/x-yaml"` or `"application/json"`. Used to parse the content before validation.
	MimeType string `json:"mime_type"`
	// RawContent: Raw content bytes to validate. Parsed according to `mime_type` before schema validation.
	RawContent string `json:"raw_content"`
	// Team: Team ID (`team_...`) that would own the config. Used for owner-aware validation rules. Mutually exclusive with `user` and `agent`.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) that would own the config. Used for owner-aware validation rules. Mutually exclusive with `team` and `agent`.
	User *string `json:"user,omitempty"`
}

// ConfigUpdateInput: Update a config
type ConfigUpdateInput struct {
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string `json:"agent,omitempty"`
	// ChangeDescription: Human-readable description of this update, stored on the new version record.
	ChangeDescription *string `json:"change_description,omitempty"`
	// Data: Arbitrary key-value metadata to store on the new version alongside the content.
	Data map[string]JSONValue `json:"data,omitempty"`
	// DataEncoding: Encoding of `raw_content`. Omit or set `"raw"` for literal content; set `"base64"` when sending binary content such as images or PDFs in JSON.
	DataEncoding *string `json:"data_encoding,omitempty"`
	// ExpectedVersion: Version number the caller expects to be current. If the config's actual current version does not match, the request returns 409 to signal a concurrent modification. Omit to skip optimistic locking.
	ExpectedVersion *int `json:"expected_version,omitempty"`
	// LookupKey: New `lookup_key` for the config. Updates the key without creating a new version when `raw_content` is omitted.
	LookupKey *string `json:"lookup_key,omitempty"`
	// MimeType: MIME type of `raw_content`, e.g. `"application/x-yaml"` or `"application/json"`. Defaults to the existing MIME type when `raw_content` is provided without this field.
	MimeType *string `json:"mime_type,omitempty"`
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org.
	Org *string `json:"org,omitempty"`
	// ParentSolution: Solution config ID (`cfg_...`) to set as the config's parent solution provenance. Clears the value when set to an empty string.
	ParentSolution *string `json:"parent_solution,omitempty"`
	// RawContent: New raw content bytes for the config. When provided, a new version is created. Omit to perform a metadata-only update without incrementing the version.
	RawContent *string `json:"raw_content,omitempty"`
	// RelativePath: Updated path of this config within its parent bundle. Only meaningful when the config has a `parent`.
	RelativePath *string `json:"relative_path,omitempty"`
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool `json:"system,omitempty"`
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string `json:"user,omitempty"`
	// VirtualPath: New `virtual_path` for the config. Updates the path without creating a new version when `raw_content` is omitted.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

// ConfigArchiveInput: Archive a config
type ConfigArchiveInput struct {
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string `json:"agent,omitempty"`
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org. Useful when the viewer has access to multiple orgs.
	Org *string `json:"org,omitempty"`
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool `json:"system,omitempty"`
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string `json:"user,omitempty"`
}

// ConfigChangeOwnerInput: Transfer ownership of a config
type ConfigChangeOwnerInput struct {
	// Agent: New owner: Agent ID (`agt_...`). Mutually exclusive with `team`, `user`, and `system`.
	Agent *string `json:"agent,omitempty"`
	// Org: Only valid when `system:true`. Omit to keep the config's existing `org_id`; supply an org ID (`org_...`) to set a specific org scope; pass blank or `null` to make the config app-level (operator viewers only). Setting `org` for `team`, `user`, or `agent` targets returns 422.
	Org *string `json:"org,omitempty"`
	// System: Set `true` to transfer to system ownership (app-level or org-scoped). Requires a privileged viewer. Mutually exclusive with `team`, `user`, and `agent`.
	System *bool `json:"system,omitempty"`
	// Team: New owner: Team ID (`team_...`). Mutually exclusive with `user`, `agent`, and `system`.
	Team *string `json:"team,omitempty"`
	// User: New owner: User ID (`usr_...`). Mutually exclusive with `team`, `agent`, and `system`.
	User *string `json:"user,omitempty"`
}

// ConfigUnarchiveInput: Unarchive a config
type ConfigUnarchiveInput struct {
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string `json:"agent,omitempty"`
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org.
	Org *string `json:"org,omitempty"`
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool `json:"system,omitempty"`
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string `json:"user,omitempty"`
}

type KindListResponseDataItem struct {
	// Classification: Structural role of this kind. `"root"` kinds are standalone configs; `"supplemental"` kinds extend or augment a root config.
	Classification string `json:"classification"`
	// Description: Markdown prose describing what this config kind represents and how to use it. `null` when no description has been registered for this kind.
	Description *string `json:"description,omitempty"`
	// Kind: The config kind identifier (e.g., `"Agent"`, `"APITool"`). Used as the `kind` value when creating or filtering configs.
	Kind string `json:"kind"`
	// SampleAvailable: `true` when a sample YAML document is available for this kind via the schema endpoint.
	SampleAvailable bool `json:"sample_available"`
	// SchemaAvailable: `true` when a JSON Schema definition is available for this kind via the schema endpoint.
	SchemaAvailable bool `json:"schema_available"`
}

// KindListResponse: Successful response
type KindListResponse struct {
	// Data: Array of config kind objects, sorted alphabetically by `kind` name.
	Data []KindListResponseDataItem `json:"data"`
}

type SystemListResponseDataItemCurrentVersion struct {
	// ChangeDescription: Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied.
	ChangeDescription *string `json:"change_description,omitempty"`
	// ContentHash: SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced.
	ContentHash *string `json:"content_hash,omitempty"`
	// CreatedAt: When this config version was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Data: Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided.
	Data map[string]JSONValue `json:"data,omitempty"`
	// ID: Config version ID (`cfv_...`).
	ID string `json:"id"`
	// Org: Organization ID (`org_...`) that owns this config version. `null` for personal configs.
	Org *string `json:"org,omitempty"`
	// Sandbox: Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs.
	Sandbox *string `json:"sandbox,omitempty"`
	// SourceSolutionConfigVersion: Config version ID (`cfv_...`) for the Solution version this config version was installed from. `null` for standalone configs and legacy rows.
	SourceSolutionConfigVersion *string `json:"source_solution_config_version,omitempty"`
	// VersionNumber: Monotonically increasing integer identifying this version within the config. Starts at 1.
	VersionNumber int `json:"version_number"`
}

type SystemListResponseDataItem struct {
	// Agent: Agent ID (`agt_...`) associated with this config. `null` if not linked to an agent.
	Agent *string `json:"agent,omitempty"`
	// CreatedAt: When this config was first created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// CurrentVersion: The most recently saved version of this config. `null` if the config has never been saved with content.
	CurrentVersion *SystemListResponseDataItemCurrentVersion `json:"current_version,omitempty"`
	// ID: Config ID (`cfg_...`).
	ID string `json:"id"`
	// IsArchived: Whether this config has been archived. Archived configs are hidden from default listings but remain accessible by ID.
	IsArchived *bool `json:"is_archived,omitempty"`
	// Kind: Type of config, e.g. `"Agent"` or `"APITool"`. Determines which fields and validation rules apply.
	Kind string `json:"kind"`
	// LookupKey: Stable, user-defined key used to look up this config without knowing its ID. `null` if not set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// MimeType: MIME type of the config's content, e.g. `"text/yaml"`. `null` if not determined.
	MimeType *string `json:"mime_type,omitempty"`
	// Org: Organization ID (`org_...`) this config belongs to. `null` for configs not scoped to an org.
	Org *string `json:"org,omitempty"`
	// Parent: Parent bundle config ID (`cfg_...`). Present only for configs that are children of a bundle; `null` otherwise.
	Parent *string `json:"parent,omitempty"`
	// ParentSolution: ID (`cfg_...`) of the solution config this config was imported with. `null` if the config was not imported via a solution.
	ParentSolution *string `json:"parent_solution,omitempty"`
	// RawContent: Raw file content as a string. Populated only for system configs; `null` for user-owned configs.
	RawContent *string `json:"raw_content,omitempty"`
	// RelativePath: Path of this config relative to its parent bundle root. Present only for bundle children; `null` otherwise.
	RelativePath *string `json:"relative_path,omitempty"`
	// Sandbox: Sandbox identifier this config belongs to. `null` for production configs.
	Sandbox *string `json:"sandbox,omitempty"`
	// Team: Team ID (`tea_...`) that owns this config. `null` for personal (user-scoped) configs.
	Team *string `json:"team,omitempty"`
	// UpdatedAt: When this config was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: User ID (`usr_...`) who owns this config. `null` for team-scoped configs.
	User *string `json:"user,omitempty"`
	// VirtualPath: Logical path uniquely identifying this config within its team, e.g. `"agents/my-agent.yaml"`. `null` for configs without an explicit path.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

// SystemListResponse: Successful response
type SystemListResponse struct {
	// Data: Array of system config objects for the current page.
	Data []SystemListResponseDataItem `json:"data"`
	// HasNext: `true` when a subsequent page of results exists.
	HasNext bool `json:"has_next"`
	// HasPrev: `true` when a previous page of results exists.
	HasPrev bool `json:"has_prev"`
	// Page: The current page number (1-indexed).
	Page int `json:"page"`
	// PageSize: Number of results returned per page.
	PageSize int `json:"page_size"`
	// TotalEntries: Total number of system configs matching the applied filters across all pages.
	TotalEntries int `json:"total_entries"`
	// TotalPages: Total number of pages given the current `page_size`.
	TotalPages int `json:"total_pages"`
}

type ConfigListResponseDataItemCurrentVersion struct {
	// ChangeDescription: Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied.
	ChangeDescription *string `json:"change_description,omitempty"`
	// ContentHash: SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced.
	ContentHash *string `json:"content_hash,omitempty"`
	// CreatedAt: When this config version was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Data: Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided.
	Data map[string]JSONValue `json:"data,omitempty"`
	// ID: Config version ID (`cfv_...`).
	ID string `json:"id"`
	// Org: Organization ID (`org_...`) that owns this config version. `null` for personal configs.
	Org *string `json:"org,omitempty"`
	// Sandbox: Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs.
	Sandbox *string `json:"sandbox,omitempty"`
	// SourceSolutionConfigVersion: Config version ID (`cfv_...`) for the Solution version this config version was installed from. `null` for standalone configs and legacy rows.
	SourceSolutionConfigVersion *string `json:"source_solution_config_version,omitempty"`
	// VersionNumber: Monotonically increasing integer identifying this version within the config. Starts at 1.
	VersionNumber int `json:"version_number"`
}

type ConfigListResponseDataItem struct {
	// Agent: Agent ID (`agt_...`) associated with this config. `null` if not linked to an agent.
	Agent *string `json:"agent,omitempty"`
	// CreatedAt: When this config was first created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// CurrentVersion: The most recently saved version of this config. `null` if the config has never been saved with content.
	CurrentVersion *ConfigListResponseDataItemCurrentVersion `json:"current_version,omitempty"`
	// ID: Config ID (`cfg_...`).
	ID string `json:"id"`
	// IsArchived: Whether this config has been archived. Archived configs are hidden from default listings but remain accessible by ID.
	IsArchived *bool `json:"is_archived,omitempty"`
	// Kind: Type of config, e.g. `"Agent"` or `"APITool"`. Determines which fields and validation rules apply.
	Kind string `json:"kind"`
	// LookupKey: Stable, user-defined key used to look up this config without knowing its ID. `null` if not set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// MimeType: MIME type of the config's content, e.g. `"text/yaml"`. `null` if not determined.
	MimeType *string `json:"mime_type,omitempty"`
	// Org: Organization ID (`org_...`) this config belongs to. `null` for configs not scoped to an org.
	Org *string `json:"org,omitempty"`
	// Parent: Parent bundle config ID (`cfg_...`). Present only for configs that are children of a bundle; `null` otherwise.
	Parent *string `json:"parent,omitempty"`
	// ParentSolution: ID (`cfg_...`) of the solution config this config was imported with. `null` if the config was not imported via a solution.
	ParentSolution *string `json:"parent_solution,omitempty"`
	// RawContent: Raw file content as a string. Populated only for system configs; `null` for user-owned configs.
	RawContent *string `json:"raw_content,omitempty"`
	// RelativePath: Path of this config relative to its parent bundle root. Present only for bundle children; `null` otherwise.
	RelativePath *string `json:"relative_path,omitempty"`
	// Sandbox: Sandbox identifier this config belongs to. `null` for production configs.
	Sandbox *string `json:"sandbox,omitempty"`
	// Team: Team ID (`tea_...`) that owns this config. `null` for personal (user-scoped) configs.
	Team *string `json:"team,omitempty"`
	// UpdatedAt: When this config was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: User ID (`usr_...`) who owns this config. `null` for team-scoped configs.
	User *string `json:"user,omitempty"`
	// VirtualPath: Logical path uniquely identifying this config within its team, e.g. `"agents/my-agent.yaml"`. `null` for configs without an explicit path.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

// ConfigListResponse: Successful response
type ConfigListResponse struct {
	// Data: Array of config objects matching the query.
	Data []ConfigListResponseDataItem `json:"data"`
}

// ConfigEncryptSecretResponse: Successful response
type ConfigEncryptSecretResponse struct {
	// EncryptedValue: Encrypted ciphertext string. Embed this in config content using the `secret_value!` interpolation syntax to have it decrypted at runtime.
	EncryptedValue string `json:"encrypted_value"`
}

type ConfigVersionsResponseVersionsItem struct {
	// ChangeDescription: Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied.
	ChangeDescription *string `json:"change_description,omitempty"`
	// ContentHash: SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced.
	ContentHash *string `json:"content_hash,omitempty"`
	// CreatedAt: When this config version was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Data: Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided.
	Data map[string]JSONValue `json:"data,omitempty"`
	// ID: Config version ID (`cfv_...`).
	ID string `json:"id"`
	// Org: Organization ID (`org_...`) that owns this config version. `null` for personal configs.
	Org *string `json:"org,omitempty"`
	// Sandbox: Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs.
	Sandbox *string `json:"sandbox,omitempty"`
	// SourceSolutionConfigVersion: Config version ID (`cfv_...`) for the Solution version this config version was installed from. `null` for standalone configs and legacy rows.
	SourceSolutionConfigVersion *string `json:"source_solution_config_version,omitempty"`
	// VersionNumber: Monotonically increasing integer identifying this version within the config. Starts at 1.
	VersionNumber int `json:"version_number"`
}

// ConfigVersionsResponse: Successful response
type ConfigVersionsResponse struct {
	// Versions: Array of version objects ordered from most recent to oldest.
	Versions []ConfigVersionsResponseVersionsItem `json:"versions"`
}

// KindListParams: query parameters for KindResource.List.
type KindListParams struct {
	// Kind: One or more config kind names to include in the response (e.g., `"Agent"`, `"APITool"`). Omit to return all non-private kinds.
	Kind []string
}

// SystemListParams: query parameters for SystemResource.List.
type SystemListParams struct {
	// Kind: Filter results to a single config kind, e.g. `"Agent"` or `"APITool"`. Use `kinds` to filter by multiple kinds at once.
	Kind *string
	// Kinds: Filter results to configs whose `kind` is in this list. When both `kind` and `kinds` are provided, `kinds` takes precedence.
	Kinds []string
	// ExcludedPathPrefixes: Exclude configs whose `virtual_path` starts with any of the listed string prefixes.
	ExcludedPathPrefixes []string
	// Page: Page number to retrieve, 1-indexed. Defaults to `1`.
	Page *int
	// PageSize: Number of results per page. Defaults to `50`; maximum is `200`. Values above the maximum are clamped to `200`.
	PageSize *int
}

// ConfigListParams: query parameters for ConfigResource.List.
type ConfigListParams struct {
	// Team: Team ID (`team_...`) whose configs to list. Mutually exclusive with `user` and `agent`.
	Team *string
	// User: User ID (`usr_...`) whose configs to list. Defaults to the current user when the viewer is a user and no owner selector is provided. Mutually exclusive with `team` and `agent`.
	User *string
	// Agent: Agent ID (`agt_...`) whose configs to list. Mutually exclusive with `team` and `user`.
	Agent *string
	// Kind: Filter results to configs of this kind, e.g. `"Agent"` or `"APITool"`. Omit to return configs of all non-private kinds.
	Kind *string
	// LookupKey: Filter to the config with exactly this `lookup_key`. Returns at most one result.
	LookupKey *string
	// PathPrefix: Filter to configs whose `virtual_path` starts with this prefix, e.g. `"my-agent/"`. Useful for listing files within a folder.
	PathPrefix *string
	// Parents: Filter to configs that are children of any of the listed parent config IDs (`cfg_...`). Pass a single ID to retrieve all children of one bundle.
	Parents []string
	// ParentSolutions: Filter to configs that were imported as part of any of the listed solution config IDs (`cfg_...`). Useful for identifying all files that arrived with a given solution.
	ParentSolutions []string
}

// ConfigFacetsParams: query parameters for ConfigResource.Facets.
type ConfigFacetsParams struct {
	// App: App ID (`app_...`). Present when mounted under the developer scope; injected automatically.
	App *string
	// Team: Team ID (`team_...`) to scope facets to that team's configs. Mutually exclusive with `user`.
	Team *string
	// User: User ID (`usr_...`) to scope facets to that user's configs. Defaults to the current user when the viewer is a user and no selector is provided. Mutually exclusive with `team`.
	User *string
	// Org: Organization ID (`org_...`) to narrow facets to configs belonging to that org.
	Org *string
}

// ConfigGetParams: query parameters for ConfigResource.Get.
type ConfigGetParams struct {
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org.
	Org *string
}

// ConfigContentParams: query parameters for ConfigResource.Content.
type ConfigContentParams struct {
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org.
	Org *string
	// Format: Output format for content conversion. One of `"yaml"` or `"json"`. Omit to return the content in its stored format. Returns 400 if conversion is not possible.
	Format *string
	// InjectProtectedFields: Whether to inject platform-managed protected fields (such as `virtual_path`) into the returned content. Defaults to `true`. Set to `false` to receive the raw stored bytes.
	InjectProtectedFields *bool
}

// ConfigVersionsParams: query parameters for ConfigResource.Versions.
type ConfigVersionsParams struct {
	// Team: Team ID (`team_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Team *string
	// User: User ID (`usr_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	User *string
	// Agent: Agent ID (`agt_...`) to use as the owner when resolving by `virtual_path` or `lookup_key`.
	Agent *string
	// System: Set `true` to resolve a system-owned config by `virtual_path` or `lookup_key`. Requires a privileged viewer (developer or all-powerful) or an org admin.
	System *bool
	// Org: Organization ID (`org_...`) to narrow the lookup to configs belonging to that org.
	Org *string
}

type KindResource struct {
	http *HTTPClient
}

func newKindResource(h *HTTPClient) *KindResource {
	return &KindResource{
		http: h,
	}
}

// List: List config kinds
//
// Returns all config kinds registered in the platform, sorted alphabetically by name.
// Each entry describes a type of configuration object (e.g., `"Agent"`, `"APITool"`) and
// indicates whether a JSON schema and a YAML sample are available for it.
// Any authenticated user may call this endpoint; no ownership scope is required.
// Pass one or more `kind` values to restrict the response to those specific kinds.
// Omit the parameter to receive the full list of non-private kinds.
//
// Returns: Successful response
func (r *KindResource) List(ctx context.Context, params KindListParams) (*KindListResponse, error) {
	q := url.Values{}
	for _, item := range params.Kind {
		q.Add("kind", item)
	}
	return fetch[*KindListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/kinds", Query: q})
}

// Schema: Retrieve a config kind schema
//
// Returns the JSON schema and a YAML sample for a single config kind. Use this to
// understand the structure a config object of that kind must follow before creating
// or validating one.
// The `json_schema` field is `null` when the kind has no machine-readable schema
// defined. The `sample_yaml` field is `null` when no sample is available. Any
// authenticated user may call this endpoint; no ownership scope is required.
// Returns 404 if the kind name does not match a registered, non-private config kind.
//
// kind: Name of the config kind to retrieve (e.g., `"Agent"`, `"APITool"`). Must match a registered, non-private kind exactly.
//
// Returns: The JSON schema and YAML sample for the requested config kind.
func (r *KindResource) Schema(ctx context.Context, kind string) (*ConfigKindSchema, error) {
	return fetch[*ConfigKindSchema](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/kinds/" + url.PathEscape(kind) + "/schema"})
}

type SystemResource struct {
	http *HTTPClient
}

func newSystemResource(h *HTTPClient) *SystemResource {
	return &SystemResource{
		http: h,
	}
}

// List: List system configs
//
// Returns a paginated list of system (template) configs from the filesystem-backed
// manifest. Results are always ordered by `virtual_path` ascending.
// Filter by one or more config kinds using `kind` (single value) or `kinds` (array).
// Both filters may be supplied together for backward compatibility; `kinds` takes
// precedence when both are present. Exclude specific path namespaces with
// `excluded_path_prefixes`.
// Use `page` and `page_size` to paginate. Page size is clamped to a maximum of 200;
// requests exceeding this limit are silently clamped rather than rejected.
//
// Returns: Successful response
func (r *SystemResource) List(ctx context.Context, params SystemListParams) (*SystemListResponse, error) {
	q := url.Values{}
	if params.Kind != nil {
		q.Add("kind", *params.Kind)
	}
	for _, item := range params.Kinds {
		q.Add("kinds", item)
	}
	for _, item := range params.ExcludedPathPrefixes {
		q.Add("excluded_path_prefixes", item)
	}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	return fetch[*SystemListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/system", Query: q})
}

// Facets: Retrieve system config facets
//
// Returns the distinct `kind` values and leading `virtual_path` prefixes present
// in the system (template) config manifest, each accompanied by a count of matching
// configs. Use this data to populate filter UIs or to determine which config kinds
// are available before listing or cloning.
// The response reflects the filesystem-backed template manifest and does not include
// user- or team-owned configs.
//
// Returns: Aggregated facet data containing distinct config kinds and path prefixes, each with a count of matching system configs.
func (r *SystemResource) Facets(ctx context.Context) (*ConfigFacets, error) {
	return fetch[*ConfigFacets](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/system/facets"})
}

// Get: Retrieve a system config
//
// Returns a single system (template) config identified by its `virtual_path` or
// `lookup_key`. The `system` parameter value is URL-decoded before lookup, so
// path segments with special characters may be passed URL-encoded.
// System configs are filesystem-backed templates and are readable by any
// authenticated caller regardless of team or user ownership. Returns 404 when no
// system config matches the given identifier.
//
// system: Identifier of the system config to retrieve either its `virtual_path` or its `lookup_key`. May be URL-encoded.
//
// Returns: The requested system config, including its current version and all metadata fields.
func (r *SystemResource) Get(ctx context.Context, system string) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/system/" + url.PathEscape(system)})
}

// Clone: Clone a system config
//
// Creates a copy of a system (template) config and transfers ownership to a team
// or user. All dependencies bundled with the source config are cloned alongside it.
// Responds with HTTP 201 and the newly created config on success.
// You must specify exactly one destination owner via `team` or `user`. Callers
// authenticated as an app (developer portal) may omit the owner the clone is
// then scoped to the system owner automatically.
// Use `virtual_path` and `lookup_key` to override the corresponding fields on the
// clone; omitting them carries the values from the source.
//
// system: Identifier of the source system config either its `virtual_path` or its `lookup_key`.
//
// Returns: The newly created config, including all cloned fields and its assigned ID.
func (r *SystemResource) Clone(ctx context.Context, system string, input SystemCloneInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/system/" + url.PathEscape(system) + "/clone", Body: input})
}

type ConfigResource struct {
	http   *HTTPClient
	Kinds  *KindResource
	System *SystemResource
}

func newConfigResource(h *HTTPClient) *ConfigResource {
	return &ConfigResource{
		http:   h,
		Kinds:  newKindResource(h),
		System: newSystemResource(h),
	}
}

// List: List configs
//
// Returns all configs owned by the specified owner. Exactly one owner selector
// (`team`, `user`, or `agent`) must be provided. Passing an unknown or
// inaccessible owner returns an empty `data` array rather than an error, to
// avoid leaking information about which teams, users, or agents exist.
// Use the `kind`, `lookup_key`, `path_prefix`, `parents`, and
// `parent_solutions` params to narrow results. Private config kinds are always
// excluded from the response regardless of the viewer's permissions.
// Results are not paginated; all matching configs are returned in a single
// response.
//
// Returns: Successful response
func (r *ConfigResource) List(ctx context.Context, params ConfigListParams) (*ConfigListResponse, error) {
	q := url.Values{}
	if params.Team != nil {
		q.Add("team", *params.Team)
	}
	if params.User != nil {
		q.Add("user", *params.User)
	}
	if params.Agent != nil {
		q.Add("agent", *params.Agent)
	}
	if params.Kind != nil {
		q.Add("kind", *params.Kind)
	}
	if params.LookupKey != nil {
		q.Add("lookup_key", *params.LookupKey)
	}
	if params.PathPrefix != nil {
		q.Add("path_prefix", *params.PathPrefix)
	}
	for _, item := range params.Parents {
		q.Add("parents", item)
	}
	for _, item := range params.ParentSolutions {
		q.Add("parent_solutions", item)
	}
	return fetch[*ConfigListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config", Query: q})
}

// Create: Create a config
//
// Creates a new config and its first version. Returns 201 on success.
// A config is uniquely identified within an app + org scope by its
// `virtual_path` or `lookup_key`. Creating a config at a path that already
// exists (including archived configs) returns 409. To adopt an existing config
// at that path and re-own it instead, pass `take_ownership: true` this
// requires modify rights on the existing row (developer or all-powerful viewer).
// The owner is resolved from the explicit selector params (`team`, `user`,
// `agent`, or `system`). Developer and all-powerful viewers default to system
// ownership when no explicit selector is provided. Exactly one owner selector
// may be set; conflicting selectors return 422.
// Requires app scope.
//
// Returns: The newly created config, including its first version.
func (r *ConfigResource) Create(ctx context.Context, input ConfigCreateInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config", Body: input})
}

// EncryptSecret: Encrypt a secret for use in a config
//
// Encrypts a plaintext secret and returns a ciphertext string safe for
// embedding directly in config content using the `secret_value!` interpolation
// syntax. The ciphertext is bound to the app's (or org's) key-encryption key
// (KEK) so it can only be decrypted at runtime within the same scope.
// When `org` is provided, the KEK for that org is used; otherwise the
// viewer's own org KEK is used, falling back to the app-level KEK for viewers
// with no org context.
// The plaintext is never stored. Requires app scope.
//
// Returns: Successful response
func (r *ConfigResource) EncryptSecret(ctx context.Context, input ConfigEncryptSecretInput) (*ConfigEncryptSecretResponse, error) {
	return fetch[*ConfigEncryptSecretResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/encrypt_secret", Body: input})
}

// Facets: List config facets
//
// Returns the distinct config kinds and leading `virtual_path` prefixes
// available to the viewer, each with a count of matching configs. Use this
// to populate filter UI dropdowns without making a full list request.
// The counts reflect every config the viewer can see in the requested scope,
// independent of any kind, path-prefix, or lookup-key filters that might be
// applied on a concurrent list request. This means the UI always shows every
// option the viewer could pick, not just the values on the current filtered page.
// Scoping follows the same rules as the list endpoint: developer and
// all-powerful viewers see facets across all owners in the app; org-scoped
// viewers receive their own configs' facets merged with system-owned facets;
// all other viewers see only their resolved owner's configs.
//
// Returns: Distinct config kinds and `virtual_path` prefixes with per-value counts.
func (r *ConfigResource) Facets(ctx context.Context, params ConfigFacetsParams) (*ConfigFacets, error) {
	q := url.Values{}
	if params.App != nil {
		q.Add("app", *params.App)
	}
	if params.Team != nil {
		q.Add("team", *params.Team)
	}
	if params.User != nil {
		q.Add("user", *params.User)
	}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	return fetch[*ConfigFacets](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/facets", Query: q})
}

// Validate: Validate config content
//
// Validates raw config content against the schema for a given config kind
// without saving anything. Returns a structured result indicating whether the
// content is valid and, if not, a list of error messages.
// Use this endpoint to give users early feedback before calling create or
// update. The owner context is used for any kind-specific validation rules that
// are owner-aware; provide the same owner you intend to use on the write call.
// Requires app scope.
//
// Returns: Validation outcome. Always HTTP 200; check the `valid` field to determine success. Includes `errors` when `valid` is `false`.
func (r *ConfigResource) Validate(ctx context.Context, input ConfigValidateInput) (*ValidationResult, error) {
	return fetch[*ValidationResult](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/validate", Body: input})
}

// Delete: Delete a config
//
// Permanently deletes a config and all its associated versions. This action is
// irreversible. To soft-delete a config while retaining its history, use the
// archive endpoint instead.
// The config may be addressed by its ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, you must
// supply exactly one owner selector (`team`, `user`, `agent`, or `system`);
// passing an owner selector when addressing by ID returns 422.
// Returns 204 No Content on success. Requires app scope. The viewer must have
// modify rights on the config.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: Empty body. HTTP 204 indicates the config and all its versions were permanently deleted.
func (r *ConfigResource) Delete(ctx context.Context, config string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/config/" + url.PathEscape(config)})
}

// Get: Retrieve a config
//
// Returns a single config identified by its ID, `virtual_path`, or
// `lookup_key`. The config object includes its current version metadata but
// not the raw content bytes; use the content endpoint to fetch the raw content.
// When addressing by `lookup_key` or `virtual_path`, you must supply exactly
// one owner selector (`team`, `user`, `agent`, or `system`). Passing an owner
// selector when addressing by ID (`cfg_...`) returns 422. Both `not_found`
// and `forbidden` outcomes are surfaced as 404 to avoid leaking config
// existence.
// Requires app scope.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: The requested config object.
func (r *ConfigResource) Get(ctx context.Context, config string, params ConfigGetParams) (*Config, error) {
	q := url.Values{}
	if params.Team != nil {
		q.Add("team", *params.Team)
	}
	if params.User != nil {
		q.Add("user", *params.User)
	}
	if params.Agent != nil {
		q.Add("agent", *params.Agent)
	}
	if params.System != nil {
		q.Add("system", queryParam(*params.System))
	}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	return fetch[*Config](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/" + url.PathEscape(config), Query: q})
}

// Update: Update a config
//
// Updates an existing config. When `raw_content` is provided, a new version is
// created and becomes the current version. When `raw_content` is omitted, only
// metadata fields (`virtual_path`, `lookup_key`, `relative_path`,
// `parent_solution`) are updated without creating a new version.
// Use `expected_version` for optimistic concurrency control: if the config's
// current version number does not match the supplied value the request returns
// 409. This prevents overwriting concurrent edits.
// The config may be addressed by its ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, you must
// supply exactly one owner selector (`team`, `user`, `agent`, or `system`).
// Both `not_found` and `forbidden` outcomes are surfaced as 404.
// Requires app scope. The viewer must have modify rights on the config.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: The config reflecting the applied update.
func (r *ConfigResource) Update(ctx context.Context, config string, input ConfigUpdateInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "PATCH", Path: "/api/v1/config/" + url.PathEscape(config), Body: input})
}

// Archive: Archive a config
//
// Soft-deletes a config by marking it as archived. Archived configs are hidden
// from list and show endpoints but are not permanently removed; use the
// unarchive endpoint to restore one, or the delete endpoint for permanent
// removal.
// The config may be addressed by its ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, you must
// supply exactly one owner selector (`team`, `user`, `agent`, or `system`);
// passing an owner selector when addressing by ID returns 422.
// Requires app scope. The viewer must have modify rights on the config.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. `virtual_path` values should be URL-encoded if they contain slashes.
//
// Returns: The config in its newly archived state.
func (r *ConfigResource) Archive(ctx context.Context, config string, input ConfigArchiveInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/" + url.PathEscape(config) + "/archive", Body: input})
}

// ChangeOwner: Transfer ownership of a config
//
// Transfers a config to a new owner (`team`, `user`, `agent`, or `system`).
// Exactly one of the new-owner selectors must be provided. The config must be
// addressed by its ID (`cfg_...` or UUID); `virtual_path` and `lookup_key`
// are not accepted to avoid ambiguity look up the ID first if needed.
// For non-system targets the new owner's org is derived automatically from the
// target entity; supplying `org` in that case returns 422. For `system:true`
// targets, `org` controls the resulting org scope: omit to keep the existing
// `org_id`, supply a value to set a specific org, or pass `null`/blank to make
// the config app-level (operator viewers only).
// Operator viewers (developer credentials or all-powerful viewers) may transfer
// to any owner. All other viewers are restricted to owners they can themselves
// access (team membership, user identity, agent scope, or `system` with the
// appropriate privilege).
// Requires app scope. The viewer must have modify rights on the config.
//
// config: Config ID in id-form: `cfg_...` or a UUID. `lookup_key` and `virtual_path` are not accepted retrieve the config ID first if you only have a path.
//
// Returns: The config reflecting its new ownership.
func (r *ConfigResource) ChangeOwner(ctx context.Context, config string, input ConfigChangeOwnerInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/" + url.PathEscape(config) + "/change_owner", Body: input})
}

// Content: Retrieve a config's raw content
//
// Returns the raw byte content of a config's current version. The response
// `Content-Type` header reflects the config's stored MIME type unless a
// `format` conversion is requested.
// Pass `format: "yaml"` or `format: "json"` to convert between YAML and JSON
// on the fly. Conversion is only supported between these two formats; requesting
// a conversion that is not possible returns 400.
// By default, `virtual_path` and other platform-injected protected fields are
// embedded in the returned content. Set `inject_protected_fields: false` to
// return the stored raw bytes exactly as written.
// The config may be addressed by ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, exactly one
// owner selector (`team`, `user`, `agent`, or `system`) is required.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: Raw config content in the stored or requested format.
func (r *ConfigResource) Content(ctx context.Context, config string, params ConfigContentParams) (*RawResponse, error) {
	q := url.Values{}
	if params.Team != nil {
		q.Add("team", *params.Team)
	}
	if params.User != nil {
		q.Add("user", *params.User)
	}
	if params.Agent != nil {
		q.Add("agent", *params.Agent)
	}
	if params.System != nil {
		q.Add("system", queryParam(*params.System))
	}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	if params.Format != nil {
		q.Add("format", *params.Format)
	}
	if params.InjectProtectedFields != nil {
		q.Add("inject_protected_fields", queryParam(*params.InjectProtectedFields))
	}
	return r.http.requestRaw(ctx, requestSpec{Method: "GET", Path: "/api/v1/config/" + url.PathEscape(config) + "/content", Query: q})
}

// Unarchive: Unarchive a config
//
// Restores a previously archived config, making it visible again in list and
// show responses. The config's content and version history are unchanged.
// The config may be addressed by its ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, you must
// supply exactly one owner selector (`team`, `user`, `agent`, or `system`);
// passing an owner selector when addressing by ID returns 422.
// Requires app scope. The viewer must have modify rights on the config.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: The config in its newly restored (active) state.
func (r *ConfigResource) Unarchive(ctx context.Context, config string, input ConfigUnarchiveInput) (*Config, error) {
	return fetch[*Config](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/config/" + url.PathEscape(config) + "/unarchive", Body: input})
}

// Versions: List a config's version history
//
// Returns all versions of a config in the order they were created, most recent
// first. Each version includes its version number, content metadata, and change
// description. The raw content bytes for a specific version are not included;
// use the content endpoint to fetch them.
// The config may be addressed by its ID (`cfg_...`), `virtual_path`, or
// `lookup_key`. When addressing by `lookup_key` or `virtual_path`, you must
// supply exactly one owner selector (`team`, `user`, `agent`, or `system`).
// Both `not_found` and `forbidden` outcomes are surfaced as 404.
// Requires app scope.
//
// config: Config identifier. Accepts a config ID (`cfg_...`), a `virtual_path`, or a `lookup_key`. URL-encode `virtual_path` values that contain slashes.
//
// Returns: Successful response
func (r *ConfigResource) Versions(ctx context.Context, config string, params ConfigVersionsParams) (*ConfigVersionsResponse, error) {
	q := url.Values{}
	if params.Team != nil {
		q.Add("team", *params.Team)
	}
	if params.User != nil {
		q.Add("user", *params.User)
	}
	if params.Agent != nil {
		q.Add("agent", *params.Agent)
	}
	if params.System != nil {
		q.Add("system", queryParam(*params.System))
	}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	return fetch[*ConfigVersionsResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/config/" + url.PathEscape(config) + "/versions", Query: q})
}
