// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 80ba7e69c2d7

package platform

import (
	"context"
	"net/url"
)

// ExternalObjectCreateInput: Provision an external object through an integration service
type ExternalObjectCreateInput struct {
	// Agent: Owning agent ID (`agt_...`). Supply exactly one owner field.
	Agent *string `json:"agent,omitempty"`
	// Object: Provisioning fields selected by external object type.
	Object JSONValue `json:"object"`
	// Org: Owning organization ID (`org_...`). Supply exactly one owner field.
	Org     *string `json:"org,omitempty"`
	Service string  `json:"service"`
	// Team: Owning team ID (`tem_...`). Supply exactly one owner field.
	Team *string `json:"team,omitempty"`
	// User: Owning user ID (`usr_...`). Supply exactly one owner field.
	User *string `json:"user,omitempty"`
}

// ExternalObjectUpdateInput: Update an external object
type ExternalObjectUpdateInput struct {
	// Object: Mutable fields selected by external object type.
	Object JSONValue `json:"object"`
}

type ExternalObjectListResponseDataItem struct {
	Agent     *string `json:"agent,omitempty"`
	CreatedAt Time    `json:"created_at"`
	// ID: ArchAstro external object ID (`ext_...`).
	ID string `json:"id"`
	// Integration: Integration ID (`int_...`).
	Integration string `json:"integration"`
	// Object: Service-specific object payload.
	Object    JSONValue `json:"object"`
	Org       *string   `json:"org,omitempty"`
	Service   string    `json:"service"`
	Team      *string   `json:"team,omitempty"`
	UpdatedAt Time      `json:"updated_at"`
	User      *string   `json:"user,omitempty"`
}

// ExternalObjectListResponse: Successful response
type ExternalObjectListResponse struct {
	Data         []ExternalObjectListResponseDataItem `json:"data"`
	HasNext      bool                                 `json:"has_next"`
	HasPrev      bool                                 `json:"has_prev"`
	Page         int                                  `json:"page"`
	PageSize     int                                  `json:"page_size"`
	TotalEntries int                                  `json:"total_entries"`
	TotalPages   int                                  `json:"total_pages"`
}

// ExternalObjectListParams: query parameters for ExternalObjectResource.List.
type ExternalObjectListParams struct {
	Service  *string
	Type     *string
	Page     *int
	PageSize *int
	Search   *string
}

type ExternalObjectResource struct {
	http *HTTPClient
}

func newExternalObjectResource(h *HTTPClient) *ExternalObjectResource {
	return &ExternalObjectResource{
		http: h,
	}
}

// List: List external objects
//
// Returns: Successful response
func (r *ExternalObjectResource) List(ctx context.Context, params ExternalObjectListParams) (*ExternalObjectListResponse, error) {
	q := url.Values{}
	if params.Service != nil {
		q.Add("service", *params.Service)
	}
	if params.Type != nil {
		q.Add("type", *params.Type)
	}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	if params.Search != nil {
		q.Add("search", *params.Search)
	}
	return fetch[*ExternalObjectListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/external_objects", Query: q})
}

// Create: Provision an external object through an integration service
//
// Returns: Successful response
func (r *ExternalObjectResource) Create(ctx context.Context, input ExternalObjectCreateInput) (*ExternalObject, error) {
	return fetch[*ExternalObject](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/external_objects", Body: input})
}

// Delete: Delete an external object
//
// Returns: No content
func (r *ExternalObjectResource) Delete(ctx context.Context, externalObject string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/external_objects/" + url.PathEscape(externalObject)})
}

// Get: Show an external object
//
// Returns: Successful response
func (r *ExternalObjectResource) Get(ctx context.Context, externalObject string) (*ExternalObject, error) {
	return fetch[*ExternalObject](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/external_objects/" + url.PathEscape(externalObject)})
}

// Update: Update an external object
//
// Returns: Successful response
func (r *ExternalObjectResource) Update(ctx context.Context, externalObject string, input ExternalObjectUpdateInput) (*ExternalObject, error) {
	return fetch[*ExternalObject](r.http, ctx, requestSpec{Method: "PATCH", Path: "/api/v1/external_objects/" + url.PathEscape(externalObject), Body: input})
}
