// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 3bee4cd04989

package platform

import (
	"context"
	"net/url"
)

// ExtractionCreateInput: Start an extraction
type ExtractionCreateInput struct {
	// Agent: Owning agent (`agt_...`) scopes the extraction and its outputs.
	Agent *string `json:"agent,omitempty"`
	// DestinationKind: Where outputs are written.
	DestinationKind string `json:"destination_kind"`
	// DestinationPath: Destination virtual_path prefix. Required for `destination_kind=config`, where it must name at least one path segment (`.` and `..` segments are dropped).
	DestinationPath *string `json:"destination_path,omitempty"`
	// File: Source file id (`fil_...`) for document extraction. Runs synchronously, so the source must be at most 10MB; larger files are rejected.
	File *string `json:"file,omitempty"`
	// MaxPages: Crawl cap for `mode=site` must be at least 1 (defaults to 100; `link` is always 1).
	MaxPages *int `json:"max_pages,omitempty"`
	// Mode: Required with `url`. Document extraction is selected by `file` instead and takes no `mode` (its `kind` is `document`).
	Mode *string `json:"mode,omitempty"`
	// Org: Owning organization (`org_...`). Defaults to the viewer's org.
	Org *string `json:"org,omitempty"`
	// URL: Source URL for link/site extraction.
	URL *string `json:"url,omitempty"`
}

type ExtractionResource struct {
	http *HTTPClient
}

func newExtractionResource(h *HTTPClient) *ExtractionResource {
	return &ExtractionResource{
		http: h,
	}
}

// Create: Start an extraction
//
// Records a text-extraction job for a document (`file`) or a URL (`url` + `mode`).
// The job is owner-scoped and tagged with the caller-supplied `destination`
// namespace, **without** committing knowledge to an agent (no embeddings, no
// agent attach).
// Exactly one of `file` or (`url` + `mode`) is required.
// Document extraction (`file`) runs synchronously: the response already
// reflects the final state (`done` with its output, or an error if extraction
// couldn't complete), status `201`. URL extraction (`url` + `mode`) submits an
// async crawl and returns immediately with state `running`, status `202`
// poll `GET /extractions/:extraction` for its terminal state.
//
// Returns: The extraction job. Document extraction returns `201` with `state: "done"`; link/site extraction returns `202` with `state: "running"`.
func (r *ExtractionResource) Create(ctx context.Context, input ExtractionCreateInput) (*Extraction, error) {
	return fetch[*Extraction](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/extractions", Body: input})
}

// Get: Retrieve an extraction
//
// Returns a single extraction job and its current state. Poll this endpoint after
// starting an async (link/site) extraction until `state` is `done` or `failed`.
// An extraction that exists but is not visible to the current viewer returns `404`
// rather than `403`, so the resource's existence is not revealed.
//
// extraction: Extraction ID (`ext_...`).
//
// Returns: The extraction job.
func (r *ExtractionResource) Get(ctx context.Context, extraction string) (*Extraction, error) {
	return fetch[*Extraction](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/extractions/" + url.PathEscape(extraction)})
}
