// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a01f9b09c780

package platform

import (
	"context"
	"net/url"
)

// FileCreateInput: Upload a file
type FileCreateInput struct {
	// Agent: Agent ID (`agi_...`) to associate with this file. When provided, the file's organization is derived from the agent.
	Agent *string `json:"agent,omitempty"`
	// ContentType: MIME type of the file, e.g. `"image/png"` or `"application/pdf"`.
	ContentType string `json:"content_type"`
	// Data: Base64-encoded binary content of the file to upload.
	Data string `json:"data"`
	// Filename: Original filename including extension, e.g. `"avatar.png"`.
	Filename string `json:"filename"`
	// Org: Organization ID (`org_...`) to associate with this file. Optional; defaults to the viewer's organization when omitted.
	Org *string `json:"org,omitempty"`
	// Team: Team ID (`tem_...`) that owns this file. Takes precedence over `user` when both are provided.
	Team *string `json:"team,omitempty"`
	// User: User ID (`usr_...`) that owns this file. Defaults to the authenticated user when neither `user` nor `team` is specified.
	User *string `json:"user,omitempty"`
}

// FileAvatarParams: query parameters for FileResource.Avatar.
type FileAvatarParams struct {
	// Token: HMAC capability token authorizing access to this specific file. Obtained from the avatar URL minted when the profile picture was set.
	Token string
}

type FileResource struct {
	http *HTTPClient
}

func newFileResource(h *HTTPClient) *FileResource {
	return &FileResource{
		http: h,
	}
}

// Create: Upload a file
//
// Creates a new file from base64-encoded content and returns the resulting file object,
// including a signed download URL. Use this endpoint to store images, documents, or
// other binary assets that can then be referenced by agents, teams, or users.
// App scope is derived from the authenticated viewer's bearer token or publishable key.
// You may optionally associate the file with an organization, team, user, or agent by
// passing the corresponding ID. If no owner is specified and the viewer is a user, the
// file is automatically attributed to that user.
// Returns `422` when the `data` field is not valid base64 or the changeset is invalid.
// Returns `403` when the request lacks the required app scope.
//
// Returns: The newly created file, including a signed download URL.
func (r *FileResource) Create(ctx context.Context, input FileCreateInput) (*StorageFile, error) {
	return fetch[*StorageFile](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/files", Body: input})
}

// Avatar: Fetch an agent avatar image
//
// Returns the raw image bytes for an agent's profile picture identified by `file`.
// This endpoint is designed for integration partners (such as Slack) that fetch
// avatar URLs via plain GET requests without bearer token support. Authorization
// is performed via a short, stable capability `token` rather than an HTTP header.
// The `token` is an HMAC-based capability tied to the file ID. It does not expire,
// but it is invalidated when the agent's profile picture is replaced or the agent is
// deleted shared caches may continue serving the old image until the
// `Cache-Control` max-age of one hour elapses. The endpoint never redirects to
// a signed storage URL; bytes are served inline so behavior is consistent across
// storage backends.
// All failure modes invalid file ID, invalid token, file not currently referenced
// as an agent avatar return a uniform `404` to avoid acting as an existence oracle.
//
// file: File ID of the agent's profile picture (`fil_...`). Must be currently set as an agent's profile picture within the same app.
//
// Returns: Raw image bytes of the agent avatar, served with the file's original content type.
func (r *FileResource) Avatar(ctx context.Context, file string, params FileAvatarParams) (*RawResponse, error) {
	q := url.Values{}
	q.Add("token", params.Token)
	return r.http.requestRaw(ctx, requestSpec{Method: "GET", Path: "/api/v1/files/" + url.PathEscape(file) + "/avatar", Query: q})
}
