// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 37d5bb0ab1d9

package platform

import (
	"context"
	"net/url"
)

type InstallationSourceResource struct {
	http *HTTPClient
}

func newInstallationSourceResource(h *HTTPClient) *InstallationSourceResource {
	return &InstallationSourceResource{
		http: h,
	}
}

// Delete: Remove a source from an installation
//
// Detaches and permanently deletes a source from an installation. This action
// cannot be undone; the source and its associated content will no longer be
// available to the installation's agent.
// This endpoint requires an app-scoped token. You may identify the target
// indirectly by providing only the `source` ID the installation is resolved
// automatically from the source record. Providing `installation` explicitly
// is also accepted and may be more efficient.
//
// source: Source ID (`cso_...`) of the source to remove.
//
// Returns: No content
func (r *InstallationSourceResource) Delete(ctx context.Context, source string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/installation_sources/" + url.PathEscape(source)})
}
