// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 57e9565221d4

package platform

import (
	"context"
	"net/url"
)

type KnowledgeDocumentListResponseDataItem struct {
	// Agent: ID of the agent that owns this document (`agi_...`). `null` if owned by a user or team.
	Agent *string `json:"agent,omitempty"`
	// CreatedAt: When the document was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// File: ID of the backing storage file (`fil_...`) when the document is file-backed. `null` for inline documents.
	File *string `json:"file,omitempty"`
	// ID: Context document ID (`cdo_...`).
	ID string `json:"id"`
	// Metadata: Arbitrary key-value metadata attached to the document. Shape varies by source type.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Source: ID of the context source this document belongs to (`cso_...`).
	Source *string `json:"source,omitempty"`
	// Team: ID of the team that owns this document (`tem_...`). `null` if owned by a user or agent.
	Team *string `json:"team,omitempty"`
	// Title: Human-readable display title of the document. `null` if no title has been set.
	Title *string `json:"title,omitempty"`
	// TotalLines: Total number of lines in the document's text content. `0` if the document has no content.
	TotalLines *int `json:"total_lines,omitempty"`
	// TotalSize: Total byte size of the document's text content. `0` if the document has no content.
	TotalSize *int `json:"total_size,omitempty"`
	// UpdatedAt: When the document was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user that owns this document (`usr_...`). `null` if owned by a team or agent.
	User *string `json:"user,omitempty"`
}

// KnowledgeDocumentListResponse: Successful response
type KnowledgeDocumentListResponse struct {
	// Data: Array of context document objects for the current page.
	Data []KnowledgeDocumentListResponseDataItem `json:"data"`
	// HasNext: `true` if a subsequent page exists; `false` when this is the last page.
	HasNext bool `json:"has_next"`
	// HasPrev: `true` if a previous page exists; `false` when this is the first page.
	HasPrev bool `json:"has_prev"`
	// Page: The current page number.
	Page int `json:"page"`
	// PageSize: Maximum number of documents returned per page.
	PageSize int `json:"page_size"`
	// TotalEntries: Total number of documents matching the applied filters across all pages.
	TotalEntries int `json:"total_entries"`
	// TotalPages: Total number of pages given the current `page_size`.
	TotalPages int `json:"total_pages"`
}

// KnowledgeDocumentListParams: query parameters for KnowledgeDocumentResource.List.
type KnowledgeDocumentListParams struct {
	// Page: Page number to return. Defaults to 1.
	Page *int
	// PageSize: Number of documents per page. Defaults to 25.
	PageSize *int
	// Q: Case-insensitive prefix filter applied to the document title.
	Q *string
	// Source: Return only documents belonging to these source IDs (`cso_...`). Multiple values are OR'd.
	Source []string
	// Installation: Return only documents belonging to these installation IDs. Multiple values are OR'd.
	Installation []string
	// Agent: Return only documents owned by these agent IDs. Multiple values are OR'd.
	Agent []string
}

// KnowledgeDocumentContentParams: query parameters for KnowledgeDocumentResource.Content.
type KnowledgeDocumentContentParams struct {
	// Offset: Starting position for a content slice. When `unit` is `"lines"`, this is a 1-indexed line number. When `unit` is `"bytes"`, this is a 0-indexed byte offset. Omit to return the full document.
	Offset *int
	// Limit: Maximum number of units to return when slicing. Defaults to 200 when `unit` is `"lines"` and 8192 when `unit` is `"bytes"`.
	Limit *int
	// Unit: Unit to use for `offset` and `limit`. One of `"lines"` (default) or `"bytes"`.
	Unit *string
}

type KnowledgeDocumentResource struct {
	http *HTTPClient
}

func newKnowledgeDocumentResource(h *HTTPClient) *KnowledgeDocumentResource {
	return &KnowledgeDocumentResource{
		http: h,
	}
}

// List: List context documents
//
// Returns a paginated list of context documents visible to the authenticated
// caller within the scoped app. Results are ordered by creation time
// descending.
// Use `q` for a case-insensitive title prefix search. Use `source`,
// `installation`, or `agent` to narrow results to documents belonging to
// specific sources, installations, or agents. Multiple values within each
// filter are treated as OR conditions. Filters may be combined.
// The response includes page-level metadata so you can navigate through
// large result sets without cursor tokens.
//
// Returns: Successful response
func (r *KnowledgeDocumentResource) List(ctx context.Context, params KnowledgeDocumentListParams) (*KnowledgeDocumentListResponse, error) {
	q := url.Values{}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	if params.Q != nil {
		q.Add("q", *params.Q)
	}
	for _, item := range params.Source {
		q.Add("source", item)
	}
	for _, item := range params.Installation {
		q.Add("installation", item)
	}
	for _, item := range params.Agent {
		q.Add("agent", item)
	}
	return fetch[*KnowledgeDocumentListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_documents", Query: q})
}

// Delete: Delete a context document
//
// Permanently deletes a context document and all of its associated chunk
// items. This action is irreversible.
// The backing storage file, if any, is not deleted storage files can be
// shared across multiple documents and are cleaned up separately by the
// platform's storage garbage collector. The caller must be authenticated
// and the request must be scoped to the app that owns the document.
//
// document: Document ID (`cdo_...`) to delete.
//
// Returns: Empty body. Returns HTTP 204 on success.
func (r *KnowledgeDocumentResource) Delete(ctx context.Context, document string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/knowledge_documents/" + url.PathEscape(document)})
}

// Get: Retrieve a context document
//
// Returns a single context document identified by its ID. The response
// includes document metadata such as title, size, and ownership fields,
// but not the document's text content. To read the full or partial content,
// use the content endpoint.
// The caller must be authenticated and the request must be scoped to the
// app that owns the document.
//
// document: Document ID (`cdo_...`) to retrieve.
//
// Returns: The requested context document's metadata.
func (r *KnowledgeDocumentResource) Get(ctx context.Context, document string) (*ContextDocument, error) {
	return fetch[*ContextDocument](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_documents/" + url.PathEscape(document)})
}

// Content: Retrieve a context document's content
//
// Returns the full text of a context document, or a slice of it when
// `offset`, `limit`, and `unit` are supplied. Both file-backed and inline
// documents are supported; the response shape is the same in either case.
// When slicing, set `unit` to `"lines"` (default) or `"bytes"`. A line-based
// slice uses a 1-indexed `offset`; a byte-based slice uses a 0-indexed
// `offset`. If you omit `offset`, the full document text is returned and the
// slice-specific response fields (`unit`, `offset`, `limit`, `start_line`,
// `end_line`, `start_byte`, `end_byte`) are absent.
// The caller must be authenticated and the request must be scoped to an app
// that owns the document.
//
// document: Document ID (`cdo_...`) whose content to retrieve.
//
// Returns: The document's content, optionally sliced by offset and limit.
func (r *KnowledgeDocumentResource) Content(ctx context.Context, document string, params KnowledgeDocumentContentParams) (*ContextDocumentContent, error) {
	q := url.Values{}
	if params.Offset != nil {
		q.Add("offset", queryParam(*params.Offset))
	}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.Unit != nil {
		q.Add("unit", *params.Unit)
	}
	return fetch[*ContextDocumentContent](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_documents/" + url.PathEscape(document) + "/content", Query: q})
}
