// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 946cc84961e7

package platform

import (
	"context"
	"net/url"
)

// KnowledgeSourceCreateInput: Create a knowledge source
type KnowledgeSourceCreateInput struct {
	// Agent: Agent ID (`agt_...`) that owns this source. Mutually exclusive with `team` and `user`.
	Agent *string `json:"agent,omitempty"`
	// Metadata: Arbitrary key-value metadata to attach to the source. Returned as-is on reads.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: Organization ID (`org_...`). Required for system-owned sources that have no individual owner (`team`, `user`, or `agent`).
	Org *string `json:"org,omitempty"`
	// ParentSource: Parent knowledge source ID (`ksrc_...`). Use to create a child source.
	ParentSource *string `json:"parent_source,omitempty"`
	// Payload: Type-specific configuration for the source. Shape depends on `type`.
	Payload map[string]JSONValue `json:"payload,omitempty"`
	// State: Initial state of the source. One of `"active"` (default) or `"paused"`. Paused sources do not trigger ingestion automatically.
	State *string `json:"state,omitempty"`
	// Team: Team ID (`team_...`) that owns this source. Mutually exclusive with `user` and `agent`.
	Team *string `json:"team,omitempty"`
	// Thread: Thread ID (`thr_...`) to associate this source with, if applicable.
	Thread *string `json:"thread,omitempty"`
	// Type: Knowledge source type. Must be one of the values returned by `GET /api/v1/knowledge_sources/kinds`.
	Type string `json:"type"`
	// User: User ID (`usr_...`) that owns this source. Mutually exclusive with `team` and `agent`.
	User *string `json:"user,omitempty"`
}

// KnowledgeSourceUpdateInput: Update a knowledge source
type KnowledgeSourceUpdateInput struct {
	// Metadata: Arbitrary key-value metadata to attach to the source. Replaces the entire existing `metadata` map when provided.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Payload: Type-specific configuration to replace on the source. Shape depends on the source `type`. Replaces the entire existing `payload` when provided.
	Payload map[string]JSONValue `json:"payload,omitempty"`
	// State: Desired state of the source. One of `"active"` or `"paused"`. Paused sources do not trigger ingestion automatically.
	State *string `json:"state,omitempty"`
}

type KnowledgeSourceIngestInputContent struct {
	// ContentType: MIME type of the content, e.g. `"application/pdf"` or `"text/plain"`.
	ContentType *string `json:"content_type,omitempty"`
	// Data: The raw document bytes. When `data_encoding` is `"base64"`, provide the base64-encoded representation of the binary content.
	Data string `json:"data"`
	// DataEncoding: Encoding format of `data`. One of `"raw"` (default, plain text) or `"base64"` (binary content such as images or PDFs, decoded server-side before storage).
	DataEncoding *string `json:"data_encoding,omitempty"`
	// Filename: Original filename for the document, e.g. `"report.pdf"`.
	Filename *string `json:"filename,omitempty"`
}

// KnowledgeSourceIngestInput: Trigger ingestion on a knowledge source
type KnowledgeSourceIngestInput struct {
	// Content: Inline document bytes to push to the source. Mutually exclusive with `file` and `pull`.
	Content *KnowledgeSourceIngestInputContent `json:"content,omitempty"`
	// Dedupe: When `true`, reuse the source's existing document if the pushed content is byte-identical to it, instead of creating a duplicate. The reused document keeps its chunks and embeddings, and `title`/`metadata` from this request are still applied to it. Content that differs in any way always creates a new document. Defaults to `false`, which creates a new document on every push. Push mode only not valid with `pull: true`. Check `metadata.document_reused` on the returned ingestion to see whether a document was actually reused.
	Dedupe *bool `json:"dedupe,omitempty"`
	// File: ID of an already-uploaded file (`fil_...`). The runner reads filename and content type from the stored file. Upload the file via `POST /v1/files` first. Mutually exclusive with `content` and `pull`.
	File *string `json:"file,omitempty"`
	// Metadata: Arbitrary key-value metadata to attach to the ingested document. Applied in push mode only; ignored when `pull: true`.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Pull: When `true`, re-triggers ingestion using the source's own configured data. Re-scrapes a `scrape/site`, re-fetches a `web/link`, or re-processes a `file/document`. Mutually exclusive with `file` and `content`. Not valid for `knowledge/documents` sources.
	Pull *bool `json:"pull,omitempty"`
	// Title: Display title for the ingested document. Applied in push mode only; ignored when `pull: true`.
	Title *string `json:"title,omitempty"`
}

// KnowledgeSourceSearchInput: Search within a knowledge source
type KnowledgeSourceSearchInput struct {
	// MaxResults: Maximum number of results to return. The platform applies its own upper bound; omit to use the default.
	MaxResults *int `json:"max_results,omitempty"`
	// MinSimilarity: Cosine-similarity floor for the vector leg, 0.0-1.0. Candidates below it are discarded before ranking, so a high value trades recall for precision. Pass `0.0` to disable the floor when a missed match costs more than a weak one note that with no floor every query returns results, so an empty response can no longer be read as "no match". Omit to use the default.
	MinSimilarity *float64 `json:"min_similarity,omitempty"`
	// Mode: Search algorithm to use. One of `"hybrid"` (default, combines vector and full-text), `"vector"` (semantic similarity only), or `"fulltext"` (keyword matching only).
	Mode *string `json:"mode,omitempty"`
	// Query: Natural language or keyword query string to search for.
	Query string `json:"query"`
	// RecencyDays: When set, limits results to documents ingested within the last N days. Omit to search across all documents regardless of age.
	RecencyDays *int `json:"recency_days,omitempty"`
}

type KnowledgeSourceListResponseDataItem struct {
	// Agent: ID of the agent that owns this source (`agt_...`). `null` if owned by a human user or team.
	Agent *string `json:"agent,omitempty"`
	// ContextInstallation: ID of the context installation that provisioned this source (`cin_...`). `null` when the source was created directly rather than through an installation.
	ContextInstallation *string `json:"context_installation,omitempty"`
	// CreatedAt: When this knowledge source was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// ID: Knowledge source ID (`cso_...`).
	ID string `json:"id"`
	// Metadata: Arbitrary key-value metadata attached to this source. Useful for storing caller-defined labels or references.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: ID of the organization this source belongs to (`org_...`). `null` if not scoped to an org.
	Org *string `json:"org,omitempty"`
	// ParentSource: ID of the parent knowledge source (`cso_...`) when this source was derived from another. `null` for top-level sources.
	ParentSource *string `json:"parent_source,omitempty"`
	// Payload: Type-specific configuration object. The keys depend on the source `type`; see the create endpoint for the expected shape per type.
	Payload map[string]JSONValue `json:"payload,omitempty"`
	// Sandbox: ID of the developer sandbox this source is scoped to (`sbx_...`). `null` outside sandbox contexts.
	Sandbox *string `json:"sandbox,omitempty"`
	// State: Current lifecycle state of the source. One of `"active"` (ingestion running normally) or `"paused"` (ingestion suspended).
	State string `json:"state"`
	// Team: ID of the team that owns this source (`tea_...`). `null` if owned by a user, agent, or org.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the chat thread this source is associated with (`thr_...`). `null` when not thread-scoped.
	Thread *string `json:"thread,omitempty"`
	// Type: Source type identifier (e.g. `"gmail"`, `"github_activity"`). Determines the shape of `payload` and the ingestion behavior.
	Type string `json:"type"`
	// UpdatedAt: When this knowledge source was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user that owns this source (`usr_...`). `null` if owned by a team, agent, or org.
	User *string `json:"user,omitempty"`
}

// KnowledgeSourceListResponse: Successful response
type KnowledgeSourceListResponse struct {
	// Data: Array of knowledge source objects for the current page.
	Data []KnowledgeSourceListResponseDataItem `json:"data"`
	// HasNext: `true` if a subsequent page exists, `false` if this is the last page.
	HasNext bool `json:"has_next"`
	// HasPrev: `true` if a previous page exists, `false` if this is the first page.
	HasPrev bool `json:"has_prev"`
	// Page: Current page number.
	Page int `json:"page"`
	// PageSize: Number of results returned per page.
	PageSize int `json:"page_size"`
	// TotalEntries: Total number of knowledge sources matching the query across all pages.
	TotalEntries int `json:"total_entries"`
	// TotalPages: Total number of pages available.
	TotalPages int `json:"total_pages"`
}

type KnowledgeSourceSearchResponseDataItem struct {
	// Content: Normalized plain-text content of the matched chunk.
	Content *string `json:"content,omitempty"`
	// ContentType: MIME type of the content, e.g. `"text/plain"` or `"text/html"`.
	ContentType *string `json:"content_type,omitempty"`
	// CreatedAt: When this item was indexed into the knowledge base (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// ID: Context item ID (`cim_...`).
	ID string `json:"id"`
	// Kind: Result variant discriminator. Always `"chunk"` for this object type.
	Kind string `json:"kind"`
	// Metadata: Arbitrary key-value metadata attached to this item by the source connector.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// RawContent: Raw content payload as stored by the source connector, before normalization.
	RawContent map[string]JSONValue `json:"raw_content,omitempty"`
	// Type: Type identifier of the parent knowledge source (e.g. `"gmail"`, `"github_activity"`). Returns `"unknown"` when the source association is not loaded.
	Type *string `json:"type,omitempty"`
}

// KnowledgeSourceSearchResponse: Successful response
type KnowledgeSourceSearchResponse struct {
	// Data: Array of matching knowledge items ordered by relevance score descending.
	Data []KnowledgeSourceSearchResponseDataItem `json:"data"`
}

// KnowledgeSourceListParams: query parameters for KnowledgeSourceResource.List.
type KnowledgeSourceListParams struct {
	// Page: Page number to retrieve. Defaults to 1.
	Page *int
	// PageSize: Number of knowledge sources to return per page. Defaults to 25.
	PageSize *int
	// Search: Filter sources whose type contains this string. Case-insensitive substring match.
	Search *string
	// Type: Exact knowledge source type to filter by, e.g. `"knowledge/documents"`.
	Type *string
	// Team: Exact team IDs whose sources to include.
	Team []string
	// Thread: Exact backing thread IDs whose sources to include.
	Thread []string
	// Installation: Installation ID (`ins_...`). Returns only sources associated with this installation.
	Installation *string
	// Agent: Agent ID (`agt_...`). Returns only sources owned by or associated with this agent.
	Agent *string
	// Org: Organization ID (`org_...`). Returns only sources belonging to this organization. Combine with `owner_scope: "system"` to retrieve org-level system sources.
	Org *string
	// OwnerScope: Filter by ownership scope. One of `"any"` (default returns all visible sources), `"individual"` (only sources owned by a user, team, or agent), or `"system"` (only sources with no individual owner, typically org-level).
	OwnerScope *string
}

type KnowledgeSourceKindResource struct {
	http *HTTPClient
}

func newKnowledgeSourceKindResource(h *HTTPClient) *KnowledgeSourceKindResource {
	return &KnowledgeSourceKindResource{
		http: h,
	}
}

// List: List creatable knowledge source kinds
//
// Returns the fixed set of knowledge source types that can be created directly via
// `POST /api/v1/knowledge_sources`. Use this endpoint to discover valid values for the
// `type` param before calling the create endpoint.
// Source kinds populated by server-driven flows such as `webhook/inbound`,
// `connectors/*/emails`, and `thread/messages` are intentionally excluded from this
// list, as they cannot be created through the API.
//
// Returns: List of knowledge source kinds available for creation via the API.
func (r *KnowledgeSourceKindResource) List(ctx context.Context) (*KnowledgeSourceKindListResponse, error) {
	return fetch[*KnowledgeSourceKindListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_sources/kinds"})
}

type KnowledgeSourceResource struct {
	http  *HTTPClient
	Kinds *KnowledgeSourceKindResource
}

func newKnowledgeSourceResource(h *HTTPClient) *KnowledgeSourceResource {
	return &KnowledgeSourceResource{
		http:  h,
		Kinds: newKnowledgeSourceKindResource(h),
	}
}

// List: List knowledge sources
//
// Returns a paginated list of knowledge sources visible to the authenticated caller.
// Results are ordered by creation time descending.
// Use the `type`, `installation`, `agent`, `org`, and `owner_scope` filters to narrow the
// result set. Combine `owner_scope: "system"` with `org` to list org-level sources that
// have no individual owner. Combine `owner_scope: "individual"` with `agent` to list
// sources owned by a specific agent.
// Pagination is page-number based. The default page size is 25.
//
// Returns: Successful response
func (r *KnowledgeSourceResource) List(ctx context.Context, params KnowledgeSourceListParams) (*KnowledgeSourceListResponse, error) {
	q := url.Values{}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	if params.Search != nil {
		q.Add("search", *params.Search)
	}
	if params.Type != nil {
		q.Add("type", *params.Type)
	}
	for _, item := range params.Team {
		q.Add("team", item)
	}
	for _, item := range params.Thread {
		q.Add("thread", item)
	}
	if params.Installation != nil {
		q.Add("installation", *params.Installation)
	}
	if params.Agent != nil {
		q.Add("agent", *params.Agent)
	}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	if params.OwnerScope != nil {
		q.Add("owner_scope", *params.OwnerScope)
	}
	return fetch[*KnowledgeSourceListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_sources", Query: q})
}

// Create: Create a knowledge source
//
// Creates a new knowledge source of the requested type and returns the created object.
// Only types listed by `GET /api/v1/knowledge_sources/kinds` may be created through this
// endpoint. Other source types such as `webhook/inbound`, `connectors/*/emails`, and
// `thread/messages` are provisioned automatically by server-driven flows (webhook
// auto-provisioning, installation activation, connector lifecycle events) and cannot be
// created directly via the API.
// Exactly one of `team`, `user`, `agent`, or `org` must identify the owner of the new
// source. Omit `org` when an individual owner (`team`, `user`, or `agent`) is supplied;
// include `org` alone for org-level system-owned sources.
//
// Returns: The newly created knowledge source.
func (r *KnowledgeSourceResource) Create(ctx context.Context, input KnowledgeSourceCreateInput) (*KnowledgeSource, error) {
	return fetch[*KnowledgeSource](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/knowledge_sources", Body: input})
}

// Delete: Delete a knowledge source
//
// Permanently deletes the knowledge source identified by `source`. This action is
// irreversible all documents, embeddings, and ingestion history associated with the
// source are removed.
// The authenticated caller must own the source or have sufficient permissions within its
// parent organization. Returns `204 No Content` on success.
//
// source: Knowledge source ID (`ksrc_...`) to delete.
//
// Returns: Empty response. The source has been permanently deleted.
func (r *KnowledgeSourceResource) Delete(ctx context.Context, source string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "DELETE", Path: "/api/v1/knowledge_sources/" + url.PathEscape(source)})
}

// Get: Retrieve a knowledge source
//
// Returns the knowledge source identified by `source`. The authenticated caller must have
// access to the source's parent organization or be the individual owner of the source.
// Use the list endpoint to retrieve many sources at once or to discover sources by type
// or owner.
//
// source: Knowledge source ID (`ksrc_...`) to retrieve.
//
// Returns: The requested knowledge source.
func (r *KnowledgeSourceResource) Get(ctx context.Context, source string) (*KnowledgeSource, error) {
	return fetch[*KnowledgeSource](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/knowledge_sources/" + url.PathEscape(source)})
}

// Update: Update a knowledge source
//
// Updates the mutable fields of an existing knowledge source and returns the updated
// object. Only fields provided in the request body are changed; omitted fields retain
// their current values.
// You can update the type-specific `payload`, the `metadata` map, and the `state`. To
// pause a source and prevent automatic ingestion, set `state` to `"paused"`. To resume,
// set it back to `"active"`.
//
// source: Knowledge source ID (`ksrc_...`) to update.
//
// Returns: The updated knowledge source.
func (r *KnowledgeSourceResource) Update(ctx context.Context, source string, input KnowledgeSourceUpdateInput) (*KnowledgeSource, error) {
	return fetch[*KnowledgeSource](r.http, ctx, requestSpec{Method: "PATCH", Path: "/api/v1/knowledge_sources/" + url.PathEscape(source), Body: input})
}

// Ingest: Trigger ingestion on a knowledge source
//
// Starts an ingestion run on the specified knowledge source and returns the ingestion
// object. Exactly one of two modes must be chosen per request:
// **Push mode** (`file` or `content`) available for `knowledge/documents` sources only.
// Supply the document bytes either as a reference to an already-uploaded file (`file`) or
// as an inline blob (`content`). The runner stores the bytes and indexes the resulting
// document. `title` and `metadata` are persisted on the document in push mode.
// **Pull mode** (`pull: true`) re-triggers ingestion using the source's own configured
// data. Use this to re-scrape a `scrape/site`, re-fetch a `web/link`, or re-process a
// `file/document`. Not valid for `knowledge/documents` (which has no upstream push new
// bytes instead) or for source kinds populated by server-driven flows. `title` and
// `metadata` are ignored in pull mode.
// If an ingestion is already active for the source, the existing ingestion is returned
// rather than creating a duplicate.
//
// source: Knowledge source ID (`ksrc_...`) to ingest.
//
// Returns: The created ingestion, or an existing active ingestion if one is already running.
func (r *KnowledgeSourceResource) Ingest(ctx context.Context, source string, input KnowledgeSourceIngestInput) (*ContextIngestion, error) {
	return fetch[*ContextIngestion](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/knowledge_sources/" + url.PathEscape(source) + "/ingest", Body: input})
}

// Search: Search within a knowledge source
//
// Executes a search query against the indexed documents in a single knowledge source and
// returns matching results ranked by relevance.
// Three search modes are supported: `"hybrid"` (default) combines vector similarity and
// full-text scoring, `"vector"` uses embedding-based semantic search only, and
// `"fulltext"` uses keyword-based search only. Use `"hybrid"` for most use cases;
// prefer `"vector"` when semantic meaning matters more than exact terms.
// Optionally restrict results to documents ingested within the last N days using
// `recency_days`. Results are ordered by relevance score descending.
//
// source: Knowledge source ID (`ksrc_...`) to search within.
//
// Returns: Successful response
func (r *KnowledgeSourceResource) Search(ctx context.Context, source string, input KnowledgeSourceSearchInput) (*KnowledgeSourceSearchResponse, error) {
	return fetch[*KnowledgeSourceSearchResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/knowledge_sources/" + url.PathEscape(source) + "/search", Body: input})
}
