// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 95e492c31f3a

package platform

import (
	"context"
	"net/url"
)

// NotificationSendInput: Send a custom notification to a user
type NotificationSendInput struct {
	// Data: Arbitrary key-value payload merged with platform-provided context (recipient, app, org, brand) when rendering the notification's display fields. Defaults to an empty object when omitted.
	Data map[string]JSONValue `json:"data,omitempty"`
	// IdempotencyKey: Optional deduplication key. A second call with the same `idempotency_key` for the same recipient returns the originally-created notification without inserting a new record. Scoped per calling app.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Type: Custom notification type identifier in the form `"custom:<lookup_key>"`, where `<lookup_key>` matches a `NotificationType` config declared in the calling app's bundle.
	Type string `json:"type"`
	// User: Recipient user ID (`usr_...`). Must be a member of the calling app's tenant.
	User string `json:"user"`
}

type NotificationListResponseDataItem struct {
	// ArchivedAt: When the recipient archived this notification. `null` if the notification has not been archived.
	ArchivedAt *Time `json:"archived_at,omitempty"`
	// CreatedAt: When the notification was sent (ISO 8601).
	CreatedAt Time `json:"created_at"`
	// ID: Notification ID (`ntf_...`).
	ID string `json:"id"`
	// ReadAt: When the recipient marked this notification read. `null` if the notification has not been read.
	ReadAt *Time `json:"read_at,omitempty"`
	// Rendered: Type-specific render spec resolved at request time. All types include `title`, `kind`, and `actions`; custom types may add their own keys. Notifications whose type is no longer registered render with `kind: "unknown"`.
	Rendered map[string]JSONValue `json:"rendered"`
	// Status: Current read state of the notification. One of `"unread"`, `"read"`, or `"archived"`.
	Status string `json:"status"`
	// Type: Notification type slug, e.g. `"app_info"` for a built-in type or `"custom:deploy_complete"` for a custom type.
	Type string `json:"type"`
}

// NotificationListResponse: Successful response
type NotificationListResponse struct {
	// AfterCursor: Opaque cursor to pass as `after_cursor` on the next request to fetch older notifications. `null` when this is the last page.
	AfterCursor *string `json:"after_cursor,omitempty"`
	// BeforeCursor: Always `null` inbox pagination is forward-only and does not support fetching newer pages via cursor.
	BeforeCursor *string `json:"before_cursor,omitempty"`
	// Data: Array of notification objects for the current page, ordered newest first.
	Data []NotificationListResponseDataItem `json:"data"`
	// HasMore: `true` if additional (older) notifications exist beyond this page; `false` if this is the last page.
	HasMore bool `json:"has_more"`
}

// NotificationUnreadCountResponse: Successful response
type NotificationUnreadCountResponse struct {
	// Count: Total number of notifications with `"unread"` status belonging to the authenticated user.
	Count int `json:"count"`
}

// NotificationListParams: query parameters for NotificationResource.List.
type NotificationListParams struct {
	// Status: Filter by notification status. One of `"all"`, `"active"`, `"unread"`, `"read"`, or `"archived"`. Defaults to `"all"` when omitted.
	Status *string
	// Limit: Maximum number of notifications to return per page. Defaults to 20; maximum is 100.
	Limit *int
	// AfterCursor: Opaque pagination cursor from a previous response's `after_cursor` field. Omit to fetch the most recent notifications.
	AfterCursor *string
}

type NotificationResource struct {
	http *HTTPClient
}

func newNotificationResource(h *HTTPClient) *NotificationResource {
	return &NotificationResource{
		http: h,
	}
}

// List: List a user's notifications
//
// Returns a cursor-paginated list of inbox notifications for the authenticated
// user, ordered by creation time descending (newest first). All status groups
// are included by default; pass `status` to narrow results to a specific group.
// Each notification's `rendered` field contains type-specific display data
// resolved at request time. Notifications whose type is no longer registered
// in the platform are rendered with `kind: "unknown"` rather than being omitted.
// Pagination is forward-only: supply `after_cursor` from a previous response to
// fetch the next (older) page. The `before_cursor` field is always `null` for
// this endpoint. Requires an app-scoped token.
//
// Returns: Successful response
func (r *NotificationResource) List(ctx context.Context, params NotificationListParams) (*NotificationListResponse, error) {
	q := url.Values{}
	if params.Status != nil {
		q.Add("status", *params.Status)
	}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	return fetch[*NotificationListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/notifications", Query: q})
}

// ReadAll: Mark all notifications as read
//
// Marks every `"unread"` notification belonging to the authenticated user as
// `"read"` in a single operation. Notifications that are already `"read"` or
// `"archived"` are not affected.
// This call is safe to retry if there are no unread notifications, it
// succeeds without error. Requires an app-scoped token. Returns 204 No Content
// on success.
//
// Returns: No content
func (r *NotificationResource) ReadAll(ctx context.Context) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/notifications/read_all"})
}

// Send: Send a custom notification to a user
//
// Delivers a custom-typed notification to one of the calling app's users.
// Apps define notification types by declaring `NotificationType` config objects
// in their bundle (one per `lookup_key`). Supply the type as
// `"custom:<lookup_key>"` and provide a `data` map that is merged with
// platform-provided context to render the notification's display fields.
// Only app-scoped tokens may call this endpoint user tokens are rejected with
// 403. The app scope is stamped onto the notification automatically; an app
// cannot target recipients outside its tenant. Built-in platform types such as
// `"app_info"` and `"billing_alert"` are not accepted here.
// Pass `idempotency_key` to deduplicate sends. If you call this endpoint twice
// with the same `idempotency_key` for the same recipient, the second call
// returns the original notification without creating a duplicate. The key is
// scoped to the calling app, so the same raw key used by different apps cannot
// collide.
//
// Returns: The created notification, or the existing notification when deduplicated by `idempotency_key`.
func (r *NotificationResource) Send(ctx context.Context, input NotificationSendInput) (*Notification, error) {
	return fetch[*Notification](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/notifications/send", Body: input})
}

// UnreadCount: Get the unread notification count
//
// Returns the total number of `"unread"` notifications for the authenticated
// user. Useful for displaying a badge or indicator in your UI without
// fetching the full notification list.
// Notifications with `"read"` or `"archived"` status are not included in the
// count. Requires an app-scoped token.
//
// Returns: Successful response
func (r *NotificationResource) UnreadCount(ctx context.Context) (*NotificationUnreadCountResponse, error) {
	return fetch[*NotificationUnreadCountResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/notifications/unread_count"})
}

// Archive: Archive a notification
//
// Moves a notification to `"archived"` status regardless of whether it is
// currently `"unread"` or `"read"`. Archived notifications are excluded from
// the default inbox view but remain retrievable by passing `status: "archived"`
// to the list endpoint.
// The authenticated user must own the notification. Passing a notification ID
// that belongs to a different user returns a 404. If the notification is
// already archived this call succeeds without error (idempotent).
// Requires an app-scoped token. Returns 204 No Content on success.
//
// notification: Notification ID (`ntf_...`) to archive. Must belong to the authenticated user.
//
// Returns: No content
func (r *NotificationResource) Archive(ctx context.Context, notification string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/notifications/" + url.PathEscape(notification) + "/archive"})
}

// Read: Mark a notification as read
//
// Transitions a notification from `"unread"` to `"read"` status. If the
// notification is already `"read"` or `"archived"`, the call succeeds without
// changing its status (idempotent).
// The authenticated user must own the notification. Passing a notification ID
// that belongs to a different user returns a 404. Requires an app-scoped token.
// Returns 204 No Content on success.
//
// notification: Notification ID (`ntf_...`) to mark as read. Must belong to the authenticated user.
//
// Returns: No content
func (r *NotificationResource) Read(ctx context.Context, notification string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/notifications/" + url.PathEscape(notification) + "/read"})
}

// Unarchive: Unarchive a notification
//
// Restores an `"archived"` notification to its previous active status:
// `"read"` if the notification had been read before archiving, or `"unread"`
// otherwise. The notification will appear again in the default inbox view.
// The authenticated user must own the notification. Passing a notification ID
// that belongs to a different user returns a 404. If the notification is not
// currently archived this call succeeds without changing its status (idempotent).
// Requires an app-scoped token. Returns 204 No Content on success.
//
// notification: Notification ID (`ntf_...`) to unarchive. Must belong to the authenticated user.
//
// Returns: No content
func (r *NotificationResource) Unarchive(ctx context.Context, notification string) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/notifications/" + url.PathEscape(notification) + "/unarchive"})
}
