// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4e9d134e278f

package platform

import "context"

// DeviceApproveInput: Approve a device authorization request
type DeviceApproveInput struct {
	// Thread: Thread ID (`thr_...`) to bind to the authorization. Required when the requested scopes include a thread-scoped permission.
	Thread *string `json:"thread,omitempty"`
	// UserCode: User-facing verification code shown on the device. Identifies the pending authorization to approve.
	UserCode string `json:"user_code"`
}

// DeviceAuthorizeInput: Initiate a device authorization request
type DeviceAuthorizeInput struct {
	// Client: OAuth client ID (`cli_...`) identifying the application requesting authorization.
	Client string `json:"client"`
	// Scope: Space-separated list of OAuth scopes to request, e.g. `"read write"`. Omit to request only the default scopes configured for the client.
	Scope *string `json:"scope,omitempty"`
}

// DeviceDenyInput: Deny a device authorization request
type DeviceDenyInput struct {
	// UserCode: User-facing verification code shown on the device. Identifies the pending authorization to deny.
	UserCode string `json:"user_code"`
}

// OauthTokenInput: Exchange a grant for OAuth tokens
type OauthTokenInput struct {
	// Client: OAuth client ID identifying the application requesting tokens. Required for `"authorization_code"` and device-code grants.
	Client *string `json:"client,omitempty"`
	// Code: Single-use authorization code issued by the authorization endpoint. Required for `"authorization_code"` grants.
	Code *string `json:"code,omitempty"`
	// CodeVerifier: PKCE code verifier corresponding to the `code_challenge` sent in the authorization request. Required when the authorization code was issued with a code challenge; omit otherwise.
	CodeVerifier *string `json:"code_verifier,omitempty"`
	// DeviceCode: Device code received from the device authorization endpoint. Required for device-code grants.
	DeviceCode *string `json:"device_code,omitempty"`
	// GrantType: The OAuth 2.0 grant type. One of `"authorization_code"`, `"refresh_token"`, or `"urn:ietf:params:oauth:grant-type:device_code"`.
	GrantType string `json:"grant_type"`
	// RedirectURI: Redirect URI that was used in the original authorization request. Must exactly match the URI on record for the client. Required for `"authorization_code"` grants.
	RedirectURI *string `json:"redirect_uri,omitempty"`
	// RefreshToken: Refresh token received from a previous token response. Required for `"refresh_token"` grants. The token is rotated on each successful call.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// OauthScopesResponse: Successful response
type OauthScopesResponse struct {
	// Scopes: Map of scope name to its definition object. Each key is a scope string (e.g. `"thread:read"`) and each value describes the scope's purpose and requirements.
	Scopes map[string]JSONValue `json:"scopes"`
}

type DeviceResource struct {
	http *HTTPClient
}

func newDeviceResource(h *HTTPClient) *DeviceResource {
	return &DeviceResource{
		http: h,
	}
}

// Approve: Approve a device authorization request
//
// Grants the pending device authorization identified by `user_code`, completing
// the OAuth Device Authorization flow on behalf of the authenticated user. Once
// approved, the device can exchange the `device_code` for an access token.
// Requires a valid user session the request must be authenticated as an end
// user, not a machine client. The `user_code` must belong to a pending (not
// expired, not already approved or denied) authorization associated with the
// calling app.
// If the requested scopes include a `thread`-scoped permission, you must supply
// the `thread` parameter; omitting it returns a 400 with `error: "invalid_scope"`.
//
// Returns: Confirmation that the device authorization was approved. The `status` field will be `"approved"`.
func (r *DeviceResource) Approve(ctx context.Context, input DeviceApproveInput) (*DeviceAuthorizationStatusResponse, error) {
	return fetch[*DeviceAuthorizationStatusResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/oauth/device/approve", Body: input})
}

// Authorize: Initiate a device authorization request
//
// Starts the OAuth 2.0 Device Authorization flow for a device that cannot
// perform browser-based redirects. Returns a `device_code` (used by the device
// to poll for a token) and a `user_code` (shown to the user to enter at the
// `verification_uri`).
// This endpoint requires a publishable API key; secret keys are rejected with
// a 403. Third-party OAuth must be enabled on the app; if it is not, the
// response returns `error: "third_party_oauth_not_enabled"` with a 403.
// The endpoint is rate-limited to 10 requests per IP per minute. Excess
// requests receive a 429 response. The returned codes expire after
// `expires_in` seconds; once expired, a new authorization request must be
// initiated.
//
// Returns: Device authorization codes and polling parameters. Present the `user_code` to the user and direct them to `verification_uri`. Poll the token endpoint using `device_code` at the rate given by `interval`.
func (r *DeviceResource) Authorize(ctx context.Context, input DeviceAuthorizeInput) (*DeviceAuthorizationResponse, error) {
	return fetch[*DeviceAuthorizationResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/oauth/device/authorize", Body: input})
}

// Deny: Deny a device authorization request
//
// Rejects the pending device authorization identified by `user_code`, preventing
// the device from obtaining an access token. Once denied, the device will
// receive an `access_denied` error on its next token poll.
// Requires a valid user session. The `user_code` must belong to a pending
// authorization associated with the calling app. Attempting to deny an already
// approved, already denied, or expired authorization returns a 400.
//
// Returns: Confirmation that the device authorization was denied. The `status` field will be `"denied"`.
func (r *DeviceResource) Deny(ctx context.Context, input DeviceDenyInput) (*DeviceAuthorizationStatusResponse, error) {
	return fetch[*DeviceAuthorizationStatusResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/oauth/device/deny", Body: input})
}

type OauthResource struct {
	http   *HTTPClient
	Device *DeviceResource
}

func newOauthResource(h *HTTPClient) *OauthResource {
	return &OauthResource{
		http:   h,
		Device: newDeviceResource(h),
	}
}

// Scopes: List available OAuth scopes
//
// Returns the complete set of OAuth scopes that the platform supports.
// Use this endpoint to discover which scopes are available before constructing
// an authorization request or rendering a consent UI.
// No authentication is required. The response is the same for all callers.
//
// Returns: Successful response
func (r *OauthResource) Scopes(ctx context.Context) (*OauthScopesResponse, error) {
	return fetch[*OauthScopesResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/oauth/scopes"})
}

// Token: Exchange a grant for OAuth tokens
//
// Issues an access token and a refresh token in exchange for a valid grant.
// Three grant types are supported: `"authorization_code"`, `"refresh_token"`,
// and `"urn:ietf:params:oauth:grant-type:device_code"`.
// For `"authorization_code"` grants, supply `code`, `client`, `redirect_uri`, and
// optionally `code_verifier` for PKCE flows. Each authorization code is single-use;
// consuming it a second time returns `invalid_grant`.
// For `"refresh_token"` grants, supply `refresh_token`. The endpoint rotates the
// refresh token on every call and returns a fresh pair of tokens.
// For device-code grants, supply `device_code` and `client`. Poll this endpoint
// after receiving `authorization_pending` until the user approves or the code
// expires. Slow down polling if you receive `slow_down`.
// This endpoint is rate-limited to 20 requests per IP per 60 seconds. Exceeding
// the limit returns HTTP 429 with `"error": "too_many_requests"`.
//
// Returns: Token pair issued for the authenticated user.
func (r *OauthResource) Token(ctx context.Context, input OauthTokenInput) (*OAuthTokenResponse, error) {
	return fetch[*OAuthTokenResponse](r.http, ctx, requestSpec{Method: "POST", Path: "/oauth/token", Body: input})
}
