// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: cef494614bb5

package platform

import (
	"context"
	"net/url"
)

type OrgThreadCreateInputThreadMembersItem struct {
	// ID: Public user (`usr_...`) or agent (`agt_...`) ID matching `type`.
	ID string `json:"id"`
	// Type: Member kind. Use `user` for a user ID or `agent` for an agent ID.
	Type string `json:"type"`
}

type OrgThreadCreateInputThreadProfilePicture struct {
	// Data: Base64-encoded image bytes.
	Data *string `json:"data,omitempty"`
	// Filename: Original filename of the uploaded image, used for display and content-type inference.
	Filename *string `json:"filename,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`.
	MimeType *string `json:"mime_type,omitempty"`
}

type OrgThreadCreateInputThreadSettings struct {
	// AgentEnabled: Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured. `null` when a client explicitly cleared the setting.
	AgentEnabled *bool `json:"agent_enabled,omitempty"`
}

type OrgThreadCreateInputThread struct {
	// CreateLegacyAgent: When `true`, provisions a legacy chat agent alongside the thread. Only needed for integrations that depend on the pre-v2 agent model.
	CreateLegacyAgent *bool `json:"create_legacy_agent,omitempty"`
	// Description: Optional longer description of the thread's purpose. `null` if not provided.
	Description *string `json:"description,omitempty"`
	// IsUnlisted: When `true`, the thread is hidden from the default thread list and accessible only by direct link or ID.
	IsUnlisted *bool `json:"is_unlisted,omitempty"`
	// Key: Client-assigned unique key for idempotent creation or later lookup. Must be unique within the owning organization.
	Key *string `json:"key,omitempty"`
	// Kind: Optional behavioral subtype. `personal` is accepted only for a user-owned thread and limits membership to that user and agents currently owned by them. `feed` is accepted for any owner and renders the thread as a post feed: message lists return top-level posts with their newest replies inline, and agent responses attach to the root post. Mirror kinds remain server-derived and cannot be selected by callers.
	Kind *string `json:"kind,omitempty"`
	// Members: Users and agents to add atomically when the thread is created. Each target must pass the same authorization rules as a post-creation member add. Slack mirror threads reject non-empty caller-supplied rosters because their membership is sync-owned.
	Members []OrgThreadCreateInputThreadMembersItem `json:"members,omitempty"`
	// Metadata: Arbitrary key-value pairs stored alongside the thread. Values must be strings or numbers.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Muted: When `true`, push and in-app notifications for this thread are suppressed for the creating user.
	Muted *bool `json:"muted,omitempty"`
	// OrgID: ID of the organization to create the thread under. Defaults to the authenticated user's primary organization when omitted.
	OrgID *string `json:"org_id,omitempty"`
	// ProfilePicture: Optional profile image for the thread, provided as a base64-encoded payload.
	ProfilePicture *OrgThreadCreateInputThreadProfilePicture `json:"profile_picture,omitempty"`
	// Settings: Configuration overrides for the thread, such as AI model selection and context window settings.
	Settings *OrgThreadCreateInputThreadSettings `json:"settings,omitempty"`
	// Slug: Optional URL-safe identifier. Derived from the title when omitted and unique within the thread owner.
	Slug *string `json:"slug,omitempty"`
	// Title: Display name for the thread. `null` if omitted, which causes the thread to be untitled.
	Title *string `json:"title,omitempty"`
	// Visibility: Thread visibility. A team-owned thread with members must explicitly use `restricted` or `private`. User- and agent-owned threads with members default to `private` and reject every other value. `org` is only valid on an organization-owned thread with no team, user, or agent owner.
	Visibility *string `json:"visibility,omitempty"`
}

// OrgThreadCreateInput: Create an organization-visibility thread
type OrgThreadCreateInput struct {
	// SkipWelcomeMessage: When `true`, suppresses the automatic welcome message that is otherwise sent into the thread on creation. Defaults to `false`.
	SkipWelcomeMessage *bool `json:"skip_welcome_message,omitempty"`
	// Thread: Attributes for the new thread. Visibility is forced to `org`.
	Thread *OrgThreadCreateInputThread `json:"thread"`
}

type OrgThreadListResponseDataItemParentMessageAclAddItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParentMessageAclGrantsItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParentMessageAclRemoveItem struct {
	// Principal: The identifier of the principal to remove. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`. Omit when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal to remove. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParentMessageAcl struct {
	// Add: Patch mode: grants to add or merge into the existing list. Cannot be combined with `grants`.
	Add []OrgThreadListResponseDataItemParentMessageAclAddItem `json:"add,omitempty"`
	// Grants: Replace mode: the complete new list of grants that replaces all existing entries. Send an empty array (`[]`) to clear all grants. Cannot be combined with `add` or `remove`.
	Grants []OrgThreadListResponseDataItemParentMessageAclGrantsItem `json:"grants,omitempty"`
	// Remove: Patch mode: principals whose grants should be removed from the existing list. Cannot be combined with `grants`.
	Remove []OrgThreadListResponseDataItemParentMessageAclRemoveItem `json:"remove,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageActorsItemProfilePicture struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageActorsItem struct {
	// Alias: Short handle or alias for the actor, used as an alternate display identifier. `null` if not configured.
	Alias *string `json:"alias,omitempty"`
	// ID: Composite actor identifier. Format is `"user-<usr_...>"` for human users or `"agent-<agi_...>"` for agents.
	ID *string `json:"id,omitempty"`
	// Name: Display name of the actor shown in the UI. `null` if no name is set.
	Name *string `json:"name,omitempty"`
	// ProfilePicture: Profile picture for the actor. `null` if the actor has no profile picture.
	ProfilePicture *OrgThreadListResponseDataItemParentMessageActorsItemProfilePicture `json:"profile_picture,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageAttachmentsItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageAttachmentsItemVariantsItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageAttachmentsItemVariantsItem struct {
	// ContentType: MIME type of this variant's file (e.g., `"image/jpeg"`, `"video/mp4"`). `null` if the file is not loaded.
	ContentType *string `json:"content_type,omitempty"`
	// CreatedAt: When this variant was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// File: ID of the underlying storage file that backs this variant (`fil_...`).
	File *string `json:"file,omitempty"`
	// Filename: Original filename of the uploaded file for this variant. `null` if the file is not loaded.
	Filename *string `json:"filename,omitempty"`
	// Height: Height of this variant in pixels. `null` if not recorded.
	Height *int `json:"height,omitempty"`
	// ID: Media variant ID (`mvr_...`).
	ID string `json:"id"`
	// ImageSource: Resolved image delivery metadata for this variant, including dimensions and CDN URL. `null` for non-image content types.
	ImageSource *OrgThreadListResponseDataItemParentMessageAttachmentsItemVariantsItemImageSource `json:"image_source,omitempty"`
	// UpdatedAt: When this variant was last updated (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// URL: Signed download URL for this variant, resolved at request time. `null` if the file is unavailable.
	URL *string `json:"url,omitempty"`
	// VariantKey: Identifier for this variant's processing tier. Common values include `"original"` (the unmodified upload) and `"thumbnail"` (a resized preview).
	VariantKey *string `json:"variant_key,omitempty"`
	// Width: Width of this variant in pixels. `null` if not recorded.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageAttachmentsItem struct {
	// ContentType: MIME type of the attached file, e.g. `"image/png"` or `"application/pdf"`. Present on `file`, `artifact`, and `media` types. `null` otherwise.
	ContentType *string `json:"content_type,omitempty"`
	// Description: Short description. The page meta-description for `scraped_link`, the artifact description for `artifact`, and the task description for `task` types. `null` on other types.
	Description *string `json:"description,omitempty"`
	// Filename: Original filename of the attached file, e.g. `"report.pdf"`. Present on `file`, `artifact`, and `media` types. `null` otherwise.
	Filename *string `json:"filename,omitempty"`
	// Height: Height in pixels of the media item. Present on `media` type only. `null` otherwise.
	Height *int `json:"height,omitempty"`
	// ID: Unique identifier for this attachment within the message.
	ID string `json:"id"`
	// ImageHeight: Height in pixels of the scraped preview image. Present on `scraped_link` type only. `null` otherwise.
	ImageHeight *int `json:"image_height,omitempty"`
	// ImageSource: Image source metadata for inline rendering. Present on `file`, `scraped_link`, `artifact`, and `media` types when the content is an image. `null` otherwise.
	ImageSource *OrgThreadListResponseDataItemParentMessageAttachmentsItemImageSource `json:"image_source,omitempty"`
	// ImageURL: URL of the preview image extracted from the scraped page. Present on `scraped_link` type only. `null` otherwise.
	ImageURL *string `json:"image_url,omitempty"`
	// ImageWidth: Width in pixels of the scraped preview image. Present on `scraped_link` type only. `null` otherwise.
	ImageWidth *int `json:"image_width,omitempty"`
	// Key: For `structured_data` type, what the data is about as set by the sender (for example `"pr:14963"`), copied from the record so it can be read without `object`. Not unique. `null` when unset and on other types.
	Key *string `json:"key,omitempty"`
	// MediaType: The media category, e.g. `"video"` or `"audio"`. Present on `media` type only; omitted otherwise.
	MediaType *string `json:"media_type,omitempty"`
	// Name: Display name of the media item. Present on `media` type only. `null` otherwise.
	Name *string `json:"name,omitempty"`
	// Object: The full embedded object payload. For `task` type, contains the task record. For `action` type, contains the action definition. For `chart` type, contains the chart with its inline `spec`. For `structured_data` type, contains the inline `data` and the `schema_url` or `schema_config` naming its JSON Schema. Omitted on other types.
	Object map[string]JSONValue `json:"object,omitempty"`
	// Title: Display title. The page title for `scraped_link`, the artifact name for `artifact`, and the task title for `task` types. `null` on other types.
	Title *string `json:"title,omitempty"`
	// Type: The attachment type. One of `"file"`, `"scraped_link"`, `"artifact"`, `"task"`, `"media"`, `"action"`, `"chart"`, or `"structured_data"`. Determines which additional fields are present.
	Type string `json:"type"`
	// URL: URL to access the resource. A signed download URL for `file` and `artifact` types; the original URL for `scraped_link`; a media playback URL for `media`. `null` on `task` and `action` types.
	URL *string `json:"url,omitempty"`
	// Variants: Array of available encoding variants for the media item (e.g. different resolutions). Present on `media` type only; omitted otherwise.
	Variants []OrgThreadListResponseDataItemParentMessageAttachmentsItemVariantsItem `json:"variants,omitempty"`
	// Version: Version number of the attached artifact at the time of attachment. Present on `artifact` type only. `null` otherwise.
	Version *int `json:"version,omitempty"`
	// Width: Width in pixels of the media item. Present on `media` type only. `null` otherwise.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParentMessageContextItem struct {
	// Attributes: Scalar key-value fields describing the context, such as route, repository, or pull-request number.
	Attributes map[string]JSONValue `json:"attributes,omitempty"`
	// Content: Optional context body. The model receives it as escaped XML data, not a system instruction.
	Content *string `json:"content,omitempty"`
	// Title: Optional human-readable label for this context block.
	Title *string `json:"title,omitempty"`
	// Type: Stable context kind. Must start with a lowercase letter and contain only lowercase letters, numbers, dots, dashes, or underscores.
	Type string `json:"type"`
}

type OrgThreadListResponseDataItemParentMessageReactionsItem struct {
	// Payload: Type-specific reaction data. For `"emoji_reaction"` reactions, contains an `emoji` key with the Unicode emoji string (e.g., `" "`).
	Payload map[string]JSONValue `json:"payload,omitempty"`
	// Type: Reaction type identifier. Currently always `"emoji_reaction"` for emoji-based reactions.
	Type string `json:"type"`
	// User: Public ID of the user who added the reaction (`usr_...`).
	User *string `json:"user,omitempty"`
}

type OrgThreadListResponseDataItemParentMessage struct {
	// ACL: Access control list for private messages (grants with `read` action). Only returned to resource owners (and privileged/org-admin viewers) via server-side `field_redactions: [acl: :owner]`; `null` for everyone else.
	ACL *OrgThreadListResponseDataItemParentMessageAcl `json:"acl,omitempty"`
	// Actors: Resolved actor descriptors for the message sender, combining identity and display metadata. Always contains exactly one entry.
	Actors []OrgThreadListResponseDataItemParentMessageActorsItem `json:"actors,omitempty"`
	// Agent: ID of the agent user that sent this message (`agi_...`). `null` for messages sent by human users.
	Agent *string `json:"agent,omitempty"`
	// AgentMode: Local agent execution mode for this message. One of `cli`, `embedded`, or `null` when the message was not created by a local agent execution path.
	AgentMode *string `json:"agent_mode,omitempty"`
	// Attachments: Files, links, tasks, media, artifacts, and actions attached to this message. Empty array if there are no attachments.
	Attachments []OrgThreadListResponseDataItemParentMessageAttachmentsItem `json:"attachments,omitempty"`
	// BranchedThread: ID of the thread that was branched from this message (`thr_...`). `null` if this message has not spawned a branch thread.
	BranchedThread *string `json:"branched_thread,omitempty"`
	// Content: Text content of the message. `null` for messages that contain only attachments.
	Content *string `json:"content,omitempty"`
	// Context: Immutable structured context captured when the message was posted. Each entry has `type`, optional `title` and `content`, and scalar `attributes`. Always present; defaults to an empty array. Context is delivered to agents as escaped XML data, not as system instructions.
	Context []OrgThreadListResponseDataItemParentMessageContextItem `json:"context,omitempty"`
	// CreatedAt: When the message was posted (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// HasReplies: Whether this message has at least one reply. Only present when explicitly requested or computed by the server.
	HasReplies *bool `json:"has_replies,omitempty"`
	// ID: Message ID (`msg_...`).
	ID string `json:"id"`
	// IdempotencyKey: Client-supplied idempotency key used to deduplicate message sends. `null` if the sender did not provide one.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// IsDeleted: Whether this message is a deletion tombstone. `true` only on the `message_updated` broadcast emitted when a message is deleted: the original content is replaced with a placeholder and the message no longer exists on the server. Always `false` for live messages.
	IsDeleted *bool `json:"is_deleted,omitempty"`
	// LegacyAgent: Identifier of the legacy chat agent that sent this message, if applicable. `null` for messages sent by users or modern agent users.
	LegacyAgent *string `json:"legacy_agent,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the message. Always present; defaults to an empty object when no metadata has been set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: ID of the organization that owns this message (`org_...`).
	Org *string `json:"org,omitempty"`
	// Reactions: Emoji and other reactions added to this message by users. Empty array if no reactions have been added or the association is not preloaded.
	Reactions []OrgThreadListResponseDataItemParentMessageReactionsItem `json:"reactions,omitempty"`
	// RenderingMode: Display hint for how the message should be rendered. One of `"reply"`, `"direct"`, or `"inline"`. `null` for user-authored messages, which are always rendered as standard replies.
	RenderingMode *string `json:"rendering_mode,omitempty"`
	// Replies: Inline array of reply messages, each serialized as a full message object. Only present when the server has preloaded replies for this message.
	Replies []map[string]JSONValue `json:"replies,omitempty"`
	// RepliesAfterCursor: Opaque pagination cursor to fetch replies posted after the current page. Only present when inline replies are included in the response.
	RepliesAfterCursor *string `json:"replies_after_cursor,omitempty"`
	// RepliesBeforeCursor: Opaque pagination cursor to fetch replies posted before the current page. Only present when inline replies are included in the response.
	RepliesBeforeCursor *string `json:"replies_before_cursor,omitempty"`
	// ReplyCount: Total number of direct replies to this message. Only present when explicitly requested or computed by the server.
	ReplyCount *int `json:"reply_count,omitempty"`
	// ReplyTo: The parent message this message is a reply to, expanded as a full message object when loaded. `null` if this is a top-level message or the association is not preloaded.
	ReplyTo map[string]JSONValue `json:"reply_to,omitempty"`
	// RootMessageID: ID of the root message in this reply chain (`msg_...`). `null` for a top-level message. The value is persisted when the reply is created, so callers can correlate a multi-turn session without walking parent messages.
	RootMessageID *string `json:"root_message_id,omitempty"`
	// Sandbox: ID of the developer sandbox this message belongs to (`dsb_...`). `null` for non-sandbox messages.
	Sandbox *string `json:"sandbox,omitempty"`
	// Team: ID of the team this message is scoped to (`tem_...`). `null` if the message is not team-scoped.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the thread this message belongs to (`thr_...`).
	Thread *string `json:"thread,omitempty"`
	// Type: Optional client-defined classification for the message (for example `note` or `status`). Free-form string up to 64 characters. The value `system` is reserved for platform-authored messages and cannot be set by clients. `null` when unset.
	Type *string `json:"type,omitempty"`
	// User: The human user who sent this message. Returns a public ID string (`usr_...`) when the association is not preloaded, or an expanded user object when it is. `null` for messages sent by agents.
	User *JSONValue `json:"user,omitempty"`
	// Visibility: Message-level visibility. `default` is visible to anyone who can see the parent thread. `private` is restricted to the sender and explicit ACL `read` grantees.
	Visibility *string `json:"visibility,omitempty"`
}

type OrgThreadListResponseDataItemParticipantsItem struct {
	// Alias: Short handle or alias for the user. `null` if not set.
	Alias *string `json:"alias,omitempty"`
	// App: ID of the app this user (and their access token) is scoped to (`dap_...`). `null` if the user is not scoped to an app.
	App *string `json:"app,omitempty"`
	// AppName: Display name of the user's app. `null` when the app association was not preloaded by the caller.
	AppName *string `json:"app_name,omitempty"`
	// CreatedByAgentUser: Agent user that created this account (`usr_...`). `null` unless an agent created it.
	CreatedByAgentUser *string `json:"created_by_agent_user,omitempty"`
	// CreatedByDeveloper: Developer account that created this user (`dva_...`). `null` unless created via a developer token.
	CreatedByDeveloper *string `json:"created_by_developer,omitempty"`
	// CreatedByOrg: Org of the principal that created this user (`org_...`). `null` on legacy rows.
	CreatedByOrg *string `json:"created_by_org,omitempty"`
	// CreatedByTeam: Team that created this user (`tem_...`). `null` unless created as a team.
	CreatedByTeam *string `json:"created_by_team,omitempty"`
	// CreatedByUser: User who created this account (`usr_...`). `null` on self-signup or legacy rows.
	CreatedByUser *string `json:"created_by_user,omitempty"`
	// Email: Email address of the user.
	Email *string `json:"email,omitempty"`
	// ID: User ID (`usr_...`).
	ID string `json:"id"`
	// IsSystemUser: `true` if this account is an internal system user rather than a human. System users are created automatically by the platform.
	IsSystemUser *bool `json:"is_system_user,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the user. Defaults to an empty object.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Full display name of the user. `null` if the user has not set a name.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this user belongs to (`org_...`). `null` if the user is not a member of any organization.
	Org *string `json:"org,omitempty"`
	// OrgName: Display name of the user's organization. `null` when the user is not in an org, or when the org association was not preloaded by the caller.
	OrgName *string `json:"org_name,omitempty"`
	// OrgRole: Role of the user within their organization. One of `"admin"`, `"member"`, or `"viewer"`. `null` when the user is not a member of any organization.
	OrgRole *string `json:"org_role,omitempty"`
	// OrgSlug: Stable workspace slug for the user's organization. `null` when the user is not in an org, or when the org association was not preloaded by the caller.
	OrgSlug *string `json:"org_slug,omitempty"`
	// Sandbox: ID of the sandbox environment this user is scoped to (`sbx_...`). `null` for production users.
	Sandbox *string `json:"sandbox,omitempty"`
	// SandboxName: Display name of the user's sandbox environment. `null` for production users, or when the sandbox association was not preloaded by the caller.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemAclAddItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemAclGrantsItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemAclRemoveItem struct {
	// Principal: The identifier of the principal to remove. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`. Omit when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal to remove. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemAcl struct {
	// Add: Patch mode: grants to add or merge into the existing list. Cannot be combined with `grants`.
	Add []OrgThreadListResponseDataItemParticipatingAgentsItemAclAddItem `json:"add,omitempty"`
	// Grants: Replace mode: the complete new list of grants that replaces all existing entries. Send an empty array (`[]`) to clear all grants. Cannot be combined with `add` or `remove`.
	Grants []OrgThreadListResponseDataItemParticipatingAgentsItemAclGrantsItem `json:"grants,omitempty"`
	// Remove: Patch mode: principals whose grants should be removed from the existing list. Cannot be combined with `grants`.
	Remove []OrgThreadListResponseDataItemParticipatingAgentsItemAclRemoveItem `json:"remove,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionOrgLogo struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContractParticipantsItem struct {
	// Description: Workflow-authored explanation of the slot's role. `null` when the workflow declares none.
	Description *string `json:"description,omitempty"`
	// Name: The slot's name, as referenced by the workflow. Supply the chosen agent under the top-level `participants[name]` field when invoking.
	Name string `json:"name"`
	// Required: Whether the workflow requires this slot to be filled for the run to complete its embedded stages.
	Required bool `json:"required"`
	// Type: The kind of principal the slot accepts. Currently always `"agent_user"` the value supplied at invoke is an agent ID (`agi_...`).
	Type string `json:"type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContractPrefills struct {
	// Participants: Participant slot-to-agent mappings applied by the platform. Caller values at these slots must match exactly.
	Participants map[string]JSONValue `json:"participants,omitempty"`
	// Payload: Partial invocation payload applied by the platform. A caller may omit these values, but supplying a different value at any locked path is rejected.
	Payload map[string]JSONValue `json:"payload,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContract struct {
	// InputSchema: JSON Schema validated against the whole invoke payload, from the automation's `input_schema_config`. `null` when none is configured.
	InputSchema map[string]JSONValue `json:"input_schema,omitempty"`
	// Participants: Named participant slots declared by the workflow, sorted by name. `null` when the workflow declares none. Values supplied under the top-level `participants` field are agent IDs.
	Participants []OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContractParticipantsItem `json:"participants,omitempty"`
	// Prefills: Owner-controlled payload and participant values the platform applies to every invocation. Supplying a conflicting value is rejected.
	Prefills *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContractPrefills `json:"prefills"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetails struct {
	// AutomationType: Automation execution type (`invoked`, `scheduled`, or `trigger`). `null` when the template body does not declare one.
	AutomationType *string `json:"automation_type,omitempty"`
	// InvokeContract: Schema-driven payload and participant inputs for an invoked automation. Used by installation clients to collect locked prefills before provisioning. `null` for non-invoked automation types.
	InvokeContract *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetailsInvokeContract `json:"invoke_contract,omitempty"`
	// Type: Template-details discriminator. Always `automation` for this variant.
	Type string `json:"type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItem struct {
	// Description: Short prose blurb from the template body's `description:` field. `null` when the body doesn't set one. Used as the card subhead in the Library carousel.
	Description *string `json:"description,omitempty"`
	// Details: Template-kind-specific details selected by the `type` discriminator. `null` when this template kind has no additional details.
	Details *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItemDetails `json:"details,omitempty"`
	// DisplayName: Human-facing label from the template body's `display_name:` field. `null` when the body doesn't set one. Library carousels use this for the card title, falling back to a humanized `name`.
	DisplayName *string `json:"display_name,omitempty"`
	// ID: Template config ID (`cfg_...`). `null` for inline-only templates.
	ID *string `json:"id,omitempty"`
	// Kind: Template config kind, or `SolutionTemplateRef` / `SolutionTemplatePath` when unresolved.
	Kind string `json:"kind"`
	// LookupKey: Lookup key stamped on the template config at import time. `null` when no lookup key was assigned.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Name: Canonical name from the template body. For `AgentTemplate` this doubles as the human-facing label; for `AgentToolTemplate` it's the LLM-facing tool function identifier (snake_case); for `AgentRoutineTemplate` it's the routine identifier (kebab-case). Clients rendering carousels should prefer `display_name` and fall back to humanizing `name`.
	Name *string `json:"name,omitempty"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded, scoped to this template's bundled markdown asset. `null` when the Solution body's `templates[].readme_path` is unset for this entry. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// VirtualPath: Stable virtual path assigned to the template config. `null` when no virtual path was set.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolution struct {
	// CategoryKeys: Category tag keys declared in the Solution body, used to group Solutions in the catalog. An empty array when the body declares none.
	CategoryKeys []string `json:"category_keys,omitempty"`
	// CreatedAt: When the Solution config was first imported (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// Description: Short tagline or summary declared in the Solution body, used as the card subhead in catalog UIs. `null` when the Solution body does not set one.
	Description *string `json:"description,omitempty"`
	// Events: Custom analytics events declared in the Solution body's `events:` manifest a map of event key (snake_case) to its definition (`label`, optional `description`, optional typed `fields`). Dashboards use the `label` as the event's display name. Present as an empty object when the body declares none.
	Events map[string]JSONValue `json:"events,omitempty"`
	// ID: Solution config ID (`cfg_...`).
	ID string `json:"id"`
	// ImageURL: Absolute URL of the Solution's cover image the bundled asset the body's `image:` field names. A stable, non-expiring capability URL (like `org_logo.url`), safe to hold in caches and OpenGraph tags; it 404s if the Solution stops declaring a cover. `null` when the Solution has no cover image. Org-only rows remain `null`; when a list entry merges an org copy with its system counterpart, it may reuse the system row's public cover URL. Permanent URLs are never minted for private org assets.
	ImageURL *string `json:"image_url,omitempty"`
	// InstalledConfigIds: Config IDs (`cfg_...`) of this Solution's installations in the viewer's organization. The array is empty when the Solution is visible only from the system catalog.
	InstalledConfigIds []string `json:"installed_config_ids"`
	// Kind: Resource type. Always `"Solution"`.
	Kind string `json:"kind"`
	// LatestSolution: When `upgrade_available` is `true`, the system-scope Solution config ID (`cfg_...`) that should be used as the upgrade source. `null` otherwise.
	LatestSolution *string `json:"latest_solution,omitempty"`
	// LatestVersion: When `upgrade_available` is `true`, the higher system-scope `solution_version` available to upgrade to. `null` otherwise.
	LatestVersion *string `json:"latest_version,omitempty"`
	// LookupKey: The lookup key stored on the Solution config, if one was assigned during import. `null` when no lookup key was set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Metadata: Arbitrary key-value metadata declared in the Solution body (e.g. category or display hints). Present as an empty object when the body declares none.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Human-facing display name declared in the Solution body. `null` when the Solution body does not set one.
	Name *string `json:"name,omitempty"`
	// Org: Organization ID (`org_...`) that owns this Solution config, when the Solution is scoped to a specific org. `null` for system-scope (app-level) Solutions.
	Org *string `json:"org,omitempty"`
	// OrgLogo: Canonical image-source object for the resolved `org`'s logo, used as the principal category section glyph. The `url` is a stable, non-expiring capability URL (`refresh_url` is `null` there is nothing to refresh). `null` when `org_slug` is `null` or the org has no logo.
	OrgLogo *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionOrgLogo `json:"org_logo,omitempty"`
	// OrgName: Display name of the resolved `org`. Pairs with `org_slug` as the principal catalog category's label. `null` when `org_slug` is `null`.
	OrgName *string `json:"org_name,omitempty"`
	// OrgSlug: Resolved slug of the Solution body's `org` (the publishing organization), when set and it resolves to a real org visible to the viewer. When present this is the Solution's principal catalog category key clients group the Solution under this org ahead of `category_keys`. `null` when the body has no `org` or it doesn't resolve.
	OrgSlug *string `json:"org_slug,omitempty"`
	// Owners: Owner scopes this Solution appears under. Members: `"system"` (app-level system scope) and/or `"org"` (viewer's org scope).
	Owners []string `json:"owners"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded. `null` when the Solution has no README. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// ScreenshotUrls: Absolute URLs of the Solution's gallery screenshots the bundled assets the body's `screenshots:` field names, in declared order. Each is a stable, non-expiring capability URL with the same cacheability contract as `image_url` (one shared token, a `v` cache key, and a `file` param selecting the screenshot); a URL 404s if the Solution stops declaring its screenshot. An empty array when the Solution declares none, and always empty for org-scoped rows the permanent URLs are minted for system-scope (catalog) Solutions only.
	ScreenshotUrls []string `json:"screenshot_urls,omitempty"`
	// SolutionID: Stable UUID declared in the Solution body, used to identify the same logical Solution across multiple installed copies and owner scopes. `null` when the body omits it.
	SolutionID *string `json:"solution_id,omitempty"`
	// SolutionVersion: Semver string declared in the Solution body (e.g. `"1.2.0"`). `null` when the body does not declare a version.
	SolutionVersion *string `json:"solution_version,omitempty"`
	// TagKeys: Freeform tag keys declared in the Solution body. An empty array when the body declares none.
	TagKeys []string `json:"tag_keys,omitempty"`
	// TemplateKind: Wrapped template kind `"AgentTemplate"`, `"AutomationTemplate"`, `"AgentRoutineTemplate"`, `"AgentToolTemplate"`, `"AgentComputerTemplate"`, or `"SolutionTemplateRef"` for ref-mode bundles.
	TemplateKind *string `json:"template_kind,omitempty"`
	// Templates: Template configs bundled by this Solution, in declaration order the first entry is the deployable template the Solution wraps; the rest are sibling templates the wrapped template references.
	Templates []OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolutionTemplatesItem `json:"templates"`
	// UpdatedAt: When the Solution config was last modified (ISO 8601).
	UpdatedAt *string `json:"updated_at,omitempty"`
	// UpgradeAvailable: `true` when this Solution is installed at the viewer's org scope and the app-level system scope carries a higher `solution_version`. Always `false` for system-only rows.
	UpgradeAvailable bool `json:"upgrade_available"`
	// VirtualPath: The stable virtual path assigned to this Solution config, used as the deduplication key when the same Solution appears under multiple owner scopes. `null` when unset.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionOrgLogo struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContractParticipantsItem struct {
	// Description: Workflow-authored explanation of the slot's role. `null` when the workflow declares none.
	Description *string `json:"description,omitempty"`
	// Name: The slot's name, as referenced by the workflow. Supply the chosen agent under the top-level `participants[name]` field when invoking.
	Name string `json:"name"`
	// Required: Whether the workflow requires this slot to be filled for the run to complete its embedded stages.
	Required bool `json:"required"`
	// Type: The kind of principal the slot accepts. Currently always `"agent_user"` the value supplied at invoke is an agent ID (`agi_...`).
	Type string `json:"type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContractPrefills struct {
	// Participants: Participant slot-to-agent mappings applied by the platform. Caller values at these slots must match exactly.
	Participants map[string]JSONValue `json:"participants,omitempty"`
	// Payload: Partial invocation payload applied by the platform. A caller may omit these values, but supplying a different value at any locked path is rejected.
	Payload map[string]JSONValue `json:"payload,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContract struct {
	// InputSchema: JSON Schema validated against the whole invoke payload, from the automation's `input_schema_config`. `null` when none is configured.
	InputSchema map[string]JSONValue `json:"input_schema,omitempty"`
	// Participants: Named participant slots declared by the workflow, sorted by name. `null` when the workflow declares none. Values supplied under the top-level `participants` field are agent IDs.
	Participants []OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContractParticipantsItem `json:"participants,omitempty"`
	// Prefills: Owner-controlled payload and participant values the platform applies to every invocation. Supplying a conflicting value is rejected.
	Prefills *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContractPrefills `json:"prefills"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetails struct {
	// AutomationType: Automation execution type (`invoked`, `scheduled`, or `trigger`). `null` when the template body does not declare one.
	AutomationType *string `json:"automation_type,omitempty"`
	// InvokeContract: Schema-driven payload and participant inputs for an invoked automation. Used by installation clients to collect locked prefills before provisioning. `null` for non-invoked automation types.
	InvokeContract *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetailsInvokeContract `json:"invoke_contract,omitempty"`
	// Type: Template-details discriminator. Always `automation` for this variant.
	Type string `json:"type"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItem struct {
	// Description: Short prose blurb from the template body's `description:` field. `null` when the body doesn't set one. Used as the card subhead in the Library carousel.
	Description *string `json:"description,omitempty"`
	// Details: Template-kind-specific details selected by the `type` discriminator. `null` when this template kind has no additional details.
	Details *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItemDetails `json:"details,omitempty"`
	// DisplayName: Human-facing label from the template body's `display_name:` field. `null` when the body doesn't set one. Library carousels use this for the card title, falling back to a humanized `name`.
	DisplayName *string `json:"display_name,omitempty"`
	// ID: Template config ID (`cfg_...`). `null` for inline-only templates.
	ID *string `json:"id,omitempty"`
	// Kind: Template config kind, or `SolutionTemplateRef` / `SolutionTemplatePath` when unresolved.
	Kind string `json:"kind"`
	// LookupKey: Lookup key stamped on the template config at import time. `null` when no lookup key was assigned.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Name: Canonical name from the template body. For `AgentTemplate` this doubles as the human-facing label; for `AgentToolTemplate` it's the LLM-facing tool function identifier (snake_case); for `AgentRoutineTemplate` it's the routine identifier (kebab-case). Clients rendering carousels should prefer `display_name` and fall back to humanizing `name`.
	Name *string `json:"name,omitempty"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded, scoped to this template's bundled markdown asset. `null` when the Solution body's `templates[].readme_path` is unset for this entry. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// VirtualPath: Stable virtual path assigned to the template config. `null` when no virtual path was set.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolution struct {
	// CategoryKeys: Category tag keys declared in the Solution body, used to group Solutions in the catalog. An empty array when the body declares none.
	CategoryKeys []string `json:"category_keys,omitempty"`
	// CreatedAt: When the Solution config was first imported (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// Description: Short tagline or summary declared in the Solution body, used as the card subhead in catalog UIs. `null` when the Solution body does not set one.
	Description *string `json:"description,omitempty"`
	// Events: Custom analytics events declared in the Solution body's `events:` manifest a map of event key (snake_case) to its definition (`label`, optional `description`, optional typed `fields`). Dashboards use the `label` as the event's display name. Present as an empty object when the body declares none.
	Events map[string]JSONValue `json:"events,omitempty"`
	// ID: Solution config ID (`cfg_...`).
	ID string `json:"id"`
	// ImageURL: Absolute URL of the Solution's cover image the bundled asset the body's `image:` field names. A stable, non-expiring capability URL (like `org_logo.url`), safe to hold in caches and OpenGraph tags; it 404s if the Solution stops declaring a cover. `null` when the Solution has no cover image. Org-only rows remain `null`; when a list entry merges an org copy with its system counterpart, it may reuse the system row's public cover URL. Permanent URLs are never minted for private org assets.
	ImageURL *string `json:"image_url,omitempty"`
	// InstalledConfigIds: Config IDs (`cfg_...`) of this Solution's installations in the viewer's organization. The array is empty when the Solution is visible only from the system catalog.
	InstalledConfigIds []string `json:"installed_config_ids"`
	// Kind: Resource type. Always `"Solution"`.
	Kind string `json:"kind"`
	// LatestSolution: When `upgrade_available` is `true`, the system-scope Solution config ID (`cfg_...`) that should be used as the upgrade source. `null` otherwise.
	LatestSolution *string `json:"latest_solution,omitempty"`
	// LatestVersion: When `upgrade_available` is `true`, the higher system-scope `solution_version` available to upgrade to. `null` otherwise.
	LatestVersion *string `json:"latest_version,omitempty"`
	// LookupKey: The lookup key stored on the Solution config, if one was assigned during import. `null` when no lookup key was set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Metadata: Arbitrary key-value metadata declared in the Solution body (e.g. category or display hints). Present as an empty object when the body declares none.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Human-facing display name declared in the Solution body. `null` when the Solution body does not set one.
	Name *string `json:"name,omitempty"`
	// Org: Organization ID (`org_...`) that owns this Solution config, when the Solution is scoped to a specific org. `null` for system-scope (app-level) Solutions.
	Org *string `json:"org,omitempty"`
	// OrgLogo: Canonical image-source object for the resolved `org`'s logo, used as the principal category section glyph. The `url` is a stable, non-expiring capability URL (`refresh_url` is `null` there is nothing to refresh). `null` when `org_slug` is `null` or the org has no logo.
	OrgLogo *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionOrgLogo `json:"org_logo,omitempty"`
	// OrgName: Display name of the resolved `org`. Pairs with `org_slug` as the principal catalog category's label. `null` when `org_slug` is `null`.
	OrgName *string `json:"org_name,omitempty"`
	// OrgSlug: Resolved slug of the Solution body's `org` (the publishing organization), when set and it resolves to a real org visible to the viewer. When present this is the Solution's principal catalog category key clients group the Solution under this org ahead of `category_keys`. `null` when the body has no `org` or it doesn't resolve.
	OrgSlug *string `json:"org_slug,omitempty"`
	// Owners: Owner scopes this Solution appears under. Members: `"system"` (app-level system scope) and/or `"org"` (viewer's org scope).
	Owners []string `json:"owners"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded. `null` when the Solution has no README. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// ScreenshotUrls: Absolute URLs of the Solution's gallery screenshots the bundled assets the body's `screenshots:` field names, in declared order. Each is a stable, non-expiring capability URL with the same cacheability contract as `image_url` (one shared token, a `v` cache key, and a `file` param selecting the screenshot); a URL 404s if the Solution stops declaring its screenshot. An empty array when the Solution declares none, and always empty for org-scoped rows the permanent URLs are minted for system-scope (catalog) Solutions only.
	ScreenshotUrls []string `json:"screenshot_urls,omitempty"`
	// SolutionID: Stable UUID declared in the Solution body, used to identify the same logical Solution across multiple installed copies and owner scopes. `null` when the body omits it.
	SolutionID *string `json:"solution_id,omitempty"`
	// SolutionVersion: Semver string declared in the Solution body (e.g. `"1.2.0"`). `null` when the body does not declare a version.
	SolutionVersion *string `json:"solution_version,omitempty"`
	// TagKeys: Freeform tag keys declared in the Solution body. An empty array when the body declares none.
	TagKeys []string `json:"tag_keys,omitempty"`
	// TemplateKind: Wrapped template kind `"AgentTemplate"`, `"AutomationTemplate"`, `"AgentRoutineTemplate"`, `"AgentToolTemplate"`, `"AgentComputerTemplate"`, or `"SolutionTemplateRef"` for ref-mode bundles.
	TemplateKind *string `json:"template_kind,omitempty"`
	// Templates: Template configs bundled by this Solution, in declaration order the first entry is the deployable template the Solution wraps; the rest are sibling templates the wrapped template references.
	Templates []OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItem `json:"templates"`
	// UpdatedAt: When the Solution config was last modified (ISO 8601).
	UpdatedAt *string `json:"updated_at,omitempty"`
	// UpgradeAvailable: `true` when this Solution is installed at the viewer's org scope and the app-level system scope carries a higher `solution_version`. Always `false` for system-only rows.
	UpgradeAvailable bool `json:"upgrade_available"`
	// VirtualPath: The stable virtual path assigned to this Solution config, used as the deduplication key when the same Solution appears under multiple owner scopes. `null` when unset.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionTemplate struct {
	// CreatedAt: When this template config was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Description: Description of the template from the config body. `null` if the current version has no `description` field.
	Description *string `json:"description,omitempty"`
	// DisplayName: Human-readable display name from the config body. `null` if the current version has no `display_name` field.
	DisplayName *string `json:"display_name,omitempty"`
	// ID: Template config ID (`cfg_...`).
	ID string `json:"id"`
	// Kind: Config kind identifier for this template (e.g. `"agent_tool_template"`).
	Kind string `json:"kind"`
	// LookupKey: Stable lookup key assigned to this template config. `null` if no lookup key is set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Name: Template name as stored in the config body. `null` if the current version has no `name` field.
	Name *string `json:"name,omitempty"`
	// UpdatedAt: When this template config was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// VirtualPath: Virtual filesystem path for this template config. `null` if not set.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolution struct {
	// CurrentSolution: Summary of the current parent Solution config row. `solution` is the pinned Solution version the agent points at; `current_solution` is the source Solution config row as it exists now.
	CurrentSolution *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionCurrentSolution `json:"current_solution,omitempty"`
	// Solution: Summary of the parent Solution, including `upgrade_available`, `latest_version`, and `latest_solution` when a newer system-scoped version is available for the agent's org-scoped Solution.
	Solution *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolution `json:"solution"`
	// Template: Summary of the AgentTemplate config (`cfg_...`) the agent was last provisioned or updated from.
	Template *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolutionTemplate `json:"template"`
}

type OrgThreadListResponseDataItemParticipatingAgentsItem struct {
	// ACL: Access control list for the agent. Contains a `grants` array where each entry specifies `principal_type`, `principal`, and `actions`. `null` when no ACL restrictions are applied and the agent is accessible to all members of its scope.
	ACL *OrgThreadListResponseDataItemParticipatingAgentsItemAcl `json:"acl,omitempty"`
	// App: ID of the application that owns this agent (`dap_...`).
	App *string `json:"app,omitempty"`
	// CreatedAt: When the agent was created (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// DefaultModel: Default LLM model identifier used by this agent when no model is specified at runtime (e.g. `"claude-3-7-sonnet-latest"`).
	DefaultModel *string `json:"default_model,omitempty"`
	// Description: Human-readable description of what the agent does. `null` if not set.
	Description *string `json:"description,omitempty"`
	// Email: Email address provisioned for this agent. `null` if email delivery is not configured.
	Email *string `json:"email,omitempty"`
	// ID: Agent ID (`agi_...`).
	ID string `json:"id"`
	// Identity: System-level identity prompt that shapes the agent's persona and behavior.
	Identity *string `json:"identity,omitempty"`
	// LastAppliedTemplateConfig: ID of the AgentTemplate config (`cfg_...`) this agent was last provisioned or updated from. `null` for manually created agents.
	LastAppliedTemplateConfig *string `json:"last_applied_template_config,omitempty"`
	// LookupKey: Stable, user-defined identifier for this agent within the application. Unique per app.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the agent. Not interpreted by the platform.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Human-readable display name for the agent. `null` if not set.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this agent belongs to (`org_...`). `null` if the agent is not org-scoped.
	Org *string `json:"org,omitempty"`
	// OrgName: Display name of the organization this agent belongs to. `null` when the agent is not org-scoped or when the org association was not preloaded.
	OrgName *string `json:"org_name,omitempty"`
	// Originator: Free-form label identifying the source or author that created this agent (e.g. a username or pipeline name).
	Originator *string `json:"originator,omitempty"`
	// PhoneNumber: Phone number provisioned for this agent. `null` if SMS is not configured.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Sandbox: ID of the sandbox environment this agent is scoped to (`dsb_...`). `null` in production deployments.
	Sandbox *string `json:"sandbox,omitempty"`
	// SourceSolution: Source Solution and AgentTemplate summary for agents provisioned from a Solution. Includes `upgrade_available`, `latest_version`, and `latest_solution` so you can render an upgrade badge without a separate dry-run call. `null` for hand-built agents and agents whose tracked template or parent Solution has been deleted. Populated only on single-agent GET responses, never on list endpoints.
	SourceSolution *OrgThreadListResponseDataItemParticipatingAgentsItemSourceSolution `json:"source_solution,omitempty"`
	// Team: ID of the team that owns this agent (`tem_...`). `null` if the agent is not team-scoped.
	Team *string `json:"team,omitempty"`
	// TemplateUpgradeAvailable: True when the agent's last-applied template version is behind the current version of its AgentTemplate config i.e. reapplying the template (a per-agent upgrade) would bring it newer Solution content. Self-clears once the agent is reapplied. Computed on both the list endpoints and single-agent GET. Distinct from `source_solution.upgrade_available`, which compares Solution *versions*: an agent can lag its template (`template_upgrade_available: true`) while the org already holds the latest Solution version (`upgrade_available: false`).
	TemplateUpgradeAvailable *bool `json:"template_upgrade_available,omitempty"`
	// UpdatedAt: When the agent was last modified (ISO 8601).
	UpdatedAt *string `json:"updated_at,omitempty"`
	// User: ID of the user that owns this agent (`usr_...`). `null` if the agent is not user-scoped.
	User *string `json:"user,omitempty"`
}

type OrgThreadListResponseDataItemSettings struct {
	// AgentEnabled: Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured. `null` when a client explicitly cleared the setting.
	AgentEnabled *bool `json:"agent_enabled,omitempty"`
}

type OrgThreadListResponseDataItem struct {
	// AgentUser: ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads.
	AgentUser *string `json:"agent_user,omitempty"`
	// CreatedAt: When the thread was created (ISO 8601).
	CreatedAt *string `json:"created_at,omitempty"`
	// Creator: User who created this thread. Returns a user ID (`usr_...`) by default, or an expanded user object when the association is loaded. `null` if the creator is unknown.
	Creator *JSONValue `json:"creator,omitempty"`
	// Description: Optional description or purpose statement for the thread. `null` if not set.
	Description *string `json:"description,omitempty"`
	// ID: Thread ID (`thr_...`).
	ID string `json:"id"`
	// IsChannel: Whether this thread operates as a channel a multi-member broadcast-style conversation.
	IsChannel *bool `json:"is_channel,omitempty"`
	// IsDefault: Whether this is the default thread for its owner. Each user or team has at most one default thread.
	IsDefault *bool `json:"is_default,omitempty"`
	// IsTransient: Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires.
	IsTransient *bool `json:"is_transient,omitempty"`
	// IsUnlisted: Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants.
	IsUnlisted *bool `json:"is_unlisted,omitempty"`
	// Key: Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set.
	Key *string `json:"key,omitempty"`
	// Kind: Thread subtype: `"standard"` for ordinary threads, `"personal"` for a user-and-owned-agents roster, `"feed"` for a post feed with inline replies, `"slack_mirror"` for the membership-strict mirror of a Slack channel, or `"slashwork_mirror"` for the membership-strict mirror of a Slashwork group. `personal` and `feed` are explicit creation options; mirror kinds are server-derived.
	Kind *string `json:"kind,omitempty"`
	// LastActivity: When the most recent message was posted in this thread, falling back to the thread's creation time if it has no messages. Always populated on thread list endpoints (which order by it, after default threads); `null` on endpoints that don't compute activity enrichment.
	LastActivity *string `json:"last_activity,omitempty"`
	// LastMessagePreview: Single-line snippet of the most recent message's text content (first non-empty line, truncated to 140 characters). Populated on thread list endpoints alongside `last_activity`; `null` when the thread has no messages, the latest message has no text content (e.g. attachment-only), or the endpoint doesn't compute activity enrichment.
	LastMessagePreview *string `json:"last_message_preview,omitempty"`
	// LastMessageSender: Display name of the sender of the most recent message the same message `last_message_preview` snippets. Populated on thread list endpoints; `null` when the thread has no messages or the endpoint doesn't compute activity enrichment.
	LastMessageSender *string `json:"last_message_sender,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Muted: Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery.
	Muted *bool `json:"muted,omitempty"`
	// Org: ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context.
	Org *string `json:"org,omitempty"`
	// ParentMessage: The message that spawned this thread as a sub-thread. `null` for top-level threads.
	ParentMessage *OrgThreadListResponseDataItemParentMessage `json:"parent_message,omitempty"`
	// Participant: Array of participant user IDs (`usr_...`) who are members of this thread.
	Participant []string `json:"participant,omitempty"`
	// Participants: Expanded participant user objects for each member of this thread. Populated only when the association is loaded.
	Participants []OrgThreadListResponseDataItemParticipantsItem `json:"participants,omitempty"`
	// ParticipatingActor: Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested.
	ParticipatingActor []string `json:"participating_actor,omitempty"`
	// ParticipatingAgents: Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested.
	ParticipatingAgents []OrgThreadListResponseDataItemParticipatingAgentsItem `json:"participating_agents,omitempty"`
	// Role: The authenticated user's membership role in this thread, e.g. `"owner"`, `"member"`, or `"viewer"`. `null` if the user is not a member.
	Role *string `json:"role,omitempty"`
	// Sandbox: ID of the developer sandbox this thread is scoped to (`dsb_...`). `null` for production threads.
	Sandbox *string `json:"sandbox,omitempty"`
	// Settings: Per-thread configuration settings controlling AI agent behavior for this thread.
	Settings *OrgThreadListResponseDataItemSettings `json:"settings,omitempty"`
	// Slug: URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned.
	Slug *string `json:"slug,omitempty"`
	// SubThreads: Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested.
	SubThreads []map[string]JSONValue `json:"sub_threads,omitempty"`
	// Tags: Status tags on the thread (e.g. `"blocked"`, `"needs-review"`). Edited by any thread participant via the `/threads/:thread/tags` endpoints and filterable on the thread list endpoints. Empty array if none set.
	Tags []string `json:"tags,omitempty"`
	// Team: ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads.
	Team *string `json:"team,omitempty"`
	// Title: Human-readable name of the thread. `null` if no title has been set.
	Title *string `json:"title,omitempty"`
	// TTL: Offset-free expiry timestamp after which the thread may be automatically cleaned up. `null` if the thread does not expire.
	TTL *string `json:"ttl,omitempty"`
	// UnreadCount: Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested.
	UnreadCount *int `json:"unread_count,omitempty"`
	// UpdatedAt: When the thread was last modified (ISO 8601).
	UpdatedAt *string `json:"updated_at,omitempty"`
	// User: ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads.
	User *string `json:"user,omitempty"`
	// Visibility: Who can read the thread: `team` for every owning-team member, `restricted` for team-readable threads with an explicit roster, `private` for roster-only access, or `org` for every member of the owning organization.
	Visibility string `json:"visibility"`
}

// OrgThreadListResponse: Successful response
type OrgThreadListResponse struct {
	// Data: Array of org-visibility thread objects.
	Data []OrgThreadListResponseDataItem `json:"data"`
}

type OrgListResponseDataItem struct {
	// Domain: Company domain. For personal orgs, the owner email is returned only to a viewer in that org.
	Domain *string `json:"domain,omitempty"`
	// ID: Organization ID (`org_...`).
	ID string `json:"id"`
	// Kind: Whether this is a company-domain org or a person-owned personal org.
	Kind string `json:"kind"`
	// Name: Display name of the organization.
	Name string `json:"name"`
}

// OrgListResponse: Successful response
type OrgListResponse struct {
	// Data: Array of organization objects for the current page.
	Data []OrgListResponseDataItem `json:"data"`
	// HasNext: `true` when a subsequent page exists; `false` on the last page.
	HasNext *bool `json:"has_next,omitempty"`
	// HasPrev: `true` when a previous page exists; `false` on the first page.
	HasPrev *bool `json:"has_prev,omitempty"`
	// Page: The current page number returned.
	Page *int `json:"page,omitempty"`
	// PageSize: The number of results per page used for this response.
	PageSize *int `json:"page_size,omitempty"`
	// TotalEntries: Total number of organizations matching the query across all pages.
	TotalEntries *int `json:"total_entries,omitempty"`
	// TotalPages: Total number of pages for the current query and page size.
	TotalPages *int `json:"total_pages,omitempty"`
}

type OrgArtifactsResponseDataItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type OrgArtifactsResponseDataItem struct {
	// Agent: ID of the agent that produced this artifact (`agt_...`). `null` if not agent-produced.
	Agent *string `json:"agent,omitempty"`
	// ContentType: MIME type of the current version's file, e.g. `"text/csv"` or `"image/png"`. `null` if no file is attached.
	ContentType *string `json:"content_type,omitempty"`
	// CreatedAt: When the artifact was first created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// CurrentVersion: ID of the current (latest published) artifact version (`artv_...`). `null` if no version has been published.
	CurrentVersion *string `json:"current_version,omitempty"`
	// Description: Optional longer description of the artifact's contents or purpose. `null` if not set.
	Description *string `json:"description,omitempty"`
	// File: Storage file ID for the current version (`fil_...`). `null` if no file is attached.
	File *string `json:"file,omitempty"`
	// FileName: Original filename of the current version's file, e.g. `"output.csv"`. `null` if no file is attached.
	FileName *string `json:"file_name,omitempty"`
	// FileURL: Short-lived signed URL for downloading the current version's file. `null` if no file is attached.
	FileURL *string `json:"file_url,omitempty"`
	// GroupKey: Optional nonunique, case-sensitive grouping key, limited to 1024 UTF-8 bytes. Null when unset; belongs to the artifact, not a content version.
	GroupKey *string `json:"group_key,omitempty"`
	// ID: Artifact ID (`art_...`).
	ID string `json:"id"`
	// ImageSource: Image source metadata for rendering the current version's file inline. Present only when `content_type` starts with `"image/"`. `null` otherwise.
	ImageSource *OrgArtifactsResponseDataItemImageSource `json:"image_source,omitempty"`
	// Name: Human-readable name for the artifact, e.g. `"Q2 Report"`. `null` if not set.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this artifact belongs to (`org_...`).
	Org *string `json:"org,omitempty"`
	// Sandbox: Identifier of the sandbox environment associated with this artifact. `null` if not sandbox-scoped.
	Sandbox *string `json:"sandbox,omitempty"`
	// System: True when the artifact has no user, team, or agent owner. An organization may own a system artifact.
	System *bool `json:"system,omitempty"`
	// Team: ID of the team that owns this artifact (`tea_...`). `null` if not team-scoped.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the thread in which this artifact was created (`thr_...`). `null` if not thread-scoped.
	Thread *string `json:"thread,omitempty"`
	// UpdatedAt: When the artifact record was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user who created this artifact (`usr_...`). `null` if not user-scoped.
	User *string `json:"user,omitempty"`
	// Version: Current version number of the artifact. Increments each time a new version is published.
	Version *int `json:"version,omitempty"`
}

// OrgArtifactsResponse: Successful response
type OrgArtifactsResponse struct {
	AfterCursor *string `json:"after_cursor,omitempty"`
	// BeforeCursor: Always null; pagination is forward-only.
	BeforeCursor *string                        `json:"before_cursor,omitempty"`
	Data         []OrgArtifactsResponseDataItem `json:"data"`
	HasMore      bool                           `json:"has_more"`
}

type OrgLinkedAccountsResponseDataItem struct {
	// AccountID: The service's name for the account: the login, for GitHub.
	AccountID string `json:"account_id"`
	// Provider: Service the account is on. Currently always `"github"`.
	Provider string `json:"provider"`
	// User: User ID (`usr_...`) the account belongs to.
	User string `json:"user"`
}

// OrgLinkedAccountsResponse: Successful response
type OrgLinkedAccountsResponse struct {
	AfterCursor *string `json:"after_cursor,omitempty"`
	// BeforeCursor: Always null; pagination is forward-only.
	BeforeCursor *string `json:"before_cursor,omitempty"`
	// Data: Linked accounts, by user.
	Data    []OrgLinkedAccountsResponseDataItem `json:"data"`
	HasMore bool                                `json:"has_more"`
}

// OrgThreadListParams: query parameters for OrgThreadResource.List.
type OrgThreadListParams struct {
	// Key: Optional exact thread key, for example `archdev-room`.
	Key *string
}

// OrgListParams: query parameters for OrgResource.List.
type OrgListParams struct {
	// Search: Free-text search term matched against organization name, slug, and domain (case-insensitive). Omit to return all organizations in the app.
	Search *string
	// Page: Page number to retrieve, starting at `1`. Defaults to `1` when omitted.
	Page *int
	// PageSize: Number of organizations to return per page. Defaults to `25`; maximum is `100`.
	PageSize *int
}

// OrgArtifactsParams: query parameters for OrgResource.Artifacts.
type OrgArtifactsParams struct {
	// Limit: Maximum snapshots returned, from 1 to 100.
	Limit *int
	// AfterCursor: Opaque cursor for the next page of older snapshots.
	AfterCursor *string
	// GroupKey: Exact, case-sensitive grouping key.
	GroupKey *string
	// GroupKeyPrefix: Nonempty literal group prefix; mutually exclusive with group_key.
	GroupKeyPrefix *string
}

// OrgLinkedAccountsParams: query parameters for OrgResource.LinkedAccounts.
type OrgLinkedAccountsParams struct {
	// User: Up to 100 user IDs (`usr_...`) to look up. Omit to list every user in the organization. Users in the list who are outside the organization or have no linked account are absent.
	User []string
	// Limit: Maximum accounts returned, from 1 to 100.
	Limit *int
	// AfterCursor: Opaque cursor for the next page.
	AfterCursor *string
}

type OrgThreadResource struct {
	http *HTTPClient
}

func newOrgThreadResource(h *HTTPClient) *OrgThreadResource {
	return &OrgThreadResource{
		http: h,
	}
}

// List: List organization-visibility threads
//
// Returns org-visibility threads for the specified organization. Every member
// of the organization can list these threads; they require no team membership.
// App-scoped developer tokens for the organization's app can list them too.
//
// org: Organization ID (`org_...`) whose org-visibility threads should be listed.
//
// Returns: Successful response
func (r *OrgThreadResource) List(ctx context.Context, org string, params OrgThreadListParams) (*OrgThreadListResponse, error) {
	q := url.Values{}
	if params.Key != nil {
		q.Add("key", *params.Key)
	}
	return fetch[*OrgThreadListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/orgs/" + url.PathEscape(org) + "/threads", Query: q})
}

// Create: Create an organization-visibility thread
//
// Creates a thread owned by the organization rather than a team, user, or agent.
// Every member of the organization can read and post without joining. The
// authenticated caller must be an organization administrator, or use an
// app-scoped developer token for the organization's app.
// When `thread.key` is supplied, creation is idempotent: a second call with the
// same key returns the existing org-visibility thread instead of inserting a
// duplicate.
//
// org: Organization ID (`org_...`) whose org-visibility threads should be listed.
//
// Returns: The organization-visibility thread.
func (r *OrgThreadResource) Create(ctx context.Context, org string, input OrgThreadCreateInput) (*Thread, error) {
	return fetch[*Thread](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/orgs/" + url.PathEscape(org) + "/threads", Body: input})
}

type OrgResource struct {
	http    *HTTPClient
	Threads *OrgThreadResource
}

func newOrgResource(h *HTTPClient) *OrgResource {
	return &OrgResource{
		http:    h,
		Threads: newOrgThreadResource(h),
	}
}

// List: Search organizations
//
// Returns a paginated list of organizations within the authenticated app scope,
// optionally filtered by a free-text search term matched against name, slug, and
// domain (case-insensitive). Results are ordered by relevance when a search term
// is provided, and by creation time descending otherwise.
// The response includes only public-facing organization fields: ID, name, domain,
// and logo. Use the developer-scoped org endpoints to access full organization
// records.
// Pagination is offset-based. Pass `page` and `page_size` to navigate through
// results. The `has_next` and `has_prev` fields indicate whether adjacent pages
// exist.
//
// Returns: Successful response
func (r *OrgResource) List(ctx context.Context, params OrgListParams) (*OrgListResponse, error) {
	q := url.Values{}
	if params.Search != nil {
		q.Add("search", *params.Search)
	}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	return fetch[*OrgListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/orgs", Query: q})
}

// Artifacts: List completed organization artifacts
//
// Returns completed system-owned organization snapshots, newest first. Private user, team, agent and thread artifacts are excluded.
//
// org: Organization ID.
//
// Returns: Successful response
func (r *OrgResource) Artifacts(ctx context.Context, org string, params OrgArtifactsParams) (*OrgArtifactsResponse, error) {
	q := url.Values{}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	if params.GroupKey != nil {
		q.Add("group_key", *params.GroupKey)
	}
	if params.GroupKeyPrefix != nil {
		q.Add("group_key_prefix", *params.GroupKeyPrefix)
	}
	return fetch[*OrgArtifactsResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/orgs/" + url.PathEscape(org) + "/artifacts", Query: q})
}

// LinkedAccounts: List an organization's linked accounts
//
// Returns the GitHub login each user in the organization signed in with, so
// clients can tell that a pull request's author and a Platform user are the
// same person. Users who never signed in with GitHub are absent. Any viewer
// acting within the organization can list them; other viewers get 404.
// Pass `user` to look up specific users instead of listing the whole
// organization. Results are ordered by user and paginated forward with
// `after_cursor`.
//
// org: Organization ID (`org_...`) whose linked accounts should be listed.
//
// Returns: Successful response
func (r *OrgResource) LinkedAccounts(ctx context.Context, org string, params OrgLinkedAccountsParams) (*OrgLinkedAccountsResponse, error) {
	q := url.Values{}
	for _, item := range params.User {
		q.Add("user", item)
	}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	return fetch[*OrgLinkedAccountsResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/orgs/" + url.PathEscape(org) + "/linked_accounts", Query: q})
}
