// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 46b770bde82c

package platform

import (
	"context"
	"net/url"
)

type PrivateServiceDefinitionResource struct {
	http *HTTPClient
}

func newPrivateServiceDefinitionResource(h *HTTPClient) *PrivateServiceDefinitionResource {
	return &PrivateServiceDefinitionResource{
		http: h,
	}
}

// Get: Download an enrolled private service definition
//
// Returns the canonical callable definition authorized by an enrollment token.
//
// Returns: Raw content
func (r *PrivateServiceDefinitionResource) Get(ctx context.Context, appID string, privateServiceID string) (*RawResponse, error) {
	return r.http.requestRaw(ctx, requestSpec{Method: "GET", Path: "/api/v1/private_service_definitions/" + url.PathEscape(appID) + "/" + url.PathEscape(privateServiceID)})
}
