// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 75ae55c252c7

package platform

import (
	"context"
	"net/url"
)

// PrivateServiceEnrollmentCreateInput: Create a private service enrollment
type PrivateServiceEnrollmentCreateInput struct {
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string `json:"org,omitempty"`
	// PrivateService: Private service ID (`pvs_...`).
	PrivateService string `json:"private_service"`
}

// PrivateServiceEnrollmentListParams: query parameters for PrivateServiceEnrollmentResource.List.
type PrivateServiceEnrollmentListParams struct {
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string
	// Page: Page number. Defaults to 1.
	Page *int
	// PageSize: Results per page. Defaults to 25; maximum is 100.
	PageSize *int
}

// PrivateServiceEnrollmentGetParams: query parameters for PrivateServiceEnrollmentResource.Get.
type PrivateServiceEnrollmentGetParams struct {
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string
}

type PrivateServiceEnrollmentResource struct {
	http *HTTPClient
}

func newPrivateServiceEnrollmentResource(h *HTTPClient) *PrivateServiceEnrollmentResource {
	return &PrivateServiceEnrollmentResource{
		http: h,
	}
}

// List: List private service enrollments
//
// Returns: Successful response
func (r *PrivateServiceEnrollmentResource) List(ctx context.Context, params PrivateServiceEnrollmentListParams) (*PrivateServiceEnrollmentPage, error) {
	q := url.Values{}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	return fetch[*PrivateServiceEnrollmentPage](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/private_service_enrollments", Query: q})
}

// Create: Create a private service enrollment
//
// Creates or safely replaces an unreserved one-time connector enrollment token.
//
// Returns: Successful response
func (r *PrivateServiceEnrollmentResource) Create(ctx context.Context, input PrivateServiceEnrollmentCreateInput) (*CreatedPrivateServiceEnrollment, error) {
	return fetch[*CreatedPrivateServiceEnrollment](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/private_service_enrollments", Body: input})
}

// Get: Retrieve a private service enrollment
//
// privateServiceEnrollmentID: Canonical certificate-bound service identity.
//
// Returns: Successful response
func (r *PrivateServiceEnrollmentResource) Get(ctx context.Context, privateServiceEnrollmentID string, params PrivateServiceEnrollmentGetParams) (*PrivateServiceEnrollment, error) {
	q := url.Values{}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	return fetch[*PrivateServiceEnrollment](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/private_service_enrollments/" + url.PathEscape(privateServiceEnrollmentID), Query: q})
}
