// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2f2044744966

package platform

import (
	"context"
	"net/url"
)

type PrivateServiceCreateInputFunctionsItem struct {
	// Description: Human-readable guidance describing when and why to call the operation.
	Description string `json:"description"`
	// InputSchema: JSON Schema Draft 7 object describing the operation's argument object.
	InputSchema map[string]JSONValue `json:"input_schema"`
	// Name: Stable operation name used when invoking the private service.
	Name string `json:"name"`
	// OutputSchema: Optional JSON Schema Draft 7 object describing the successful result.
	OutputSchema map[string]JSONValue `json:"output_schema,omitempty"`
}

// PrivateServiceCreateInput: Create a private service
type PrivateServiceCreateInput struct {
	// Functions: Complete callable contracts. Input schemas are required; output schemas are optional.
	Functions []PrivateServiceCreateInputFunctionsItem `json:"functions"`
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string `json:"org,omitempty"`
}

// PrivateServiceListParams: query parameters for PrivateServiceResource.List.
type PrivateServiceListParams struct {
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string
	// Page: Page number. Defaults to 1.
	Page *int
	// PageSize: Results per page. Defaults to 25; maximum is 100.
	PageSize *int
}

// PrivateServiceGetParams: query parameters for PrivateServiceResource.Get.
type PrivateServiceGetParams struct {
	// Org: Organization ID or slug. Required for developer and server callers.
	Org *string
}

type PrivateServiceResource struct {
	http *HTTPClient
}

func newPrivateServiceResource(h *HTTPClient) *PrivateServiceResource {
	return &PrivateServiceResource{
		http: h,
	}
}

// List: List private services
//
// Returns: Successful response
func (r *PrivateServiceResource) List(ctx context.Context, params PrivateServiceListParams) (*PrivateServicePage, error) {
	q := url.Values{}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	return fetch[*PrivateServicePage](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/private_services", Query: q})
}

// Create: Create a private service
//
// Creates one immutable private service in the selected organization.
//
// Returns: The newly created private service.
func (r *PrivateServiceResource) Create(ctx context.Context, input PrivateServiceCreateInput) (*PrivateService, error) {
	return fetch[*PrivateService](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/private_services", Body: input})
}

// Get: Retrieve a private service
//
// Returns: Successful response
func (r *PrivateServiceResource) Get(ctx context.Context, privateServiceID string, params PrivateServiceGetParams) (*PrivateService, error) {
	q := url.Values{}
	if params.Org != nil {
		q.Add("org", *params.Org)
	}
	return fetch[*PrivateService](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/private_services/" + url.PathEscape(privateServiceID), Query: q})
}
