// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6d1632eaa119

package platform

import (
	"context"
	"net/url"
)

// SolutionCategoryListParams: query parameters for SolutionCategoryResource.List.
type SolutionCategoryListParams struct {
	// Page: Page number to retrieve, 1-indexed. Defaults to `1`.
	Page *int
	// PageSize: Number of solution categories to return per page. Defaults to `25`.
	PageSize *int
	// Keys: Return only categories whose key exactly matches one of the provided values.
	Keys []string
	// ParentKeys: Return only categories whose parent key matches one of the provided values. Pass an empty array to return root-level categories.
	ParentKeys []string
	// LookupKey: Return only the category whose `lookup_key` exactly matches this value.
	LookupKey *string
	// PathPrefix: Return only categories whose `virtual_path` starts with this prefix.
	PathPrefix *string
	// Owners: Restrict results to categories owned by the specified scopes. Accepted values are `"system"` and `"org"`. Omit to include all ownership scopes visible to the caller.
	Owners []string
}

type SolutionCategoryResource struct {
	http *HTTPClient
}

func newSolutionCategoryResource(h *HTTPClient) *SolutionCategoryResource {
	return &SolutionCategoryResource{
		http: h,
	}
}

// List: List solution categories
//
// Returns a paginated list of solution category definitions visible to the authenticated caller.
// Use filters to narrow results by key, parent key, lookup key, or virtual path prefix.
// Results are scoped to categories accessible under the caller's viewer context. Pass `app` to
// restrict the listing to categories associated with a specific app scope. Omit `owners` to
// return categories from all ownership scopes (`"system"` and `"org"`) that the caller can see.
// Pagination is page-based. Use `page` and `page_size` to navigate large result sets. The
// response includes `total_entries`, `total_pages`, `has_next`, and `has_prev` to support
// pagination controls. `total_entries` reflects the count after key deduplication.
//
// Returns: Paginated list of solution category summaries matching the applied filters.
func (r *SolutionCategoryResource) List(ctx context.Context, params SolutionCategoryListParams) (*SolutionCategoryListResponse, error) {
	q := url.Values{}
	if params.Page != nil {
		q.Add("page", queryParam(*params.Page))
	}
	if params.PageSize != nil {
		q.Add("page_size", queryParam(*params.PageSize))
	}
	for _, item := range params.Keys {
		q.Add("keys", item)
	}
	for _, item := range params.ParentKeys {
		q.Add("parent_keys", item)
	}
	if params.LookupKey != nil {
		q.Add("lookup_key", *params.LookupKey)
	}
	if params.PathPrefix != nil {
		q.Add("path_prefix", *params.PathPrefix)
	}
	for _, item := range params.Owners {
		q.Add("owners", item)
	}
	return fetch[*SolutionCategoryListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/solution_categories", Query: q})
}
