// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 27cddd4663e5

package platform

import (
	"context"
	"net/url"
)

type UserThreadCreateInputThreadProfilePicture struct {
	// Data: Base64-encoded image bytes.
	Data *string `json:"data,omitempty"`
	// Filename: Original filename of the uploaded image, used for display and content-type inference.
	Filename *string `json:"filename,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`.
	MimeType *string `json:"mime_type,omitempty"`
}

type UserThreadCreateInputThreadSettings struct {
	// AgentEnabled: Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured.
	AgentEnabled *bool `json:"agent_enabled,omitempty"`
}

type UserThreadCreateInputThread struct {
	// CreateLegacyAgent: When `true`, provisions a legacy chat agent alongside the thread. Only needed for integrations that depend on the pre-v2 agent model.
	CreateLegacyAgent *bool `json:"create_legacy_agent,omitempty"`
	// Description: Optional longer description of the thread's purpose. `null` if not provided.
	Description *string `json:"description,omitempty"`
	// IsUnlisted: When `true`, the thread is hidden from the default thread list and accessible only by direct link or ID.
	IsUnlisted *bool `json:"is_unlisted,omitempty"`
	// Key: Client-assigned unique key for idempotent creation or later lookup. Must be unique within the owning organization.
	Key *string `json:"key,omitempty"`
	// Metadata: Arbitrary key-value pairs stored alongside the thread. Values must be strings or numbers.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Muted: When `true`, push and in-app notifications for this thread are suppressed for the creating user.
	Muted *bool `json:"muted,omitempty"`
	// OrgID: ID of the organization to create the thread under. Defaults to the authenticated user's primary organization when omitted.
	OrgID *string `json:"org_id,omitempty"`
	// ProfilePicture: Optional profile image for the thread, provided as a base64-encoded payload.
	ProfilePicture *UserThreadCreateInputThreadProfilePicture `json:"profile_picture,omitempty"`
	// Settings: Configuration overrides for the thread, such as AI model selection and context window settings.
	Settings *UserThreadCreateInputThreadSettings `json:"settings,omitempty"`
	// Title: Display name for the thread. `null` if omitted, which causes the thread to be untitled.
	Title *string `json:"title,omitempty"`
}

// UserThreadCreateInput: Create a thread for a user
type UserThreadCreateInput struct {
	// SkipWelcomeMessage: When `true`, suppresses the automatic welcome message that is otherwise sent into the thread on creation. Defaults to `false`.
	SkipWelcomeMessage *bool `json:"skip_welcome_message,omitempty"`
	// Thread: Attributes for the new thread. See ThreadCreateParams for the full set of accepted fields.
	Thread *UserThreadCreateInputThread `json:"thread"`
}

type UserInvitesInputInvite struct {
	// Metadata: Arbitrary key-value metadata to attach to the invite. Returned as-is on the resulting invite object.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// PersonaID: ID of the persona to associate with this invite (`per_...`). `null` if the invite is not bound to a persona.
	PersonaID *string `json:"persona_id,omitempty"`
	// ThreadID: ID of the thread to associate with this invite (`thr_...`). `null` if the invite is not bound to a thread.
	ThreadID *string `json:"thread_id,omitempty"`
}

// UserInvitesInput: Create a user invite
type UserInvitesInput struct {
	// Invite: Parameters for the new invite. See the UserInviteCreateParams schema for field details.
	Invite *UserInvitesInputInvite `json:"invite"`
}

type UserProfileInputProfilePicture struct {
	// Data: Base64-encoded binary content of the image file.
	Data *string `json:"data,omitempty"`
	// Filename: Original filename of the image, used for storage metadata.
	Filename *string `json:"filename,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`.
	MimeType *string `json:"mime_type,omitempty"`
}

// UserProfileInput: Update the current user's profile
type UserProfileInput struct {
	// Alias: Short display alias shown in place of the full name in compact UI contexts.
	Alias *string `json:"alias,omitempty"`
	// FullName: Updated display name for the user.
	FullName *string `json:"full_name,omitempty"`
	// Metadata: Arbitrary key-value metadata to associate with the user. Existing keys are merged; pass `null` for a key to remove it.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// ProfilePicture: New profile picture to upload as a base64-encoded image. Replaces any existing picture.
	ProfilePicture *UserProfileInputProfilePicture `json:"profile_picture,omitempty"`
}

type UserThreadListResponseDataItemCreator struct {
	// Alias: Short handle or alias for the user. `null` if not set.
	Alias *string `json:"alias,omitempty"`
	// App: ID of the app this user (and their access token) is scoped to (`dap_...`). `null` if the user is not scoped to an app.
	App *string `json:"app,omitempty"`
	// AppName: Display name of the user's app. `null` when the app association was not preloaded by the caller.
	AppName *string `json:"app_name,omitempty"`
	// Email: Email address of the user.
	Email *string `json:"email,omitempty"`
	// ID: User ID (`usr_...`).
	ID string `json:"id"`
	// IsSystemUser: `true` if this account is an internal system user rather than a human. System users are created automatically by the platform.
	IsSystemUser *bool `json:"is_system_user,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the user. Defaults to an empty object.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Full display name of the user. `null` if the user has not set a name.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this user belongs to (`org_...`). `null` if the user is not a member of any organization.
	Org *string `json:"org,omitempty"`
	// OrgName: Display name of the user's organization. `null` when the user is not in an org, or when the org association was not preloaded by the caller.
	OrgName *string `json:"org_name,omitempty"`
	// OrgRole: Role of the user within their organization. One of `"admin"`, `"member"`, or `"viewer"`. `null` when the user is not a member of any organization.
	OrgRole *string `json:"org_role,omitempty"`
	// Sandbox: ID of the sandbox environment this user is scoped to (`sbx_...`). `null` for production users.
	Sandbox *string `json:"sandbox,omitempty"`
	// SandboxName: Display name of the user's sandbox environment. `null` for production users, or when the sandbox association was not preloaded by the caller.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

type UserThreadListResponseDataItemParentMessageActorsItemProfilePicture struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParentMessageActorsItem struct {
	// Alias: Short handle or alias for the actor, used as an alternate display identifier. `null` if not configured.
	Alias *string `json:"alias,omitempty"`
	// ID: Composite actor identifier. Format is `"user-<usr_...>"` for human users or `"agent-<agi_...>"` for agents.
	ID *string `json:"id,omitempty"`
	// Name: Display name of the actor shown in the UI. `null` if no name is set.
	Name *string `json:"name,omitempty"`
	// ProfilePicture: Profile picture for the actor. `null` if the actor has no profile picture.
	ProfilePicture *UserThreadListResponseDataItemParentMessageActorsItemProfilePicture `json:"profile_picture,omitempty"`
}

type UserThreadListResponseDataItemParentMessageAttachmentsItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParentMessageAttachmentsItemVariantsItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParentMessageAttachmentsItemVariantsItem struct {
	// ContentType: MIME type of this variant's file (e.g., `"image/jpeg"`, `"video/mp4"`). `null` if the file is not loaded.
	ContentType *string `json:"content_type,omitempty"`
	// CreatedAt: When this variant was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// File: ID of the underlying storage file that backs this variant (`fil_...`).
	File *string `json:"file,omitempty"`
	// Filename: Original filename of the uploaded file for this variant. `null` if the file is not loaded.
	Filename *string `json:"filename,omitempty"`
	// Height: Height of this variant in pixels. `null` if not recorded.
	Height *int `json:"height,omitempty"`
	// ID: Media variant ID (`mvr_...`).
	ID string `json:"id"`
	// ImageSource: Resolved image delivery metadata for this variant, including dimensions and CDN URL. `null` for non-image content types.
	ImageSource *UserThreadListResponseDataItemParentMessageAttachmentsItemVariantsItemImageSource `json:"image_source,omitempty"`
	// UpdatedAt: When this variant was last updated (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// URL: Signed download URL for this variant, resolved at request time. `null` if the file is unavailable.
	URL *string `json:"url,omitempty"`
	// VariantKey: Identifier for this variant's processing tier. Common values include `"original"` (the unmodified upload) and `"thumbnail"` (a resized preview).
	VariantKey *string `json:"variant_key,omitempty"`
	// Width: Width of this variant in pixels. `null` if not recorded.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParentMessageAttachmentsItem struct {
	// ContentType: MIME type of the attached file, e.g. `"image/png"` or `"application/pdf"`. Present on `file`, `artifact`, and `media` types. `null` otherwise.
	ContentType *string `json:"content_type,omitempty"`
	// Description: Short description. The page meta-description for `scraped_link`, the artifact description for `artifact`, and the task description for `task` types. `null` on other types.
	Description *string `json:"description,omitempty"`
	// Filename: Original filename of the attached file, e.g. `"report.pdf"`. Present on `file`, `artifact`, and `media` types. `null` otherwise.
	Filename *string `json:"filename,omitempty"`
	// Height: Height in pixels of the media item. Present on `media` type only. `null` otherwise.
	Height *int `json:"height,omitempty"`
	// ID: Unique identifier for this attachment within the message.
	ID string `json:"id"`
	// ImageHeight: Height in pixels of the scraped preview image. Present on `scraped_link` type only. `null` otherwise.
	ImageHeight *int `json:"image_height,omitempty"`
	// ImageSource: Image source metadata for inline rendering. Present on `file`, `scraped_link`, `artifact`, and `media` types when the content is an image. `null` otherwise.
	ImageSource *UserThreadListResponseDataItemParentMessageAttachmentsItemImageSource `json:"image_source,omitempty"`
	// ImageURL: URL of the preview image extracted from the scraped page. Present on `scraped_link` type only. `null` otherwise.
	ImageURL *string `json:"image_url,omitempty"`
	// ImageWidth: Width in pixels of the scraped preview image. Present on `scraped_link` type only. `null` otherwise.
	ImageWidth *int `json:"image_width,omitempty"`
	// MediaType: The media category, e.g. `"video"` or `"audio"`. Present on `media` type only. `null` otherwise.
	MediaType *string `json:"media_type,omitempty"`
	// Name: Display name of the media item. Present on `media` type only. `null` otherwise.
	Name *string `json:"name,omitempty"`
	// Object: The full embedded object payload. For `task` type, contains the task record. For `action` type, contains the action definition. `null` on other types.
	Object map[string]JSONValue `json:"object,omitempty"`
	// Title: Display title. The page title for `scraped_link`, the artifact name for `artifact`, and the task title for `task` types. `null` on other types.
	Title *string `json:"title,omitempty"`
	// Type: The attachment type. One of `"file"`, `"scraped_link"`, `"artifact"`, `"task"`, `"media"`, or `"action"`. Determines which additional fields are present.
	Type string `json:"type"`
	// URL: URL to access the resource. A signed download URL for `file` and `artifact` types; the original URL for `scraped_link`; a media playback URL for `media`. `null` on `task` and `action` types.
	URL *string `json:"url,omitempty"`
	// Variants: Array of available encoding variants for the media item (e.g. different resolutions). Present on `media` type only. `null` otherwise.
	Variants []UserThreadListResponseDataItemParentMessageAttachmentsItemVariantsItem `json:"variants,omitempty"`
	// Version: Version number of the attached artifact at the time of attachment. Present on `artifact` type only. `null` otherwise.
	Version *int `json:"version,omitempty"`
	// Width: Width in pixels of the media item. Present on `media` type only. `null` otherwise.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParentMessageReactionsItem struct {
	// Payload: Type-specific reaction data. For `"emoji_reaction"` reactions, contains an `emoji` key with the Unicode emoji string (e.g., `" "`).
	Payload map[string]JSONValue `json:"payload,omitempty"`
	// Type: Reaction type identifier. Currently always `"emoji_reaction"` for emoji-based reactions.
	Type string `json:"type"`
	// User: Public ID of the user who added the reaction (`usr_...`).
	User *string `json:"user,omitempty"`
}

type UserThreadListResponseDataItemParentMessage struct {
	// Actors: Resolved actor descriptors for the message sender, combining identity and display metadata. Always contains exactly one entry.
	Actors []UserThreadListResponseDataItemParentMessageActorsItem `json:"actors,omitempty"`
	// Agent: ID of the agent user that sent this message (`agi_...`). `null` for messages sent by human users.
	Agent *string `json:"agent,omitempty"`
	// AgentMode: Local agent execution mode for this message. One of `cli`, `embedded`, or `null` when the message was not created by a local agent execution path.
	AgentMode *string `json:"agent_mode,omitempty"`
	// Attachments: Files, links, tasks, media, artifacts, and actions attached to this message. Empty array if there are no attachments.
	Attachments []UserThreadListResponseDataItemParentMessageAttachmentsItem `json:"attachments,omitempty"`
	// BranchedThread: ID of the thread that was branched from this message (`thr_...`). `null` if this message has not spawned a branch thread.
	BranchedThread *string `json:"branched_thread,omitempty"`
	// Content: Text content of the message. `null` for messages that contain only attachments.
	Content *string `json:"content,omitempty"`
	// CreatedAt: When the message was posted (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// HasReplies: Whether this message has at least one reply. Only present when explicitly requested or computed by the server.
	HasReplies *bool `json:"has_replies,omitempty"`
	// ID: Message ID (`msg_...`).
	ID string `json:"id"`
	// IdempotencyKey: Client-supplied idempotency key used to deduplicate message sends. `null` if the sender did not provide one.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// LegacyAgent: Identifier of the legacy chat agent that sent this message, if applicable. `null` for messages sent by users or modern agent users.
	LegacyAgent *string `json:"legacy_agent,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the message. Always present; defaults to an empty object when no metadata has been set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Org: ID of the organization that owns this message (`org_...`).
	Org *string `json:"org,omitempty"`
	// Reactions: Emoji and other reactions added to this message by users. Empty array if no reactions have been added or the association is not preloaded.
	Reactions []UserThreadListResponseDataItemParentMessageReactionsItem `json:"reactions,omitempty"`
	// RenderingMode: Display hint for how the message should be rendered. One of `"reply"`, `"direct"`, or `"inline"`. `null` for user-authored messages, which are always rendered as standard replies.
	RenderingMode *string `json:"rendering_mode,omitempty"`
	// Replies: Inline array of reply messages, each serialized as a full message object. Only present when the server has preloaded replies for this message.
	Replies []map[string]JSONValue `json:"replies,omitempty"`
	// RepliesAfterCursor: Opaque pagination cursor to fetch replies posted after the current page. Only present when inline replies are included in the response.
	RepliesAfterCursor *string `json:"replies_after_cursor,omitempty"`
	// RepliesBeforeCursor: Opaque pagination cursor to fetch replies posted before the current page. Only present when inline replies are included in the response.
	RepliesBeforeCursor *string `json:"replies_before_cursor,omitempty"`
	// ReplyCount: Total number of direct replies to this message. Only present when explicitly requested or computed by the server.
	ReplyCount *int `json:"reply_count,omitempty"`
	// ReplyTo: The parent message this message is a reply to, expanded as a full message object when loaded. `null` if this is a top-level message or the association is not preloaded.
	ReplyTo map[string]JSONValue `json:"reply_to,omitempty"`
	// Sandbox: ID of the developer sandbox this message belongs to (`dsb_...`). `null` for non-sandbox messages.
	Sandbox *string `json:"sandbox,omitempty"`
	// Team: ID of the team this message is scoped to (`tem_...`). `null` if the message is not team-scoped.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the thread this message belongs to (`thr_...`). `null` for messages not yet associated with a thread.
	Thread *string `json:"thread,omitempty"`
	// User: The human user who sent this message. Returns a public ID string (`usr_...`) when the association is not preloaded, or an expanded user object when it is. `null` for messages sent by agents.
	User *string `json:"user,omitempty"`
}

type UserThreadListResponseDataItemParticipantsItem struct {
	// Alias: Short handle or alias for the user. `null` if not set.
	Alias *string `json:"alias,omitempty"`
	// App: ID of the app this user (and their access token) is scoped to (`dap_...`). `null` if the user is not scoped to an app.
	App *string `json:"app,omitempty"`
	// AppName: Display name of the user's app. `null` when the app association was not preloaded by the caller.
	AppName *string `json:"app_name,omitempty"`
	// Email: Email address of the user.
	Email *string `json:"email,omitempty"`
	// ID: User ID (`usr_...`).
	ID string `json:"id"`
	// IsSystemUser: `true` if this account is an internal system user rather than a human. System users are created automatically by the platform.
	IsSystemUser *bool `json:"is_system_user,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the user. Defaults to an empty object.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Full display name of the user. `null` if the user has not set a name.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this user belongs to (`org_...`). `null` if the user is not a member of any organization.
	Org *string `json:"org,omitempty"`
	// OrgName: Display name of the user's organization. `null` when the user is not in an org, or when the org association was not preloaded by the caller.
	OrgName *string `json:"org_name,omitempty"`
	// OrgRole: Role of the user within their organization. One of `"admin"`, `"member"`, or `"viewer"`. `null` when the user is not a member of any organization.
	OrgRole *string `json:"org_role,omitempty"`
	// Sandbox: ID of the sandbox environment this user is scoped to (`sbx_...`). `null` for production users.
	Sandbox *string `json:"sandbox,omitempty"`
	// SandboxName: Display name of the user's sandbox environment. `null` for production users, or when the sandbox association was not preloaded by the caller.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemAclAddItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemAclGrantsItem struct {
	// Actions: Array of action strings the principal is permitted to perform, e.g. `["read", "write"]`. Must contain at least one entry.
	Actions []string `json:"actions"`
	// Principal: The identifier of the principal. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`; omit entirely when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal receiving the grant. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemAclRemoveItem struct {
	// Principal: The identifier of the principal to remove. A string ID for `"user"`, `"team"`, `"org"`, and `"agent"` types; one of `"admin"`, `"member"`, or `"viewer"` for `"org_role"`. Omit when `principal_type` is `"everyone"`.
	Principal *string `json:"principal,omitempty"`
	// PrincipalType: The kind of principal to remove. One of `"user"`, `"team"`, `"org"`, `"org_role"`, `"agent"`, or `"everyone"`.
	PrincipalType string `json:"principal_type"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemAcl struct {
	// Add: Patch mode: grants to add or merge into the existing list. Cannot be combined with `grants`.
	Add []UserThreadListResponseDataItemParticipatingAgentsItemAclAddItem `json:"add,omitempty"`
	// Grants: Replace mode: the complete new list of grants that replaces all existing entries. Send an empty array (`[]`) to clear all grants. Cannot be combined with `add` or `remove`.
	Grants []UserThreadListResponseDataItemParticipatingAgentsItemAclGrantsItem `json:"grants,omitempty"`
	// Remove: Patch mode: principals whose grants should be removed from the existing list. Cannot be combined with `grants`.
	Remove []UserThreadListResponseDataItemParticipatingAgentsItemAclRemoveItem `json:"remove,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionOrgLogo struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItem struct {
	// Description: Short prose blurb from the template body's `description:` field. `null` when the body doesn't set one. Used as the card subhead in the Library carousel.
	Description *string `json:"description,omitempty"`
	// DisplayName: Human-facing label from the template body's `display_name:` field. `null` when the body doesn't set one. Library carousels use this for the card title, falling back to a humanized `name`.
	DisplayName *string `json:"display_name,omitempty"`
	// ID: Template config ID (`cfg_...`). `null` for inline-only templates.
	ID *string `json:"id,omitempty"`
	// Kind: Template config kind, or `SolutionTemplateRef` / `SolutionTemplatePath` when unresolved.
	Kind string `json:"kind"`
	// LookupKey: Lookup key stamped on the template config at import time. `null` when no lookup key was assigned.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Name: Canonical name from the template body. For `AgentTemplate` this doubles as the human-facing label; for `AgentToolTemplate` it's the LLM-facing tool function identifier (snake_case); for `AgentRoutineTemplate` it's the routine identifier (kebab-case). Clients rendering carousels should prefer `display_name` and fall back to humanizing `name`.
	Name *string `json:"name,omitempty"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded, scoped to this template's bundled markdown asset. `null` when the Solution body's `templates[].readme_path` is unset for this entry. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// VirtualPath: Stable virtual path assigned to the template config. `null` when no virtual path was set.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolution struct {
	// CategoryKeys: Category tag keys declared in the Solution body, used to group Solutions in the catalog. An empty array when the body declares none.
	CategoryKeys []string `json:"category_keys,omitempty"`
	// CreatedAt: When the Solution config was first imported (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Description: Short tagline or summary declared in the Solution body, used as the card subhead in catalog UIs. `null` when the Solution body does not set one.
	Description *string `json:"description,omitempty"`
	// ID: Solution config ID (`cfg_...`).
	ID string `json:"id"`
	// Kind: Resource type. Always `"Solution"`.
	Kind string `json:"kind"`
	// LatestSolution: When `upgrade_available` is `true`, the system-scope Solution config ID (`cfg_...`) that should be used as the upgrade source. `null` otherwise.
	LatestSolution *string `json:"latest_solution,omitempty"`
	// LatestVersion: When `upgrade_available` is `true`, the higher system-scope `solution_version` available to upgrade to. `null` otherwise.
	LatestVersion *string `json:"latest_version,omitempty"`
	// LookupKey: The lookup key stored on the Solution config, if one was assigned during import. `null` when no lookup key was set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Metadata: Arbitrary key-value metadata declared in the Solution body (e.g. category or display hints). Present as an empty object when the body declares none.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Human-facing display name declared in the Solution body. `null` when the Solution body does not set one.
	Name *string `json:"name,omitempty"`
	// Org: Organization ID (`org_...`) that owns this Solution config, when the Solution is scoped to a specific org. `null` for system-scope (app-level) Solutions.
	Org *string `json:"org,omitempty"`
	// OrgLogo: Canonical image-source object for the resolved `org`'s logo, used as the principal category section glyph. Carries the signed `url` plus a `refresh_url`. `null` when `org_slug` is `null` or the org has no logo.
	OrgLogo *UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionOrgLogo `json:"org_logo,omitempty"`
	// OrgName: Display name of the resolved `org`. Pairs with `org_slug` as the principal catalog category's label. `null` when `org_slug` is `null`.
	OrgName *string `json:"org_name,omitempty"`
	// OrgSlug: Resolved slug of the Solution body's `org` (the publishing organization), when set and it resolves to a real org visible to the viewer. When present this is the Solution's principal catalog category key clients group the Solution under this org ahead of `category_keys`. `null` when the body has no `org` or it doesn't resolve.
	OrgSlug *string `json:"org_slug,omitempty"`
	// Owners: Owner scopes this Solution appears under. Members: `"system"` (app-level system scope) and/or `"org"` (viewer's org scope).
	Owners []string `json:"owners"`
	// ReadmeURL: Relative path to the public README endpoint with a signed token already embedded. `null` when the Solution has no README. Token expires in 1 hour refresh via `GET /api/v1/solutions/:solution`.
	ReadmeURL *string `json:"readme_url,omitempty"`
	// SolutionID: Stable UUID declared in the Solution body, used to identify the same logical Solution across multiple installed copies and owner scopes. `null` when the body omits it.
	SolutionID *string `json:"solution_id,omitempty"`
	// SolutionVersion: Semver string declared in the Solution body (e.g. `"1.2.0"`). `null` when the body does not declare a version.
	SolutionVersion *string `json:"solution_version,omitempty"`
	// TagKeys: Freeform tag keys declared in the Solution body. An empty array when the body declares none.
	TagKeys []string `json:"tag_keys,omitempty"`
	// TemplateKind: Wrapped template kind `"AgentTemplate"`, `"AutomationTemplate"`, `"AgentRoutineTemplate"`, `"AgentToolTemplate"`, `"AgentComputerTemplate"`, or `"SolutionTemplateRef"` for ref-mode bundles.
	TemplateKind *string `json:"template_kind,omitempty"`
	// Templates: Template configs bundled by this Solution, in declaration order the first entry is the deployable template the Solution wraps; the rest are sibling templates the wrapped template references.
	Templates []UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolutionTemplatesItem `json:"templates"`
	// UpdatedAt: When the Solution config was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// UpgradeAvailable: `true` when this Solution is installed at the viewer's org scope and the app-level system scope carries a higher `solution_version`. Always `false` for system-only rows.
	UpgradeAvailable bool `json:"upgrade_available"`
	// VirtualPath: The stable virtual path assigned to this Solution config, used as the deduplication key when the same Solution appears under multiple owner scopes. `null` when unset.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionTemplate struct {
	// CreatedAt: When this template config was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Description: Description of the template from the config body. `null` if the current version has no `description` field.
	Description *string `json:"description,omitempty"`
	// DisplayName: Human-readable display name from the config body. `null` if the current version has no `display_name` field.
	DisplayName *string `json:"display_name,omitempty"`
	// ID: Template config ID (`cfg_...`).
	ID string `json:"id"`
	// Kind: Config kind identifier for this template (e.g. `"agent_tool_template"`).
	Kind string `json:"kind"`
	// LookupKey: Stable lookup key assigned to this template config. `null` if no lookup key is set.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Name: Template name as stored in the config body. `null` if the current version has no `name` field.
	Name *string `json:"name,omitempty"`
	// UpdatedAt: When this template config was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// VirtualPath: Virtual filesystem path for this template config. `null` if not set.
	VirtualPath *string `json:"virtual_path,omitempty"`
}

type UserThreadListResponseDataItemParticipatingAgentsItemSourceSolution struct {
	// Solution: Summary of the parent Solution, including `upgrade_available`, `latest_version`, and `latest_solution` when a newer system-scoped version is available for the agent's org-scoped Solution.
	Solution *UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionSolution `json:"solution"`
	// Template: Summary of the AgentTemplate config (`cfg_...`) the agent was last provisioned or updated from.
	Template *UserThreadListResponseDataItemParticipatingAgentsItemSourceSolutionTemplate `json:"template"`
}

type UserThreadListResponseDataItemParticipatingAgentsItem struct {
	// ACL: Access control list for the agent. Contains a `grants` array where each entry specifies `principal_type`, `principal`, and `actions`. `null` when no ACL restrictions are applied and the agent is accessible to all members of its scope.
	ACL *UserThreadListResponseDataItemParticipatingAgentsItemAcl `json:"acl,omitempty"`
	// App: ID of the application that owns this agent (`dap_...`).
	App *string `json:"app,omitempty"`
	// CreatedAt: When the agent was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// DefaultModel: Default LLM model identifier used by this agent when no model is specified at runtime (e.g. `"claude-3-7-sonnet-latest"`).
	DefaultModel *string `json:"default_model,omitempty"`
	// Email: Email address provisioned for this agent. `null` if email delivery is not configured.
	Email *string `json:"email,omitempty"`
	// ID: Agent ID (`agi_...`).
	ID string `json:"id"`
	// Identity: System-level identity prompt that shapes the agent's persona and behavior.
	Identity *string `json:"identity,omitempty"`
	// LastAppliedTemplateConfig: ID of the AgentTemplate config (`cfg_...`) this agent was last provisioned or updated from. `null` for manually created agents.
	LastAppliedTemplateConfig *string `json:"last_applied_template_config,omitempty"`
	// LookupKey: Stable, user-defined identifier for this agent within the application. Unique per app.
	LookupKey *string `json:"lookup_key,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the agent. Not interpreted by the platform.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Name: Human-readable display name for the agent. `null` if not set.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this agent belongs to (`org_...`). `null` if the agent is not org-scoped.
	Org *string `json:"org,omitempty"`
	// OrgName: Display name of the organization this agent belongs to. `null` when the agent is not org-scoped or when the org association was not preloaded.
	OrgName *string `json:"org_name,omitempty"`
	// Originator: Free-form label identifying the source or author that created this agent (e.g. a username or pipeline name).
	Originator *string `json:"originator,omitempty"`
	// PhoneNumber: Phone number provisioned for this agent. `null` if SMS is not configured.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Sandbox: ID of the sandbox environment this agent is scoped to (`dsb_...`). `null` in production deployments.
	Sandbox *string `json:"sandbox,omitempty"`
	// SourceSolution: Source Solution and AgentTemplate summary for agents provisioned from a Solution. Includes `upgrade_available`, `latest_version`, and `latest_solution` so you can render an upgrade badge without a separate dry-run call. `null` for hand-built agents and agents whose tracked template or parent Solution has been deleted. Populated only on single-agent GET responses, never on list endpoints.
	SourceSolution *UserThreadListResponseDataItemParticipatingAgentsItemSourceSolution `json:"source_solution,omitempty"`
	// Team: ID of the team that owns this agent (`tem_...`). `null` if the agent is not team-scoped.
	Team *string `json:"team,omitempty"`
	// TemplateUpgradeAvailable: True when the agent's last-applied template version is behind the current version of its AgentTemplate config i.e. reapplying the template (a per-agent upgrade) would bring it newer Solution content. Self-clears once the agent is reapplied. Computed only on list endpoints; `null` on single-agent GET.
	TemplateUpgradeAvailable *bool `json:"template_upgrade_available,omitempty"`
	// UpdatedAt: When the agent was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user that owns this agent (`usr_...`). `null` if the agent is not user-scoped.
	User *string `json:"user,omitempty"`
}

type UserThreadListResponseDataItemSettings struct {
	// AgentEnabled: Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured.
	AgentEnabled *bool `json:"agent_enabled,omitempty"`
}

type UserThreadListResponseDataItem struct {
	// AgentUser: ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads.
	AgentUser *string `json:"agent_user,omitempty"`
	// CreatedAt: When the thread was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Creator: Expanded user object for the user who created this thread. Populated only when the association is loaded.
	Creator *UserThreadListResponseDataItemCreator `json:"creator,omitempty"`
	// Description: Optional description or purpose statement for the thread. `null` if not set.
	Description *string `json:"description,omitempty"`
	// ID: Thread ID (`thr_...`).
	ID string `json:"id"`
	// IsChannel: Whether this thread operates as a channel a multi-member broadcast-style conversation.
	IsChannel *bool `json:"is_channel,omitempty"`
	// IsDefault: Whether this is the default thread for its owner. Each user or team has at most one default thread.
	IsDefault *bool `json:"is_default,omitempty"`
	// IsTransient: Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires.
	IsTransient *bool `json:"is_transient,omitempty"`
	// IsUnlisted: Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants.
	IsUnlisted *bool `json:"is_unlisted,omitempty"`
	// Key: Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set.
	Key *string `json:"key,omitempty"`
	// LastActivity: When the last message or activity occurred in this thread. Present only when activity enrichment is requested.
	LastActivity *Time `json:"last_activity,omitempty"`
	// Metadata: Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set.
	Metadata map[string]JSONValue `json:"metadata,omitempty"`
	// Muted: Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery.
	Muted *bool `json:"muted,omitempty"`
	// Org: ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context.
	Org *string `json:"org,omitempty"`
	// ParentMessage: The message that spawned this thread as a sub-thread. `null` for top-level threads.
	ParentMessage *UserThreadListResponseDataItemParentMessage `json:"parent_message,omitempty"`
	// Participant: Array of participant user IDs (`usr_...`) who are members of this thread.
	Participant []string `json:"participant,omitempty"`
	// Participants: Expanded participant user objects for each member of this thread. Populated only when the association is loaded.
	Participants []UserThreadListResponseDataItemParticipantsItem `json:"participants,omitempty"`
	// ParticipatingActor: Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested.
	ParticipatingActor []string `json:"participating_actor,omitempty"`
	// ParticipatingAgents: Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested.
	ParticipatingAgents []UserThreadListResponseDataItemParticipatingAgentsItem `json:"participating_agents,omitempty"`
	// Role: The authenticated user's membership role in this thread, e.g. `"owner"`, `"member"`, or `"viewer"`. `null` if the user is not a member.
	Role *string `json:"role,omitempty"`
	// Sandbox: ID of the developer sandbox this thread is scoped to (`sbx_...`). `null` for production threads.
	Sandbox *string `json:"sandbox,omitempty"`
	// Settings: Per-thread configuration settings controlling AI agent behavior for this thread.
	Settings *UserThreadListResponseDataItemSettings `json:"settings,omitempty"`
	// Slug: URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned.
	Slug *string `json:"slug,omitempty"`
	// SubThreads: Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested.
	SubThreads []map[string]JSONValue `json:"sub_threads,omitempty"`
	// Team: ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads.
	Team *string `json:"team,omitempty"`
	// Title: Human-readable name of the thread. `null` if no title has been set.
	Title *string `json:"title,omitempty"`
	// TTL: Time-to-live in seconds after which the thread may be automatically cleaned up. `null` if the thread does not expire.
	TTL *int `json:"ttl,omitempty"`
	// UnreadCount: Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested.
	UnreadCount *int `json:"unread_count,omitempty"`
	// UpdatedAt: When the thread was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads.
	User *string `json:"user,omitempty"`
}

// UserThreadListResponse: Successful response
type UserThreadListResponse struct {
	// Data: Array of thread objects matching the requested filters and agent narrowings.
	Data []UserThreadListResponseDataItem `json:"data"`
}

type UserArtifactsResponseDataItemImageSource struct {
	// File: ID of the underlying storage file (`fil_...`). `null` when the image is not backed by a platform storage file.
	File *string `json:"file,omitempty"`
	// Height: Height of the image in pixels. `null` if not known.
	Height *int `json:"height,omitempty"`
	// Media: ID of the associated media record (`med_...`). `null` when the image is not linked to a media entity.
	Media *string `json:"media,omitempty"`
	// MimeType: MIME type of the image, e.g. `"image/png"` or `"image/jpeg"`. `null` if not known.
	MimeType *string `json:"mime_type,omitempty"`
	// RefreshURL: Endpoint URL you can call to obtain a fresh signed `url` when the current one has expired. `null` if the URL does not require refreshing.
	RefreshURL *string `json:"refresh_url,omitempty"`
	// URL: Signed or public URL for downloading the image. May be time-limited; use `refresh_url` to obtain a new URL when this one expires.
	URL *string `json:"url,omitempty"`
	// Width: Width of the image in pixels. `null` if not known.
	Width *int `json:"width,omitempty"`
}

type UserArtifactsResponseDataItem struct {
	// Agent: ID of the agent that produced this artifact (`agt_...`). `null` if not agent-produced.
	Agent *string `json:"agent,omitempty"`
	// ContentType: MIME type of the current version's file, e.g. `"text/csv"` or `"image/png"`. `null` if no file is attached.
	ContentType *string `json:"content_type,omitempty"`
	// CreatedAt: When the artifact was first created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// CurrentVersion: ID of the current (latest published) artifact version (`artv_...`). `null` if no version has been published.
	CurrentVersion *string `json:"current_version,omitempty"`
	// Description: Optional longer description of the artifact's contents or purpose. `null` if not set.
	Description *string `json:"description,omitempty"`
	// File: Storage file ID for the current version (`fil_...`). `null` if no file is attached.
	File *string `json:"file,omitempty"`
	// FileName: Original filename of the current version's file, e.g. `"output.csv"`. `null` if no file is attached.
	FileName *string `json:"file_name,omitempty"`
	// FileURL: Short-lived signed URL for downloading the current version's file. `null` if no file is attached.
	FileURL *string `json:"file_url,omitempty"`
	// ID: Artifact ID (`art_...`).
	ID string `json:"id"`
	// ImageSource: Image source metadata for rendering the current version's file inline. Present only when `content_type` starts with `"image/"`. `null` otherwise.
	ImageSource *UserArtifactsResponseDataItemImageSource `json:"image_source,omitempty"`
	// Name: Human-readable name for the artifact, e.g. `"Q2 Report"`. `null` if not set.
	Name *string `json:"name,omitempty"`
	// Org: ID of the organization this artifact belongs to (`org_...`).
	Org *string `json:"org,omitempty"`
	// Sandbox: Identifier of the sandbox environment associated with this artifact. `null` if not sandbox-scoped.
	Sandbox *string `json:"sandbox,omitempty"`
	// Team: ID of the team that owns this artifact (`tea_...`). `null` if not team-scoped.
	Team *string `json:"team,omitempty"`
	// Thread: ID of the thread in which this artifact was created (`thr_...`). `null` if not thread-scoped.
	Thread *string `json:"thread,omitempty"`
	// UpdatedAt: When the artifact record was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// User: ID of the user who created this artifact (`usr_...`). `null` if not user-scoped.
	User *string `json:"user,omitempty"`
	// Version: Current version number of the artifact. Increments each time a new version is published.
	Version *int `json:"version,omitempty"`
}

// UserArtifactsResponse: Successful response
type UserArtifactsResponse struct {
	// Data: Array of artifact objects belonging to the user.
	Data []UserArtifactsResponseDataItem `json:"data"`
}

type UserOrgsResponseDataItem struct {
	// CreatedAt: When this organization was created (ISO 8601).
	CreatedAt *Time `json:"created_at,omitempty"`
	// Description: Short human-readable description of the organization. `null` if not set.
	Description *string `json:"description,omitempty"`
	// Domain: Primary domain associated with the organization, e.g. `"acme.com"`. `null` if not configured.
	Domain *string `json:"domain,omitempty"`
	// ID: Organization ID (`org_...`).
	ID string `json:"id"`
	// Industry: Industry category the organization belongs to, e.g. `"fintech"` or `"healthcare"`. `null` if not set.
	Industry *string `json:"industry,omitempty"`
	// Name: Display name of the organization. `null` if the org has not set a name.
	Name *string `json:"name,omitempty"`
	// OnboardingTrack: The new-user experience track this org first completed. `"vendor"` for orgs that onboarded as service providers; `"customer"` for orgs that onboarded as buyers. `null` if onboarding was not tracked.
	OnboardingTrack *string `json:"onboarding_track,omitempty"`
	// Sandbox: ID of the sandbox environment scoped to this organization (`snd_...`). `null` for organizations in production mode.
	Sandbox *string `json:"sandbox,omitempty"`
	// Slug: URL-safe identifier for the organization, used in vanity URLs and slug-based lookups.
	Slug *string `json:"slug,omitempty"`
	// Status: Current lifecycle status of the organization, e.g. `"active"` or `"suspended"`. `null` if the status has not been set.
	Status *string `json:"status,omitempty"`
	// UpdatedAt: When this organization was last modified (ISO 8601).
	UpdatedAt *Time `json:"updated_at,omitempty"`
	// Website: Public website URL for the organization. `null` if not set.
	Website *string `json:"website,omitempty"`
}

// UserOrgsResponse: Successful response
type UserOrgsResponse struct {
	// Data: Array of organization objects the user belongs to. Contains at most one item.
	Data []UserOrgsResponseDataItem `json:"data"`
}

// UserThreadListParams: query parameters for UserThreadResource.List.
type UserThreadListParams struct {
	// Agent: Array of agent user IDs (`usr_...`). When provided, only threads where at least one of the listed agents is also a member are returned. Omit or pass an empty array to return all threads regardless of agent membership.
	Agent []string
	// Filter: Array of metadata filter objects. Each filter matches threads whose `metadata` map contains the specified key/value pair. All filters must match (logical AND). Omit to return threads regardless of metadata.
	Filter []map[string]JSONValue
}

type UserThreadResource struct {
	http *HTTPClient
}

func newUserThreadResource(h *HTTPClient) *UserThreadResource {
	return &UserThreadResource{
		http: h,
	}
}

// List: List threads for a user
//
// Returns all threads visible to the specified user. The authenticated caller must
// have access to the target user's account; a 403 is returned otherwise.
// Pass one or more `agent` IDs to narrow results to threads where at least one of
// the listed agents is also a member useful for displaying every thread a user
// shares with a particular agent. Pass one or more `filter` objects to narrow
// results by thread metadata key/value pairs. Both narrowings may be combined in
// a single request.
// Results are returned as a flat array; no cursor-based pagination is applied.
//
// user: User ID (`usr_...`) whose threads should be listed.
//
// Returns: Successful response
func (r *UserThreadResource) List(ctx context.Context, user string, params UserThreadListParams) (*UserThreadListResponse, error) {
	q := url.Values{}
	for _, item := range params.Agent {
		q.Add("agent", item)
	}
	for _, item := range params.Filter {
		q.Add("filter", queryParam(item))
	}
	return fetch[*UserThreadListResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/users/" + url.PathEscape(user) + "/threads", Query: q})
}

// Create: Create a thread for a user
//
// Creates a new thread owned by the specified user. The authenticated caller must
// have access to the target user's account; a 403 is returned otherwise.
// An automatic welcome message is sent into the thread upon creation unless
// `skip_welcome_message` is set to `true`. The thread is immediately visible to
// the owning user and any members added at creation time.
//
// user: User ID (`usr_...`) whose threads should be listed.
//
// Returns: The newly created thread object.
func (r *UserThreadResource) Create(ctx context.Context, user string, input UserThreadCreateInput) (*Thread, error) {
	return fetch[*Thread](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/users/" + url.PathEscape(user) + "/threads", Body: input})
}

type UserResource struct {
	http    *HTTPClient
	Threads *UserThreadResource
}

func newUserResource(h *HTTPClient) *UserResource {
	return &UserResource{
		http:    h,
		Threads: newUserThreadResource(h),
	}
}

// Me: Retrieve the current user
//
// Returns the user associated with the authenticated session or bearer
// token. This is the canonical way to resolve "who am I?" after
// authentication.
// The response includes the user's profile, notification settings, and
// profile picture, along with the app, organization, and sandbox the
// token is scoped to and their display names enough to establish full
// session context in a single call. Unauthenticated requests return 401.
//
// Returns: The authenticated user object.
func (r *UserResource) Me(ctx context.Context) (*User, error) {
	return fetch[*User](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/users/me"})
}

// Get: Retrieve a user by ID
//
// Returns the user identified by `user`. The authenticated user must share
// at least one team with the target user; requests for users outside any
// shared team are rejected with 403.
// A user may always retrieve their own profile with this endpoint. Use the
// `GET /users/me` endpoint as a convenience alias for retrieving the
// authenticated user without specifying an ID.
//
// user: User ID (`usr_...`) of the user to retrieve.
//
// Returns: The requested user object.
func (r *UserResource) Get(ctx context.Context, user string) (*User, error) {
	return fetch[*User](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/users/" + url.PathEscape(user)})
}

// Artifacts: List a user's artifacts
//
// Returns all artifacts owned by the specified user. Artifacts represent
// AI-generated or user-uploaded files associated with agent sessions,
// threads, or sandboxes such as images, documents, and code outputs.
// The authenticated user must be requesting their own artifacts or must
// have administrative access. Attempting to list artifacts for a user
// the caller is not authorized to access returns 403.
// Results are returned in a single page without cursor pagination. Each
// artifact in the response reflects the state of its current version,
// including a short-lived signed `file_url` for direct download.
//
// user: User ID (`usr_...`). The authenticated user must be this user or have access to their artifacts.
//
// Returns: Successful response
func (r *UserResource) Artifacts(ctx context.Context, user string) (*UserArtifactsResponse, error) {
	return fetch[*UserArtifactsResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/users/" + url.PathEscape(user) + "/artifacts"})
}

// Invites: Create a user invite
//
// Creates a new invite for the authenticated user. The invite can optionally be
// scoped to a specific thread, a persona, or carry arbitrary metadata. The
// caller receives the new invite object at HTTP 201.
// The invite key is always generated server-side (192-bit URL-safe random
// string) and cannot be supplied by the caller.
// The path `:user` must match the authenticated user. If a `thread_id` is
// provided, the authenticated user must have permission to invite others to that
// thread; team threads are not supported and return an error. Supplying a
// `thread_id` that does not exist or that belongs to a different user returns
// an error. If a key collision occurs during creation the call returns a 409
// conflict simply retry to generate a new key.
//
// user: User ID (`usr_...`). Must match the authenticated user.
//
// Returns: The newly created invite object.
func (r *UserResource) Invites(ctx context.Context, user string, input UserInvitesInput) (*UserInvite, error) {
	return fetch[*UserInvite](r.http, ctx, requestSpec{Method: "POST", Path: "/api/v1/users/" + url.PathEscape(user) + "/invites", Body: input})
}

// Orgs: List organizations for a user
//
// Returns the organizations the specified user belongs to. A user can belong
// to at most one organization, so the `data` array contains either zero or one
// items.
// The authenticated viewer must have permission to inspect the target user.
// Returns an empty `data` array when the user has no organization membership.
//
// user: User ID (`usr_...`) whose organization membership you want to retrieve.
//
// Returns: Successful response
func (r *UserResource) Orgs(ctx context.Context, user string) (*UserOrgsResponse, error) {
	return fetch[*UserOrgsResponse](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/users/" + url.PathEscape(user) + "/orgs"})
}

// Profile: Update the current user's profile
//
// Updates one or more profile fields for the authenticated user. All
// fields are optional; omit any you do not want to change.
// When `profile_picture` is supplied, the image is uploaded and replaces
// the existing picture. The previous picture is deleted after the new one
// is stored. Image upload failures return 422 without modifying other
// profile fields.
//
// user: User ID (`usr_...`) or `"me"` for the authenticated user.
//
// Returns: The user object with updated profile fields.
func (r *UserResource) Profile(ctx context.Context, user string, input UserProfileInput) (*User, error) {
	return fetch[*User](r.http, ctx, requestSpec{Method: "PUT", Path: "/api/v1/users/" + url.PathEscape(user) + "/profile", Body: input})
}
