// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 27b09bd7cd64

package platform

import (
	"context"
	"net/url"
)

// WorkItemFailInput: Fail workflow work and route its durable execution
type WorkItemFailInput struct {
	// Error: JSON-serializable failure returned by the worker.
	Error map[string]JSONValue `json:"error"`
	// LeaseOwner: Saved lease token.
	LeaseOwner string `json:"lease_owner"`
}

// WorkItemHeartbeatInput: Extend a workflow work item lease
type WorkItemHeartbeatInput struct {
	// LeaseOwner: Saved lease token.
	LeaseOwner string `json:"lease_owner"`
	// LeaseSeconds: Replacement lease duration from 15 through 3600 seconds. Defaults to 300.
	LeaseSeconds *int `json:"lease_seconds,omitempty"`
}

// WorkItemStartInput: Mark claimed workflow work as running
type WorkItemStartInput struct {
	// LeaseOwner: Saved lease token.
	LeaseOwner string `json:"lease_owner"`
}

// WorkItemSubmitInput: Submit workflow work output and wake its durable execution
type WorkItemSubmitInput struct {
	// LeaseOwner: Saved lease token.
	LeaseOwner string `json:"lease_owner"`
	// Result: JSON-serializable output returned to the workflow.
	Result map[string]JSONValue `json:"result"`
}

// WorkItemListParams: query parameters for WorkItemResource.List.
type WorkItemListParams struct {
	// Execution: Optional durable execution ID filter.
	Execution *string
	// Limit: Maximum work items per page. Defaults to 50; maximum is 100.
	Limit *int
	// AfterCursor: Opaque cursor for the next page of older queued work.
	AfterCursor *string
}

type WorkItemResource struct {
	http *HTTPClient
}

func newWorkItemResource(h *HTTPClient) *WorkItemResource {
	return &WorkItemResource{
		http: h,
	}
}

// List: List active workflow work available to the viewer
//
// Lists queued, claimed, and running external work yielded by durable workflows.
// The top-level collection includes work for every agent the viewer can execute;
// the agent-nested collection limits results to that agent. This discovery
// response never includes lease tokens. Use the agent claim endpoint to acquire
// new work or resume a saved lease.
//
// Returns: Successful response
func (r *WorkItemResource) List(ctx context.Context, params WorkItemListParams) (*WorkflowWorkItemList, error) {
	q := url.Values{}
	if params.Execution != nil {
		q.Add("execution", *params.Execution)
	}
	if params.Limit != nil {
		q.Add("limit", queryParam(*params.Limit))
	}
	if params.AfterCursor != nil {
		q.Add("after_cursor", *params.AfterCursor)
	}
	return fetch[*WorkflowWorkItemList](r.http, ctx, requestSpec{Method: "GET", Path: "/api/v1/work_items", Query: q})
}

// Fail: Fail workflow work and route its durable execution
//
// Atomically records command failure, marks the work item failed, and either
// wakes the workflow at the node's error edge or fails the owning run when no
// error edge exists. Retrying the same lease and error is idempotent; a
// different terminal payload conflicts.
//
// workItem: Claimed or running work item ID.
//
// Returns: No content
func (r *WorkItemResource) Fail(ctx context.Context, workItem string, input WorkItemFailInput) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/work_items/" + url.PathEscape(workItem) + "/fail", Body: input})
}

// Heartbeat: Extend a workflow work item lease
//
// workItem: Claimed or running work item ID.
//
// Returns: No content
func (r *WorkItemResource) Heartbeat(ctx context.Context, workItem string, input WorkItemHeartbeatInput) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/work_items/" + url.PathEscape(workItem) + "/heartbeat", Body: input})
}

// Start: Mark claimed workflow work as running
//
// workItem: Claimed work item ID.
//
// Returns: No content
func (r *WorkItemResource) Start(ctx context.Context, workItem string, input WorkItemStartInput) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/work_items/" + url.PathEscape(workItem) + "/start", Body: input})
}

// Submit: Submit workflow work output and wake its durable execution
//
// Atomically records the command completion, marks the work item succeeded,
// advances the journal sequence, and enqueues the owning workflow continuation.
// Retrying the same lease and result is idempotent; a different result conflicts.
//
// workItem: Claimed or running work item ID.
//
// Returns: No content
func (r *WorkItemResource) Submit(ctx context.Context, workItem string, input WorkItemSubmitInput) error {
	return r.http.requestVoid(ctx, requestSpec{Method: "POST", Path: "/api/v1/work_items/" + url.PathEscape(workItem) + "/submit", Body: input})
}
