// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6f219456dc18

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestAPIActivityFeedChannelJoin1ReceivesContractValidReply(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		channel, err := platform.JoinAPIActivityFeedChannelAgent(ctx, socket, "test-id")
		if err != nil {
			t.Fatalf("join failed: %v", err)
		}
		if channel.JoinResponse.IsNull() {
			t.Fatal("expected a join response payload")
		}
	})
}

func TestAPIActivityFeedChannelJoin1SurfacesServerErrorReply(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		h.registerScenario(t, map[string]any{
			"topic":  "api:activity_feed:agent:test-id",
			"onJoin": []any{map[string]any{"type": "replyError", "payload": map[string]any{"reason": "test_error"}}},
		})
		_, err := platform.JoinAPIActivityFeedChannelAgent(ctx, socket, "test-id")
		requireChannelError(t, err)
	})
}

func TestAPIActivityFeedChannelJoin2ReceivesContractValidReply(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		channel, err := platform.JoinAPIActivityFeedChannelOrg(ctx, socket, "test-id")
		if err != nil {
			t.Fatalf("join failed: %v", err)
		}
		if channel.JoinResponse.IsNull() {
			t.Fatal("expected a join response payload")
		}
	})
}

func TestAPIActivityFeedChannelJoin2SurfacesServerErrorReply(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		h.registerScenario(t, map[string]any{
			"topic":  "api:activity_feed:org:test-id",
			"onJoin": []any{map[string]any{"type": "replyError", "payload": map[string]any{"reason": "test_error"}}},
		})
		_, err := platform.JoinAPIActivityFeedChannelOrg(ctx, socket, "test-id")
		requireChannelError(t, err)
	})
}

func TestAPIActivityFeedChannelListEntriesSendsValidPush(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		h.registerScenario(t, map[string]any{
			"topic":     "api:activity_feed:agent:test-id",
			"onJoin":    []any{map[string]any{"type": "autoReply"}},
			"onMessage": map[string]any{"list_entries": []any{map[string]any{"type": "autoReply"}}},
		})
		channel, err := platform.JoinAPIActivityFeedChannelAgent(ctx, socket, "test-id")
		if err != nil {
			t.Fatalf("join failed: %v", err)
		}
		reply, err := channel.ListEntries(ctx, platform.APIActivityFeedListEntriesInput{AfterCursor: platform.Ptr("test-value"), BeforeCursor: platform.Ptr("test-value"), Kind: platform.Ptr("test"), Level: platform.Ptr("test-value"), Limit: platform.Ptr(1)})
		if err != nil {
			t.Fatalf("push failed: %v", err)
		}
		if reply.Status != "ok" {
			t.Fatalf("expected an ok reply, got %q", reply.Status)
		}
		observed := h.observations(t, "api:activity_feed:agent:test-id", "list_entries")
		if len(observed) != 1 {
			t.Fatalf("expected 1 observation, got %d", len(observed))
		}
		if observed[0].Get("params").IsNull() {
			t.Fatal("expected the observed frame to carry params")
		}
	})
}

func TestAPIActivityFeedChannelOnNewEntryDeliversPayloads(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		h.registerScenario(t, map[string]any{
			"topic": "api:activity_feed:agent:test-id",
			"onJoin": []any{
				map[string]any{"type": "autoReply"},
				map[string]any{"type": "autoPush", "event": "new_entry"},
			},
		})
		channel, err := platform.JoinAPIActivityFeedChannelAgent(ctx, socket, "test-id")
		if err != nil {
			t.Fatalf("join failed: %v", err)
		}
		payloads := make(chan platform.APIActivityFeedNewEntryPayload, 8)
		channel.OnNewEntry(func(payload platform.APIActivityFeedNewEntryPayload) { payloads <- payload })
		use(awaitFirst(t, payloads))
	})
}

func TestAPIActivityFeedChannelLeavesCleanly(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarnessSocket(t, func(h *harnessClient, socket *platform.Socket) {
		h.registerScenario(t, map[string]any{
			"topic":  "api:activity_feed:agent:test-id",
			"onJoin": []any{map[string]any{"type": "autoReply"}},
		})
		channel, err := platform.JoinAPIActivityFeedChannelAgent(ctx, socket, "test-id")
		if err != nil {
			t.Fatalf("join failed: %v", err)
		}
		if err := channel.Leave(ctx); err != nil {
			t.Fatalf("leave failed: %v", err)
		}
	})
}
