// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// See LICENSE for details.

// Package contracttests holds the generated contract tests for the Go SDK.
//
// The tests themselves are generated by @archastro/sdk-generator from the
// canonical OpenAPI spec; the handwritten files in this package boot the
// servers they run against — a Prism mock for the REST suite and the
// @archastro/channel-harness service for the channel and SSE suites.
//
// This file exists so the package has a non-test source file and therefore
// builds under `go build ./...`. There is nothing to import from here.
package contracttests
