// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: b16361f68231

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1AiChatCompletionsStreamCreateYieldsSSEEvents(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarness(t, func(h *harnessClient) {
		h.registerStreamScenario(t, map[string]any{
			"route":   "POST /api/v1/ai/chat/completions/stream",
			"actions": []any{map[string]any{"type": "autoEmit", "event": "done"}, map[string]any{"type": "autoEmit", "event": "error"}, map[string]any{"type": "autoEmit", "event": "message_complete"}, map[string]any{"type": "autoEmit", "event": "message_delta"}, map[string]any{"type": "autoEmit", "event": "thinking_delta"}, map[string]any{"type": "autoEmit", "event": "tool_call_delta"}, map[string]any{"type": "autoEmit", "event": "tool_result"}},
		})
		client := h.sdkClient()
		stream, err := client.V1.Ai.Chat.Completions.Stream.Create(ctx, platform.StreamCreateInput{Messages: []platform.StreamCreateInputMessagesItem{platform.StreamCreateInputMessagesItem{Role: "user"}}, Opts: platform.Ptr(platform.StreamCreateInputOpts{Model: "test-model"})})
		if err != nil {
			t.Fatalf("stream failed to open: %v", err)
		}
		defer stream.Close()
		var events []string
		for stream.Next() {
			events = append(events, stream.Event().Event)
		}
		if err := stream.Err(); err != nil {
			t.Fatalf("stream failed: %v", err)
		}
		requireStrings(t, events, []string{"done", "error", "message_complete", "message_delta", "thinking_delta", "tool_call_delta", "tool_result"})
	})
}

func TestV1AiChatCompletionsStreamCreateRejectsNon2xx(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarness(t, func(h *harnessClient) {
		h.registerStreamScenario(t, map[string]any{
			"route":   "POST /api/v1/ai/chat/completions/stream",
			"actions": []any{map[string]any{"type": "status", "code": 402, "body": map[string]any{"error": map[string]any{"code": "plan_not_entitled"}}}},
		})
		client := h.sdkClient()
		stream, err := client.V1.Ai.Chat.Completions.Stream.Create(ctx, platform.StreamCreateInput{Messages: []platform.StreamCreateInputMessagesItem{platform.StreamCreateInputMessagesItem{Role: "user"}}, Opts: platform.Ptr(platform.StreamCreateInputOpts{Model: "test-model"})})
		if err == nil {
			for stream.Next() {
			}
			err = stream.Err()
			stream.Close()
		}
		requireAPIError(t, err, 402)
	})
}
