// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: beb063ae9605

package contracttests

import (
	"context"
	"testing"
)

func TestV1AgentSessionsStreamYieldsSSEEvents(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarness(t, func(h *harnessClient) {
		h.registerStreamScenario(t, map[string]any{
			"route":   "GET /api/v1/agent_sessions/{agent_session}/stream",
			"actions": []any{map[string]any{"type": "autoEmit", "event": "session_update"}},
		})
		client := h.sdkClient()
		stream, err := client.V1.AgentSessions.Stream(ctx, "test-value")
		if err != nil {
			t.Fatalf("stream failed to open: %v", err)
		}
		defer stream.Close()
		var events []string
		for stream.Next() {
			events = append(events, stream.Event().Event)
		}
		if err := stream.Err(); err != nil {
			t.Fatalf("stream failed: %v", err)
		}
		requireStrings(t, events, []string{"session_update"})
	})
}

func TestV1AgentSessionsStreamRejectsNon2xx(t *testing.T) {
	requireChannelTests(t)
	ctx := context.Background()
	withHarness(t, func(h *harnessClient) {
		h.registerStreamScenario(t, map[string]any{
			"route":   "GET /api/v1/agent_sessions/{agent_session}/stream",
			"actions": []any{map[string]any{"type": "status", "code": 402, "body": map[string]any{"error": map[string]any{"code": "plan_not_entitled"}}}},
		})
		client := h.sdkClient()
		stream, err := client.V1.AgentSessions.Stream(ctx, "test-value")
		if err == nil {
			for stream.Next() {
			}
			err = stream.Err()
			stream.Close()
		}
		requireAPIError(t, err, 402)
	})
}
