// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 8622b443964c

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1AgentToolsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.List(ctx, platform.AgentToolListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.List(ctx, platform.AgentToolListParams{})
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.List(ctx, platform.AgentToolListParams{})
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsListError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentTools.List(ctx, platform.AgentToolListParams{})
	requireAPIError(t, err, 404)
}

func TestV1AgentToolsCatalogSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.Catalog(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsCatalogError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.Catalog(ctx)
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsCatalogError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.Catalog(ctx)
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.AgentTools.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1AgentToolsDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.AgentTools.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.AgentTools.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.AgentTools.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentToolsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentTools.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentToolsUpdateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.Update(ctx, "test-value", platform.AgentToolUpdateInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsUpdateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.Update(ctx, "test-value", platform.AgentToolUpdateInput{})
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsUpdateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.Update(ctx, "test-value", platform.AgentToolUpdateInput{})
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsUpdateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentTools.Update(ctx, "test-value", platform.AgentToolUpdateInput{})
	requireAPIError(t, err, 404)
}

func TestV1AgentToolsUpdateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentTools.Update(ctx, "test-value", platform.AgentToolUpdateInput{})
	requireAPIError(t, err, 422)
}

func TestV1AgentToolsActivateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.Activate(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsActivateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.Activate(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsActivateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.Activate(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsActivateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentTools.Activate(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentToolsActivateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentTools.Activate(ctx, "test-value")
	requireAPIError(t, err, 422)
}

func TestV1AgentToolsDeactivateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentTools.Deactivate(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentToolsDeactivateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentTools.Deactivate(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentToolsDeactivateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentTools.Deactivate(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentToolsDeactivateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentTools.Deactivate(ctx, "test-value")
	requireAPIError(t, err, 404)
}
