// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f5e60145173a

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1AutomationsInvokeSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Automations.Invoke(ctx, "test-value", platform.AutomationInvokeInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AutomationsInvokeError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Automations.Invoke(ctx, "test-value", platform.AutomationInvokeInput{})
	requireAPIError(t, err, 401)
}

func TestV1AutomationsInvokeError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Automations.Invoke(ctx, "test-value", platform.AutomationInvokeInput{})
	requireAPIError(t, err, 403)
}

func TestV1AutomationsInvokeError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.Automations.Invoke(ctx, "test-value", platform.AutomationInvokeInput{})
	requireAPIError(t, err, 404)
}

func TestV1AutomationsInvokeError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.Automations.Invoke(ctx, "test-value", platform.AutomationInvokeInput{})
	requireAPIError(t, err, 422)
}
