// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2dbf51503267

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1AutomationRunsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AutomationRuns.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AutomationRunsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AutomationRuns.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AutomationRunsGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AutomationRuns.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AutomationRunsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AutomationRuns.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AutomationRunsJournalSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AutomationRuns.Journal(ctx, "test-value", platform.AutomationRunJournalParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AutomationRunsJournalError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.AutomationRuns.Journal(ctx, "test-value", platform.AutomationRunJournalParams{})
	requireAPIError(t, err, 400)
}

func TestV1AutomationRunsJournalError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AutomationRuns.Journal(ctx, "test-value", platform.AutomationRunJournalParams{})
	requireAPIError(t, err, 401)
}

func TestV1AutomationRunsJournalError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AutomationRuns.Journal(ctx, "test-value", platform.AutomationRunJournalParams{})
	requireAPIError(t, err, 403)
}

func TestV1AutomationRunsJournalError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AutomationRuns.Journal(ctx, "test-value", platform.AutomationRunJournalParams{})
	requireAPIError(t, err, 404)
}
