// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 395a73fe3183

package contracttests

import (
	"context"
	"testing"
)

func TestV1AgentHealthActionsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentHealthActions.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentHealthActionsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentHealthActions.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentHealthActionsGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentHealthActions.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentHealthActionsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentHealthActions.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentHealthActionsVerifySuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentHealthActions.Verify(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentHealthActionsVerifyError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentHealthActions.Verify(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentHealthActionsVerifyError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentHealthActions.Verify(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentHealthActionsVerifyError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentHealthActions.Verify(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentHealthActionsVerifyError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentHealthActions.Verify(ctx, "test-value")
	requireAPIError(t, err, 422)
}
