// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 36e60a1c1a94

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1AgentSessionsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.List(ctx, platform.AgentSessionListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.List(ctx, platform.AgentSessionListParams{})
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.List(ctx, platform.AgentSessionListParams{})
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsListError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentSessions.List(ctx, platform.AgentSessionListParams{})
	requireAPIError(t, err, 422)
}

func TestV1AgentSessionsCreateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.Create(ctx, platform.AgentSessionCreateInput{Agent: "test-value", Instructions: "test-value"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsCreateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.Create(ctx, platform.AgentSessionCreateInput{Agent: "test-value", Instructions: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsCreateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.Create(ctx, platform.AgentSessionCreateInput{Agent: "test-value", Instructions: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsCreateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentSessions.Create(ctx, platform.AgentSessionCreateInput{Agent: "test-value", Instructions: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsCreateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentSessions.Create(ctx, platform.AgentSessionCreateInput{Agent: "test-value", Instructions: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1AgentSessionsDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.AgentSessions.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1AgentSessionsDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.AgentSessions.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.AgentSessions.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.AgentSessions.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentSessions.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsUpdateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.Update(ctx, "test-value", platform.AgentSessionUpdateInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsUpdateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.Update(ctx, "test-value", platform.AgentSessionUpdateInput{})
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsUpdateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.Update(ctx, "test-value", platform.AgentSessionUpdateInput{})
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsUpdateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentSessions.Update(ctx, "test-value", platform.AgentSessionUpdateInput{})
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsUpdateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentSessions.Update(ctx, "test-value", platform.AgentSessionUpdateInput{})
	requireAPIError(t, err, 422)
}

func TestV1AgentSessionsCancelSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.Cancel(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsCancelError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.Cancel(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsCancelError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.Cancel(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsCancelError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentSessions.Cancel(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsMessageSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.AgentSessions.Message(ctx, "test-value", platform.AgentSessionMessageInput{Content: "test content"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1AgentSessionsMessageError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.AgentSessions.Message(ctx, "test-value", platform.AgentSessionMessageInput{Content: "test content"})
	requireAPIError(t, err, 401)
}

func TestV1AgentSessionsMessageError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.AgentSessions.Message(ctx, "test-value", platform.AgentSessionMessageInput{Content: "test content"})
	requireAPIError(t, err, 403)
}

func TestV1AgentSessionsMessageError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.AgentSessions.Message(ctx, "test-value", platform.AgentSessionMessageInput{Content: "test content"})
	requireAPIError(t, err, 404)
}

func TestV1AgentSessionsMessageError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.AgentSessions.Message(ctx, "test-value", platform.AgentSessionMessageInput{Content: "test content"})
	requireAPIError(t, err, 422)
}
