// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: dd555eb8c395

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1CustomObjectsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.CustomObjects.List(ctx, platform.CustomObjectListParams{Type: "test"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1CustomObjectsListError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.CustomObjects.List(ctx, platform.CustomObjectListParams{Type: "test"})
	requireAPIError(t, err, 400)
}

func TestV1CustomObjectsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.CustomObjects.List(ctx, platform.CustomObjectListParams{Type: "test"})
	requireAPIError(t, err, 401)
}

func TestV1CustomObjectsCreateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.CustomObjects.Create(ctx, platform.CustomObjectCreateInput{Fields: map[string]platform.JSONValue{}, Type: "test"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1CustomObjectsCreateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.CustomObjects.Create(ctx, platform.CustomObjectCreateInput{Fields: map[string]platform.JSONValue{}, Type: "test"})
	requireAPIError(t, err, 401)
}

func TestV1CustomObjectsCreateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.CustomObjects.Create(ctx, platform.CustomObjectCreateInput{Fields: map[string]platform.JSONValue{}, Type: "test"})
	requireAPIError(t, err, 403)
}

func TestV1CustomObjectsCreateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.CustomObjects.Create(ctx, platform.CustomObjectCreateInput{Fields: map[string]platform.JSONValue{}, Type: "test"})
	requireAPIError(t, err, 404)
}

func TestV1CustomObjectsCreateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.CustomObjects.Create(ctx, platform.CustomObjectCreateInput{Fields: map[string]platform.JSONValue{}, Type: "test"})
	requireAPIError(t, err, 422)
}

func TestV1CustomObjectsDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.CustomObjects.Delete(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1CustomObjectsDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.CustomObjects.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1CustomObjectsDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.CustomObjects.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1CustomObjectsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.CustomObjects.Get(ctx, "test-value", platform.CustomObjectGetParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1CustomObjectsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.CustomObjects.Get(ctx, "test-value", platform.CustomObjectGetParams{})
	requireAPIError(t, err, 401)
}

func TestV1CustomObjectsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.CustomObjects.Get(ctx, "test-value", platform.CustomObjectGetParams{})
	requireAPIError(t, err, 404)
}

func TestV1CustomObjectsReplaceSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.CustomObjects.Replace(ctx, "test-value", platform.CustomObjectReplaceInput{Fields: map[string]platform.JSONValue{}})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1CustomObjectsReplaceError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.CustomObjects.Replace(ctx, "test-value", platform.CustomObjectReplaceInput{Fields: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 401)
}

func TestV1CustomObjectsReplaceError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.CustomObjects.Replace(ctx, "test-value", platform.CustomObjectReplaceInput{Fields: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 404)
}

func TestV1CustomObjectsReplaceError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.CustomObjects.Replace(ctx, "test-value", platform.CustomObjectReplaceInput{Fields: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 422)
}
