// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: c38571a539bc

package contracttests

import (
	"context"
	"testing"
)

func TestV1InstallationSourcesDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.InstallationSources.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1InstallationSourcesDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.InstallationSources.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1InstallationSourcesDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.InstallationSources.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1InstallationSourcesDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.InstallationSources.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}
