// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2786c79fd780

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1InternPluginsInvokeCreateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Intern.Plugins.Invoke.Create(ctx, platform.InvokeCreateInput{Installation: platform.Ptr(platform.InvokeCreateInputInstallation{Binding: "test-value", Config: map[string]platform.JSONValue{}, Plugin: "test-value", ProtocolVersion: 1}), Operation: "test-value"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1InternPluginsInvokeCreateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Intern.Plugins.Invoke.Create(ctx, platform.InvokeCreateInput{Installation: platform.Ptr(platform.InvokeCreateInputInstallation{Binding: "test-value", Config: map[string]platform.JSONValue{}, Plugin: "test-value", ProtocolVersion: 1}), Operation: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1InternPluginsInvokeCreateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.Intern.Plugins.Invoke.Create(ctx, platform.InvokeCreateInput{Installation: platform.Ptr(platform.InvokeCreateInputInstallation{Binding: "test-value", Config: map[string]platform.JSONValue{}, Plugin: "test-value", ProtocolVersion: 1}), Operation: "test-value"})
	requireAPIError(t, err, 422)
}
