// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a8b1e4b12a90

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1KnowledgeDocumentsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.KnowledgeDocuments.List(ctx, platform.KnowledgeDocumentListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result, result.Data)
}

func TestV1KnowledgeDocumentsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.KnowledgeDocuments.List(ctx, platform.KnowledgeDocumentListParams{})
	requireAPIError(t, err, 401)
}

func TestV1KnowledgeDocumentsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.KnowledgeDocuments.List(ctx, platform.KnowledgeDocumentListParams{})
	requireAPIError(t, err, 403)
}

func TestV1KnowledgeDocumentsDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.KnowledgeDocuments.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1KnowledgeDocumentsDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.KnowledgeDocuments.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1KnowledgeDocumentsDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.KnowledgeDocuments.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1KnowledgeDocumentsDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.KnowledgeDocuments.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1KnowledgeDocumentsGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.KnowledgeDocuments.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1KnowledgeDocumentsGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.KnowledgeDocuments.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1KnowledgeDocumentsGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.KnowledgeDocuments.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1KnowledgeDocumentsGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.KnowledgeDocuments.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1KnowledgeDocumentsContentSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.KnowledgeDocuments.Content(ctx, "test-value", platform.KnowledgeDocumentContentParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1KnowledgeDocumentsContentError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.KnowledgeDocuments.Content(ctx, "test-value", platform.KnowledgeDocumentContentParams{})
	requireAPIError(t, err, 401)
}

func TestV1KnowledgeDocumentsContentError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.KnowledgeDocuments.Content(ctx, "test-value", platform.KnowledgeDocumentContentParams{})
	requireAPIError(t, err, 403)
}

func TestV1KnowledgeDocumentsContentError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.KnowledgeDocuments.Content(ctx, "test-value", platform.KnowledgeDocumentContentParams{})
	requireAPIError(t, err, 404)
}

func TestV1KnowledgeDocumentsContentError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.KnowledgeDocuments.Content(ctx, "test-value", platform.KnowledgeDocumentContentParams{})
	requireAPIError(t, err, 422)
}
