// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a57b25c04e54

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1NotificationsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Notifications.List(ctx, platform.NotificationListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result, result.Data)
}

func TestV1NotificationsListError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.Notifications.List(ctx, platform.NotificationListParams{})
	requireAPIError(t, err, 400)
}

func TestV1NotificationsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Notifications.List(ctx, platform.NotificationListParams{})
	requireAPIError(t, err, 401)
}

func TestV1NotificationsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Notifications.List(ctx, platform.NotificationListParams{})
	requireAPIError(t, err, 403)
}

func TestV1NotificationsReadAllSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.Notifications.ReadAll(ctx); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1NotificationsReadAllError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.Notifications.ReadAll(ctx)
	requireAPIError(t, err, 401)
}

func TestV1NotificationsReadAllError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.Notifications.ReadAll(ctx)
	requireAPIError(t, err, 403)
}

func TestV1NotificationsSendSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1NotificationsSendError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	requireAPIError(t, err, 400)
}

func TestV1NotificationsSendError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1NotificationsSendError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1NotificationsSendError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1NotificationsSendError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.Notifications.Send(ctx, platform.NotificationSendInput{Type: "test", User: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1NotificationsUnreadCountSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Notifications.UnreadCount(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1NotificationsUnreadCountError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Notifications.UnreadCount(ctx)
	requireAPIError(t, err, 401)
}

func TestV1NotificationsUnreadCountError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Notifications.UnreadCount(ctx)
	requireAPIError(t, err, 403)
}

func TestV1NotificationsArchiveSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.Notifications.Archive(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1NotificationsArchiveError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.Notifications.Archive(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1NotificationsArchiveError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.Notifications.Archive(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1NotificationsArchiveError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.Notifications.Archive(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1NotificationsReadSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.Notifications.Read(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1NotificationsReadError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.Notifications.Read(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1NotificationsReadError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.Notifications.Read(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1NotificationsReadError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.Notifications.Read(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1NotificationsUnarchiveSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.Notifications.Unarchive(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1NotificationsUnarchiveError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.Notifications.Unarchive(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1NotificationsUnarchiveError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.Notifications.Unarchive(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1NotificationsUnarchiveError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.Notifications.Unarchive(ctx, "test-value")
	requireAPIError(t, err, 404)
}
