// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 57f1bcaee1c3

package contracttests

import (
	"context"
	"testing"
)

func TestV1SSHKeysDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.SSHKeys.Delete(ctx, "test-key"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1SSHKeysDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.SSHKeys.Delete(ctx, "test-key")
	requireAPIError(t, err, 401)
}

func TestV1SSHKeysDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.SSHKeys.Delete(ctx, "test-key")
	requireAPIError(t, err, 403)
}

func TestV1SSHKeysDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.SSHKeys.Delete(ctx, "test-key")
	requireAPIError(t, err, 404)
}
