// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: fda2fb2c8699

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1SandboxesCreateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Sandboxes.Create(ctx, platform.SandboxCreateInput{Name: "test-name", Slug: "test-value"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1SandboxesCreateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Sandboxes.Create(ctx, platform.SandboxCreateInput{Name: "test-name", Slug: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1SandboxesCreateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Sandboxes.Create(ctx, platform.SandboxCreateInput{Name: "test-name", Slug: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1SandboxesCreateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.Sandboxes.Create(ctx, platform.SandboxCreateInput{Name: "test-name", Slug: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1SandboxesCreateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.Sandboxes.Create(ctx, platform.SandboxCreateInput{Name: "test-name", Slug: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1SandboxesDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.Sandboxes.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1SandboxesDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.Sandboxes.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1SandboxesDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.Sandboxes.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1SandboxesDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.Sandboxes.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1SandboxesGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Sandboxes.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1SandboxesGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Sandboxes.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1SandboxesGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Sandboxes.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1SandboxesGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.Sandboxes.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1SandboxesKeysSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.Sandboxes.Keys(ctx, "test-value", platform.SandboxKeysInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1SandboxesKeysError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.Sandboxes.Keys(ctx, "test-value", platform.SandboxKeysInput{})
	requireAPIError(t, err, 401)
}

func TestV1SandboxesKeysError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.Sandboxes.Keys(ctx, "test-value", platform.SandboxKeysInput{})
	requireAPIError(t, err, 403)
}

func TestV1SandboxesKeysError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.Sandboxes.Keys(ctx, "test-value", platform.SandboxKeysInput{})
	requireAPIError(t, err, 404)
}

func TestV1SandboxesKeysError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.Sandboxes.Keys(ctx, "test-value", platform.SandboxKeysInput{})
	requireAPIError(t, err, 422)
}
