// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a8aba5b035db

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1SolutionCategoriesListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.SolutionCategories.List(ctx, platform.SolutionCategoryListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1SolutionCategoriesListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.SolutionCategories.List(ctx, platform.SolutionCategoryListParams{})
	requireAPIError(t, err, 401)
}

func TestV1SolutionCategoriesListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.SolutionCategories.List(ctx, platform.SolutionCategoryListParams{})
	requireAPIError(t, err, 403)
}
