// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 5df42cf358ba

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1ThreadMessagesDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.ThreadMessages.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1ThreadMessagesDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.ThreadMessages.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesDeleteError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.ThreadMessages.Delete(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.ThreadMessages.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesDeleteError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.ThreadMessages.Delete(ctx, "test-value")
	requireAPIError(t, err, 422)
}

func TestV1ThreadMessagesGetSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.ThreadMessages.Get(ctx, "test-value")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1ThreadMessagesGetError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.ThreadMessages.Get(ctx, "test-value")
	requireAPIError(t, err, 400)
}

func TestV1ThreadMessagesGetError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.ThreadMessages.Get(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesGetError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.ThreadMessages.Get(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesGetError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.ThreadMessages.Get(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesReplaceSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.ThreadMessages.Replace(ctx, "test-value", platform.ThreadMessageReplaceInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1ThreadMessagesReplaceError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.ThreadMessages.Replace(ctx, "test-value", platform.ThreadMessageReplaceInput{})
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesReplaceError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.ThreadMessages.Replace(ctx, "test-value", platform.ThreadMessageReplaceInput{})
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesReplaceError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.ThreadMessages.Replace(ctx, "test-value", platform.ThreadMessageReplaceInput{})
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesReplaceError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.ThreadMessages.Replace(ctx, "test-value", platform.ThreadMessageReplaceInput{})
	requireAPIError(t, err, 422)
}

func TestV1ThreadMessagesRepliesSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.ThreadMessages.Replies(ctx, "test-value", platform.ThreadMessageRepliesParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1ThreadMessagesRepliesError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.ThreadMessages.Replies(ctx, "test-value", platform.ThreadMessageRepliesParams{})
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesRepliesError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.ThreadMessages.Replies(ctx, "test-value", platform.ThreadMessageRepliesParams{})
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesRepliesError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.ThreadMessages.Replies(ctx, "test-value", platform.ThreadMessageRepliesParams{})
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesRepliesError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.ThreadMessages.Replies(ctx, "test-value", platform.ThreadMessageRepliesParams{})
	requireAPIError(t, err, 422)
}

func TestV1ThreadMessagesReactionsRemoveSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.ThreadMessages.Reactions.Remove(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1ThreadMessagesReactionsRemoveError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.ThreadMessages.Reactions.Remove(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesReactionsRemoveError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.ThreadMessages.Reactions.Remove(ctx, "test-value")
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesReactionsRemoveError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.ThreadMessages.Reactions.Remove(ctx, "test-value")
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesReactionsRemoveError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.ThreadMessages.Reactions.Remove(ctx, "test-value")
	requireAPIError(t, err, 422)
}

func TestV1ThreadMessagesReactionsCreateSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.ThreadMessages.Reactions.Create(ctx, "test-value", platform.ReactionCreateInput{Emoji: "test-value"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1ThreadMessagesReactionsCreateError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.ThreadMessages.Reactions.Create(ctx, "test-value", platform.ReactionCreateInput{Emoji: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1ThreadMessagesReactionsCreateError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.ThreadMessages.Reactions.Create(ctx, "test-value", platform.ReactionCreateInput{Emoji: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1ThreadMessagesReactionsCreateError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.ThreadMessages.Reactions.Create(ctx, "test-value", platform.ReactionCreateInput{Emoji: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1ThreadMessagesReactionsCreateError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.ThreadMessages.Reactions.Create(ctx, "test-value", platform.ReactionCreateInput{Emoji: "test-value"})
	requireAPIError(t, err, 422)
}
