// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: ea59e1368446

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1TeamMembershipsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.TeamMemberships.List(ctx, platform.TeamMembershipListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1TeamMembershipsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.TeamMemberships.List(ctx, platform.TeamMembershipListParams{})
	requireAPIError(t, err, 401)
}

func TestV1TeamMembershipsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.TeamMemberships.List(ctx, platform.TeamMembershipListParams{})
	requireAPIError(t, err, 403)
}

func TestV1TeamMembershipsDeleteSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.TeamMemberships.Delete(ctx, "test-value"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1TeamMembershipsDeleteError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.TeamMemberships.Delete(ctx, "test-value")
	requireAPIError(t, err, 401)
}

func TestV1TeamMembershipsDeleteError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.TeamMemberships.Delete(ctx, "test-value")
	requireAPIError(t, err, 404)
}
