// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a42787bcb435

package contracttests

import (
	"context"
	"github.com/ArchAstro/archastro-go/platform"
	"testing"
)

func TestV1WorkItemsListSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	result, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	use(result)
}

func TestV1WorkItemsListError400(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 400)
	_, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	requireAPIError(t, err, 400)
}

func TestV1WorkItemsListError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	_, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	requireAPIError(t, err, 401)
}

func TestV1WorkItemsListError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	_, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	requireAPIError(t, err, 403)
}

func TestV1WorkItemsListError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	_, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	requireAPIError(t, err, 404)
}

func TestV1WorkItemsListError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	_, err := client.V1.WorkItems.List(ctx, platform.WorkItemListParams{})
	requireAPIError(t, err, 422)
}

func TestV1WorkItemsFailSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1WorkItemsFailError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1WorkItemsFailError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1WorkItemsFailError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1WorkItemsFailError409(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 409)
	err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"})
	requireAPIError(t, err, 409)
}

func TestV1WorkItemsFailError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.WorkItems.Fail(ctx, "test-value", platform.WorkItemFailInput{Error: map[string]platform.JSONValue{}, LeaseOwner: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1WorkItemsHeartbeatSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1WorkItemsHeartbeatError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1WorkItemsHeartbeatError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1WorkItemsHeartbeatError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1WorkItemsHeartbeatError409(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 409)
	err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 409)
}

func TestV1WorkItemsHeartbeatError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.WorkItems.Heartbeat(ctx, "test-value", platform.WorkItemHeartbeatInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1WorkItemsStartSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1WorkItemsStartError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 401)
}

func TestV1WorkItemsStartError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 403)
}

func TestV1WorkItemsStartError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 404)
}

func TestV1WorkItemsStartError409(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 409)
	err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 409)
}

func TestV1WorkItemsStartError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.WorkItems.Start(ctx, "test-value", platform.WorkItemStartInput{LeaseOwner: "test-value"})
	requireAPIError(t, err, 422)
}

func TestV1WorkItemsSubmitSuccess(t *testing.T) {
	ctx := context.Background()
	client := restClient(t)
	if err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestV1WorkItemsSubmitError401(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 401)
	err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 401)
}

func TestV1WorkItemsSubmitError403(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 403)
	err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 403)
}

func TestV1WorkItemsSubmitError404(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 404)
	err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 404)
}

func TestV1WorkItemsSubmitError409(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 409)
	err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 409)
}

func TestV1WorkItemsSubmitError422(t *testing.T) {
	ctx := context.Background()
	client := errorClient(t, 422)
	err := client.V1.WorkItems.Submit(ctx, "test-value", platform.WorkItemSubmitInput{LeaseOwner: "test-value", Result: map[string]platform.JSONValue{}})
	requireAPIError(t, err, 422)
}
